/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global directory.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ActiveTeam
 */
export interface ActiveTeam {
    /**
     * 
     * @type {string}
     * @memberof ActiveTeam
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof ActiveTeam
     */
    teamId: string;
    /**
     * 
     * @type {string}
     * @memberof ActiveTeam
     */
    teamRole?: string;
    /**
     * 
     * @type {string}
     * @memberof ActiveTeam
     */
    homeRegionId: string;
    /**
     * 
     * @type {boolean}
     * @memberof ActiveTeam
     */
    defaultTeam?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ActiveTeam
     */
    edgeGatewayUrl?: string | null;
}

/**
 * Check if a given object implements the ActiveTeam interface.
 */
export function instanceOfActiveTeam(value: object): value is ActiveTeam {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('teamId' in value) || value['teamId'] === undefined) return false;
    if (!('homeRegionId' in value) || value['homeRegionId'] === undefined) return false;
    return true;
}

export function ActiveTeamFromJSON(json: any): ActiveTeam {
    return ActiveTeamFromJSONTyped(json, false);
}

export function ActiveTeamFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActiveTeam {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['user_id'],
        'teamId': json['team_id'],
        'teamRole': json['team_role'] == null ? undefined : json['team_role'],
        'homeRegionId': json['home_region_id'],
        'defaultTeam': json['default_team'] == null ? undefined : json['default_team'],
        'edgeGatewayUrl': json['edge_gateway_url'] == null ? undefined : json['edge_gateway_url'],
    };
}

export function ActiveTeamToJSON(json: any): ActiveTeam {
    return ActiveTeamToJSONTyped(json, false);
}

export function ActiveTeamToJSONTyped(value?: ActiveTeam | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_id': value['userId'],
        'team_id': value['teamId'],
        'team_role': value['teamRole'],
        'home_region_id': value['homeRegionId'],
        'default_team': value['defaultTeam'],
        'edge_gateway_url': value['edgeGatewayUrl'],
    };
}

