/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by internal-gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NodeAffinity } from './NodeAffinity';
import {
    NodeAffinityFromJSON,
    NodeAffinityFromJSONTyped,
    NodeAffinityToJSON,
    NodeAffinityToJSONTyped,
} from './NodeAffinity';
import type { PodAffinity } from './PodAffinity';
import {
    PodAffinityFromJSON,
    PodAffinityFromJSONTyped,
    PodAffinityToJSON,
    PodAffinityToJSONTyped,
} from './PodAffinity';

/**
 * 
 * @export
 * @interface Affinity
 */
export interface Affinity {
    /**
     * 
     * @type {NodeAffinity}
     * @memberof Affinity
     */
    nodeAffinity?: NodeAffinity;
    /**
     * 
     * @type {PodAffinity}
     * @memberof Affinity
     */
    podAffinity?: PodAffinity;
}

/**
 * Check if a given object implements the Affinity interface.
 */
export function instanceOfAffinity(value: object): value is Affinity {
    return true;
}

export function AffinityFromJSON(json: any): Affinity {
    return AffinityFromJSONTyped(json, false);
}

export function AffinityFromJSONTyped(json: any, ignoreDiscriminator: boolean): Affinity {
    if (json == null) {
        return json;
    }
    return {
        
        'nodeAffinity': json['nodeAffinity'] == null ? undefined : NodeAffinityFromJSON(json['nodeAffinity']),
        'podAffinity': json['podAffinity'] == null ? undefined : PodAffinityFromJSON(json['podAffinity']),
    };
}

export function AffinityToJSON(json: any): Affinity {
    return AffinityToJSONTyped(json, false);
}

export function AffinityToJSONTyped(value?: Affinity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nodeAffinity': NodeAffinityToJSON(value['nodeAffinity']),
        'podAffinity': PodAffinityToJSON(value['podAffinity']),
    };
}

