/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by internal-gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FileContentResponse } from './FileContentResponse';
import {
    FileContentResponseFromJSON,
    FileContentResponseFromJSONTyped,
    FileContentResponseToJSON,
    FileContentResponseToJSONTyped,
} from './FileContentResponse';

/**
 * 
 * @export
 * @interface ApiV1SandboxesIdFilesGet200Response
 */
export interface ApiV1SandboxesIdFilesGet200Response {
    /**
     * 
     * @type {boolean}
     * @memberof ApiV1SandboxesIdFilesGet200Response
     */
    success: boolean;
    /**
     * 
     * @type {FileContentResponse}
     * @memberof ApiV1SandboxesIdFilesGet200Response
     */
    data?: FileContentResponse;
}

/**
 * Check if a given object implements the ApiV1SandboxesIdFilesGet200Response interface.
 */
export function instanceOfApiV1SandboxesIdFilesGet200Response(value: object): value is ApiV1SandboxesIdFilesGet200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function ApiV1SandboxesIdFilesGet200ResponseFromJSON(json: any): ApiV1SandboxesIdFilesGet200Response {
    return ApiV1SandboxesIdFilesGet200ResponseFromJSONTyped(json, false);
}

export function ApiV1SandboxesIdFilesGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1SandboxesIdFilesGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': json['data'] == null ? undefined : FileContentResponseFromJSON(json['data']),
    };
}

export function ApiV1SandboxesIdFilesGet200ResponseToJSON(json: any): ApiV1SandboxesIdFilesGet200Response {
    return ApiV1SandboxesIdFilesGet200ResponseToJSONTyped(json, false);
}

export function ApiV1SandboxesIdFilesGet200ResponseToJSONTyped(value?: ApiV1SandboxesIdFilesGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': FileContentResponseToJSON(value['data']),
    };
}

