/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CloneVolumeFileResult
 */
export interface CloneVolumeFileResult {
    /**
     * 
     * @type {string}
     * @memberof CloneVolumeFileResult
     */
    sourceVolumeId: string;
    /**
     * 
     * @type {string}
     * @memberof CloneVolumeFileResult
     */
    sourcePath: string;
    /**
     * 
     * @type {string}
     * @memberof CloneVolumeFileResult
     */
    targetPath: string;
    /**
     * 
     * @type {string}
     * @memberof CloneVolumeFileResult
     */
    mode: CloneVolumeFileResultModeEnum;
    /**
     * 
     * @type {number}
     * @memberof CloneVolumeFileResult
     */
    sizeBytes: number;
}


/**
 * @export
 */
export const CloneVolumeFileResultModeEnum = {
    Cow: 'cow',
    Copy: 'copy'
} as const;
export type CloneVolumeFileResultModeEnum = typeof CloneVolumeFileResultModeEnum[keyof typeof CloneVolumeFileResultModeEnum];


/**
 * Check if a given object implements the CloneVolumeFileResult interface.
 */
export function instanceOfCloneVolumeFileResult(value: object): value is CloneVolumeFileResult {
    if (!('sourceVolumeId' in value) || value['sourceVolumeId'] === undefined) return false;
    if (!('sourcePath' in value) || value['sourcePath'] === undefined) return false;
    if (!('targetPath' in value) || value['targetPath'] === undefined) return false;
    if (!('mode' in value) || value['mode'] === undefined) return false;
    if (!('sizeBytes' in value) || value['sizeBytes'] === undefined) return false;
    return true;
}

export function CloneVolumeFileResultFromJSON(json: any): CloneVolumeFileResult {
    return CloneVolumeFileResultFromJSONTyped(json, false);
}

export function CloneVolumeFileResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): CloneVolumeFileResult {
    if (json == null) {
        return json;
    }
    return {
        
        'sourceVolumeId': json['source_volume_id'],
        'sourcePath': json['source_path'],
        'targetPath': json['target_path'],
        'mode': json['mode'],
        'sizeBytes': json['size_bytes'],
    };
}

export function CloneVolumeFileResultToJSON(json: any): CloneVolumeFileResult {
    return CloneVolumeFileResultToJSONTyped(json, false);
}

export function CloneVolumeFileResultToJSONTyped(value?: CloneVolumeFileResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'source_volume_id': value['sourceVolumeId'],
        'source_path': value['sourcePath'],
        'target_path': value['targetPath'],
        'mode': value['mode'],
        'size_bytes': value['sizeBytes'],
    };
}

