/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResourceQuota } from './ResourceQuota';
import {
    ResourceQuotaFromJSON,
    ResourceQuotaFromJSONTyped,
    ResourceQuotaToJSON,
    ResourceQuotaToJSONTyped,
} from './ResourceQuota';
import type { EnvVar } from './EnvVar';
import {
    EnvVarFromJSON,
    EnvVarFromJSONTyped,
    EnvVarToJSON,
    EnvVarToJSONTyped,
} from './EnvVar';

/**
 * 
 * @export
 * @interface ContainerSpec
 */
export interface ContainerSpec {
    /**
     * Canonical normalized OCI reference pinned by a lowercase SHA-256 digest. Mutable tags are rejected.
     * @type {string}
     * @memberof ContainerSpec
     */
    image: string;
    /**
     * 
     * @type {Array<EnvVar>}
     * @memberof ContainerSpec
     */
    env?: Array<EnvVar>;
    /**
     * 
     * @type {ResourceQuota}
     * @memberof ContainerSpec
     */
    resources: ResourceQuota;
    /**
     * Immutable gVisor guest privilege class. Privileged capabilities remain confined by runsc and do not expose host devices.
     * @type {string}
     * @memberof ContainerSpec
     */
    securityClass?: ContainerSpecSecurityClassEnum;
}


/**
 * @export
 */
export const ContainerSpecSecurityClassEnum = {
    Standard: 'standard',
    Privileged: 'privileged'
} as const;
export type ContainerSpecSecurityClassEnum = typeof ContainerSpecSecurityClassEnum[keyof typeof ContainerSpecSecurityClassEnum];


/**
 * Check if a given object implements the ContainerSpec interface.
 */
export function instanceOfContainerSpec(value: object): value is ContainerSpec {
    if (!('image' in value) || value['image'] === undefined) return false;
    if (!('resources' in value) || value['resources'] === undefined) return false;
    return true;
}

export function ContainerSpecFromJSON(json: any): ContainerSpec {
    return ContainerSpecFromJSONTyped(json, false);
}

export function ContainerSpecFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContainerSpec {
    if (json == null) {
        return json;
    }
    return {
        
        'image': json['image'],
        'env': json['env'] == null ? undefined : ((json['env'] as Array<any>).map(EnvVarFromJSON)),
        'resources': ResourceQuotaFromJSON(json['resources']),
        'securityClass': json['securityClass'] == null ? undefined : json['securityClass'],
    };
}

export function ContainerSpecToJSON(json: any): ContainerSpec {
    return ContainerSpecToJSONTyped(json, false);
}

export function ContainerSpecToJSONTyped(value?: ContainerSpec | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'image': value['image'],
        'env': value['env'] == null ? undefined : ((value['env'] as Array<any>).map(EnvVarToJSON)),
        'resources': ResourceQuotaToJSON(value['resources']),
        'securityClass': value['securityClass'],
    };
}

