/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateTeamRequest
 */
export interface CreateTeamRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateTeamRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTeamRequest
     */
    slug?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTeamRequest
     */
    homeRegionId?: string | null;
}

/**
 * Check if a given object implements the CreateTeamRequest interface.
 */
export function instanceOfCreateTeamRequest(value: object): value is CreateTeamRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateTeamRequestFromJSON(json: any): CreateTeamRequest {
    return CreateTeamRequestFromJSONTyped(json, false);
}

export function CreateTeamRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTeamRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'homeRegionId': json['home_region_id'] == null ? undefined : json['home_region_id'],
    };
}

export function CreateTeamRequestToJSON(json: any): CreateTeamRequest {
    return CreateTeamRequestToJSONTyped(json, false);
}

export function CreateTeamRequestToJSONTyped(value?: CreateTeamRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'slug': value['slug'],
        'home_region_id': value['homeRegionId'],
    };
}

