/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by internal-gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PTYSize } from './PTYSize';
import {
    PTYSizeFromJSON,
    PTYSizeFromJSONTyped,
    PTYSizeToJSON,
    PTYSizeToJSONTyped,
} from './PTYSize';
import type { ProcessType } from './ProcessType';
import {
    ProcessTypeFromJSON,
    ProcessTypeFromJSONTyped,
    ProcessTypeToJSON,
    ProcessTypeToJSONTyped,
} from './ProcessType';
import type { CreateREPLContextRequest } from './CreateREPLContextRequest';
import {
    CreateREPLContextRequestFromJSON,
    CreateREPLContextRequestFromJSONTyped,
    CreateREPLContextRequestToJSON,
    CreateREPLContextRequestToJSONTyped,
} from './CreateREPLContextRequest';
import type { CreateCMDContextRequest } from './CreateCMDContextRequest';
import {
    CreateCMDContextRequestFromJSON,
    CreateCMDContextRequestFromJSONTyped,
    CreateCMDContextRequestToJSON,
    CreateCMDContextRequestToJSONTyped,
} from './CreateCMDContextRequest';

/**
 * 
 * @export
 * @interface CreateContextRequest
 */
export interface CreateContextRequest {
    /**
     * 
     * @type {ProcessType}
     * @memberof CreateContextRequest
     */
    type?: ProcessType;
    /**
     * 
     * @type {CreateREPLContextRequest}
     * @memberof CreateContextRequest
     */
    repl?: CreateREPLContextRequest;
    /**
     * 
     * @type {CreateCMDContextRequest}
     * @memberof CreateContextRequest
     */
    cmd?: CreateCMDContextRequest;
    /**
     * 
     * @type {boolean}
     * @memberof CreateContextRequest
     */
    waitUntilDone?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CreateContextRequest
     */
    cwd?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof CreateContextRequest
     */
    envVars?: { [key: string]: string; };
    /**
     * 
     * @type {PTYSize}
     * @memberof CreateContextRequest
     */
    ptySize?: PTYSize;
    /**
     * 
     * @type {number}
     * @memberof CreateContextRequest
     */
    idleTimeoutSec?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateContextRequest
     */
    ttlSec?: number;
}



/**
 * Check if a given object implements the CreateContextRequest interface.
 */
export function instanceOfCreateContextRequest(value: object): value is CreateContextRequest {
    return true;
}

export function CreateContextRequestFromJSON(json: any): CreateContextRequest {
    return CreateContextRequestFromJSONTyped(json, false);
}

export function CreateContextRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateContextRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : ProcessTypeFromJSON(json['type']),
        'repl': json['repl'] == null ? undefined : CreateREPLContextRequestFromJSON(json['repl']),
        'cmd': json['cmd'] == null ? undefined : CreateCMDContextRequestFromJSON(json['cmd']),
        'waitUntilDone': json['wait_until_done'] == null ? undefined : json['wait_until_done'],
        'cwd': json['cwd'] == null ? undefined : json['cwd'],
        'envVars': json['env_vars'] == null ? undefined : json['env_vars'],
        'ptySize': json['pty_size'] == null ? undefined : PTYSizeFromJSON(json['pty_size']),
        'idleTimeoutSec': json['idle_timeout_sec'] == null ? undefined : json['idle_timeout_sec'],
        'ttlSec': json['ttl_sec'] == null ? undefined : json['ttl_sec'],
    };
}

export function CreateContextRequestToJSON(json: any): CreateContextRequest {
    return CreateContextRequestToJSONTyped(json, false);
}

export function CreateContextRequestToJSONTyped(value?: CreateContextRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': ProcessTypeToJSON(value['type']),
        'repl': CreateREPLContextRequestToJSON(value['repl']),
        'cmd': CreateCMDContextRequestToJSON(value['cmd']),
        'wait_until_done': value['waitUntilDone'],
        'cwd': value['cwd'],
        'env_vars': value['envVars'],
        'pty_size': PTYSizeToJSON(value['ptySize']),
        'idle_timeout_sec': value['idleTimeoutSec'],
        'ttl_sec': value['ttlSec'],
    };
}

