/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global directory.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateRegionRequest
 */
export interface CreateRegionRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateRegionRequest
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CreateRegionRequest
     */
    displayName?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateRegionRequest
     */
    edgeGatewayUrl: string;
    /**
     * 
     * @type {string}
     * @memberof CreateRegionRequest
     */
    meteringExportUrl?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof CreateRegionRequest
     */
    enabled?: boolean;
}

/**
 * Check if a given object implements the CreateRegionRequest interface.
 */
export function instanceOfCreateRegionRequest(value: object): value is CreateRegionRequest {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('edgeGatewayUrl' in value) || value['edgeGatewayUrl'] === undefined) return false;
    return true;
}

export function CreateRegionRequestFromJSON(json: any): CreateRegionRequest {
    return CreateRegionRequestFromJSONTyped(json, false);
}

export function CreateRegionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateRegionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'displayName': json['display_name'] == null ? undefined : json['display_name'],
        'edgeGatewayUrl': json['edge_gateway_url'],
        'meteringExportUrl': json['metering_export_url'] == null ? undefined : json['metering_export_url'],
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
    };
}

export function CreateRegionRequestToJSON(json: any): CreateRegionRequest {
    return CreateRegionRequestToJSONTyped(json, false);
}

export function CreateRegionRequestToJSONTyped(value?: CreateRegionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'display_name': value['displayName'],
        'edge_gateway_url': value['edgeGatewayUrl'],
        'metering_export_url': value['meteringExportUrl'],
        'enabled': value['enabled'],
    };
}

