/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CredentialSourceResolverKind } from './CredentialSourceResolverKind';
import {
    CredentialSourceResolverKindFromJSON,
    CredentialSourceResolverKindFromJSONTyped,
    CredentialSourceResolverKindToJSON,
    CredentialSourceResolverKindToJSONTyped,
} from './CredentialSourceResolverKind';

/**
 * 
 * @export
 * @interface CredentialSourceMetadata
 */
export interface CredentialSourceMetadata {
    /**
     * 
     * @type {string}
     * @memberof CredentialSourceMetadata
     */
    name: string;
    /**
     * 
     * @type {CredentialSourceResolverKind}
     * @memberof CredentialSourceMetadata
     */
    resolverKind: CredentialSourceResolverKind;
    /**
     * 
     * @type {number}
     * @memberof CredentialSourceMetadata
     */
    currentVersion?: number;
    /**
     * 
     * @type {string}
     * @memberof CredentialSourceMetadata
     */
    status?: string;
    /**
     * 
     * @type {Date}
     * @memberof CredentialSourceMetadata
     */
    createdAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof CredentialSourceMetadata
     */
    updatedAt?: Date | null;
}



/**
 * Check if a given object implements the CredentialSourceMetadata interface.
 */
export function instanceOfCredentialSourceMetadata(value: object): value is CredentialSourceMetadata {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('resolverKind' in value) || value['resolverKind'] === undefined) return false;
    return true;
}

export function CredentialSourceMetadataFromJSON(json: any): CredentialSourceMetadata {
    return CredentialSourceMetadataFromJSONTyped(json, false);
}

export function CredentialSourceMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CredentialSourceMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'resolverKind': CredentialSourceResolverKindFromJSON(json['resolverKind']),
        'currentVersion': json['currentVersion'] == null ? undefined : json['currentVersion'],
        'status': json['status'] == null ? undefined : json['status'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function CredentialSourceMetadataToJSON(json: any): CredentialSourceMetadata {
    return CredentialSourceMetadataToJSONTyped(json, false);
}

export function CredentialSourceMetadataToJSONTyped(value?: CredentialSourceMetadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'resolverKind': CredentialSourceResolverKindToJSON(value['resolverKind']),
        'currentVersion': value['currentVersion'],
        'status': value['status'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

