/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global directory.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StaticUsernamePasswordSourceSpec } from './StaticUsernamePasswordSourceSpec';
import {
    StaticUsernamePasswordSourceSpecFromJSON,
    StaticUsernamePasswordSourceSpecFromJSONTyped,
    StaticUsernamePasswordSourceSpecToJSON,
    StaticUsernamePasswordSourceSpecToJSONTyped,
} from './StaticUsernamePasswordSourceSpec';
import type { StaticHeadersSourceSpec } from './StaticHeadersSourceSpec';
import {
    StaticHeadersSourceSpecFromJSON,
    StaticHeadersSourceSpecFromJSONTyped,
    StaticHeadersSourceSpecToJSON,
    StaticHeadersSourceSpecToJSONTyped,
} from './StaticHeadersSourceSpec';
import type { StaticTLSClientCertificateSourceSpec } from './StaticTLSClientCertificateSourceSpec';
import {
    StaticTLSClientCertificateSourceSpecFromJSON,
    StaticTLSClientCertificateSourceSpecFromJSONTyped,
    StaticTLSClientCertificateSourceSpecToJSON,
    StaticTLSClientCertificateSourceSpecToJSONTyped,
} from './StaticTLSClientCertificateSourceSpec';

/**
 * 
 * @export
 * @interface CredentialSourceWriteSpec
 */
export interface CredentialSourceWriteSpec {
    /**
     * 
     * @type {StaticHeadersSourceSpec}
     * @memberof CredentialSourceWriteSpec
     */
    staticHeaders?: StaticHeadersSourceSpec;
    /**
     * 
     * @type {StaticTLSClientCertificateSourceSpec}
     * @memberof CredentialSourceWriteSpec
     */
    staticTLSClientCertificate?: StaticTLSClientCertificateSourceSpec;
    /**
     * 
     * @type {StaticUsernamePasswordSourceSpec}
     * @memberof CredentialSourceWriteSpec
     */
    staticUsernamePassword?: StaticUsernamePasswordSourceSpec;
}

/**
 * Check if a given object implements the CredentialSourceWriteSpec interface.
 */
export function instanceOfCredentialSourceWriteSpec(value: object): value is CredentialSourceWriteSpec {
    return true;
}

export function CredentialSourceWriteSpecFromJSON(json: any): CredentialSourceWriteSpec {
    return CredentialSourceWriteSpecFromJSONTyped(json, false);
}

export function CredentialSourceWriteSpecFromJSONTyped(json: any, ignoreDiscriminator: boolean): CredentialSourceWriteSpec {
    if (json == null) {
        return json;
    }
    return {
        
        'staticHeaders': json['staticHeaders'] == null ? undefined : StaticHeadersSourceSpecFromJSON(json['staticHeaders']),
        'staticTLSClientCertificate': json['staticTLSClientCertificate'] == null ? undefined : StaticTLSClientCertificateSourceSpecFromJSON(json['staticTLSClientCertificate']),
        'staticUsernamePassword': json['staticUsernamePassword'] == null ? undefined : StaticUsernamePasswordSourceSpecFromJSON(json['staticUsernamePassword']),
    };
}

export function CredentialSourceWriteSpecToJSON(json: any): CredentialSourceWriteSpec {
    return CredentialSourceWriteSpecToJSONTyped(json, false);
}

export function CredentialSourceWriteSpecToJSONTyped(value?: CredentialSourceWriteSpec | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'staticHeaders': StaticHeadersSourceSpecToJSON(value['staticHeaders']),
        'staticTLSClientCertificate': StaticTLSClientCertificateSourceSpecToJSON(value['staticTLSClientCertificate']),
        'staticUsernamePassword': StaticUsernamePasswordSourceSpecToJSON(value['staticUsernamePassword']),
    };
}

