/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const CredentialSourceResolverKind = {
    StaticHeaders: 'static_headers',
    StaticTlsClientCertificate: 'static_tls_client_certificate',
    StaticUsernamePassword: 'static_username_password'
} as const;
export type CredentialSourceResolverKind = typeof CredentialSourceResolverKind[keyof typeof CredentialSourceResolverKind];


export function instanceOfCredentialSourceResolverKind(value: any): boolean {
    for (const key in CredentialSourceResolverKind) {
        if (Object.prototype.hasOwnProperty.call(CredentialSourceResolverKind, key)) {
            if (CredentialSourceResolverKind[key as keyof typeof CredentialSourceResolverKind] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CredentialSourceResolverKindFromJSON(json: any): CredentialSourceResolverKind {
    return CredentialSourceResolverKindFromJSONTyped(json, false);
}

export function CredentialSourceResolverKindFromJSONTyped(json: any, ignoreDiscriminator: boolean): CredentialSourceResolverKind {
    return json as CredentialSourceResolverKind;
}

export function CredentialSourceResolverKindToJSON(value?: CredentialSourceResolverKind | null): any {
    return value as any;
}

export function CredentialSourceResolverKindToJSONTyped(value: any, ignoreDiscriminator: boolean): CredentialSourceResolverKind {
    return value as CredentialSourceResolverKind;
}

