/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LoginResponse } from './LoginResponse';
import {
    LoginResponseFromJSON,
    LoginResponseFromJSONTyped,
    LoginResponseToJSON,
    LoginResponseToJSONTyped,
} from './LoginResponse';

/**
 * 
 * @export
 * @interface DeviceLoginPollResponse
 */
export interface DeviceLoginPollResponse {
    /**
     * 
     * @type {string}
     * @memberof DeviceLoginPollResponse
     */
    status: DeviceLoginPollResponseStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof DeviceLoginPollResponse
     */
    intervalSeconds?: number;
    /**
     * 
     * @type {number}
     * @memberof DeviceLoginPollResponse
     */
    expiresAt?: number;
    /**
     * 
     * @type {LoginResponse}
     * @memberof DeviceLoginPollResponse
     */
    login?: LoginResponse;
}


/**
 * @export
 */
export const DeviceLoginPollResponseStatusEnum = {
    Pending: 'pending',
    SlowDown: 'slow_down',
    Completed: 'completed'
} as const;
export type DeviceLoginPollResponseStatusEnum = typeof DeviceLoginPollResponseStatusEnum[keyof typeof DeviceLoginPollResponseStatusEnum];


/**
 * Check if a given object implements the DeviceLoginPollResponse interface.
 */
export function instanceOfDeviceLoginPollResponse(value: object): value is DeviceLoginPollResponse {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function DeviceLoginPollResponseFromJSON(json: any): DeviceLoginPollResponse {
    return DeviceLoginPollResponseFromJSONTyped(json, false);
}

export function DeviceLoginPollResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeviceLoginPollResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'intervalSeconds': json['interval_seconds'] == null ? undefined : json['interval_seconds'],
        'expiresAt': json['expires_at'] == null ? undefined : json['expires_at'],
        'login': json['login'] == null ? undefined : LoginResponseFromJSON(json['login']),
    };
}

export function DeviceLoginPollResponseToJSON(json: any): DeviceLoginPollResponse {
    return DeviceLoginPollResponseToJSONTyped(json, false);
}

export function DeviceLoginPollResponseToJSONTyped(value?: DeviceLoginPollResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'interval_seconds': value['intervalSeconds'],
        'expires_at': value['expiresAt'],
        'login': LoginResponseToJSON(value['login']),
    };
}

