/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EphemeralMountSpec
 */
export interface EphemeralMountSpec {
    /**
     * 
     * @type {string}
     * @memberof EphemeralMountSpec
     */
    mountPath: string;
    /**
     * Exact byte quantity between 1Mi and 1Ti. The tmpfs remains subject to the sandbox memory cgroup.
     * @type {string}
     * @memberof EphemeralMountSpec
     */
    sizeLimit: string;
}

/**
 * Check if a given object implements the EphemeralMountSpec interface.
 */
export function instanceOfEphemeralMountSpec(value: object): value is EphemeralMountSpec {
    if (!('mountPath' in value) || value['mountPath'] === undefined) return false;
    if (!('sizeLimit' in value) || value['sizeLimit'] === undefined) return false;
    return true;
}

export function EphemeralMountSpecFromJSON(json: any): EphemeralMountSpec {
    return EphemeralMountSpecFromJSONTyped(json, false);
}

export function EphemeralMountSpecFromJSONTyped(json: any, ignoreDiscriminator: boolean): EphemeralMountSpec {
    if (json == null) {
        return json;
    }
    return {
        
        'mountPath': json['mountPath'],
        'sizeLimit': json['sizeLimit'],
    };
}

export function EphemeralMountSpecToJSON(json: any): EphemeralMountSpec {
    return EphemeralMountSpecToJSONTyped(json, false);
}

export function EphemeralMountSpecToJSONTyped(value?: EphemeralMountSpec | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mountPath': value['mountPath'],
        'sizeLimit': value['sizeLimit'],
    };
}

