/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ExecutionSessionDesiredState = {
    ExecutionSessionDesiredStateRunning: 'running',
    ExecutionSessionDesiredStateStopped: 'stopped'
} as const;
export type ExecutionSessionDesiredState = typeof ExecutionSessionDesiredState[keyof typeof ExecutionSessionDesiredState];


export function instanceOfExecutionSessionDesiredState(value: any): boolean {
    for (const key in ExecutionSessionDesiredState) {
        if (Object.prototype.hasOwnProperty.call(ExecutionSessionDesiredState, key)) {
            if (ExecutionSessionDesiredState[key as keyof typeof ExecutionSessionDesiredState] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ExecutionSessionDesiredStateFromJSON(json: any): ExecutionSessionDesiredState {
    return ExecutionSessionDesiredStateFromJSONTyped(json, false);
}

export function ExecutionSessionDesiredStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExecutionSessionDesiredState {
    return json as ExecutionSessionDesiredState;
}

export function ExecutionSessionDesiredStateToJSON(value?: ExecutionSessionDesiredState | null): any {
    return value as any;
}

export function ExecutionSessionDesiredStateToJSONTyped(value: any, ignoreDiscriminator: boolean): ExecutionSessionDesiredState {
    return value as ExecutionSessionDesiredState;
}

