/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ExecutionSessionWebSocketInput
 */
export interface ExecutionSessionWebSocketInput {
    /**
     * Client-generated operation identifier used to deduplicate recorded retries.
     * @type {string}
     * @memberof ExecutionSessionWebSocketInput
     */
    inputId: string;
    /**
     *
     * @type {string}
     * @memberof ExecutionSessionWebSocketInput
     */
    expectedAttemptId?: string;
    /**
     * Base64-encoded input bytes accepted into the current attempt input queue. WebSocket closure never implies EOF.
     * @type {string}
     * @memberof ExecutionSessionWebSocketInput
     */
    dataBase64?: string;
    /**
     *
     * @type {boolean}
     * @memberof ExecutionSessionWebSocketInput
     */
    eof?: boolean;
    /**
     *
     * @type {string}
     * @memberof ExecutionSessionWebSocketInput
     */
    type: ExecutionSessionWebSocketInputTypeEnum;
    /**
     *
     * @type {string}
     * @memberof ExecutionSessionWebSocketInput
     */
    requestId?: string;
}


/**
 * @export
 */
export const ExecutionSessionWebSocketInputTypeEnum = {
    Input: 'input'
} as const;
export type ExecutionSessionWebSocketInputTypeEnum = typeof ExecutionSessionWebSocketInputTypeEnum[keyof typeof ExecutionSessionWebSocketInputTypeEnum];


/**
 * Check if a given object implements the ExecutionSessionWebSocketInput interface.
 */
export function instanceOfExecutionSessionWebSocketInput(value: object): value is ExecutionSessionWebSocketInput {
    if (!('inputId' in value) || value['inputId'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function ExecutionSessionWebSocketInputFromJSON(json: any): ExecutionSessionWebSocketInput {
    return ExecutionSessionWebSocketInputFromJSONTyped(json, false);
}

export function ExecutionSessionWebSocketInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExecutionSessionWebSocketInput {
    if (json == null) {
        return json;
    }
    return {

        'inputId': json['input_id'],
        'expectedAttemptId': json['expected_attempt_id'] == null ? undefined : json['expected_attempt_id'],
        'dataBase64': json['data_base64'] == null ? undefined : json['data_base64'],
        'eof': json['eof'] == null ? undefined : json['eof'],
        'type': json['type'],
        'requestId': json['request_id'] == null ? undefined : json['request_id'],
    };
}

export function ExecutionSessionWebSocketInputToJSON(json: any): ExecutionSessionWebSocketInput {
    return ExecutionSessionWebSocketInputToJSONTyped(json, false);
}

export function ExecutionSessionWebSocketInputToJSONTyped(value?: ExecutionSessionWebSocketInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'input_id': value['inputId'],
        'expected_attempt_id': value['expectedAttemptId'],
        'data_base64': value['dataBase64'],
        'eof': value['eof'],
        'type': value['type'],
        'request_id': value['requestId'],
    };
}

