/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ExecutionSessionSignalRequest
 */
export interface ExecutionSessionSignalRequest {
    /**
     *
     * @type {string}
     * @memberof ExecutionSessionSignalRequest
     */
    signal: string;
    /**
     *
     * @type {string}
     * @memberof ExecutionSessionSignalRequest
     */
    expectedAttemptId?: string;
}

/**
 * Check if a given object implements the ExecutionSessionSignalRequest interface.
 */
export function instanceOfExecutionSessionSignalRequest(value: object): value is ExecutionSessionSignalRequest {
    if (!('signal' in value) || value['signal'] === undefined) return false;
    return true;
}

export function ExecutionSessionSignalRequestFromJSON(json: any): ExecutionSessionSignalRequest {
    return ExecutionSessionSignalRequestFromJSONTyped(json, false);
}

export function ExecutionSessionSignalRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExecutionSessionSignalRequest {
    if (json == null) {
        return json;
    }
    return {

        'signal': json['signal'],
        'expectedAttemptId': json['expected_attempt_id'] == null ? undefined : json['expected_attempt_id'],
    };
}

export function ExecutionSessionSignalRequestToJSON(json: any): ExecutionSessionSignalRequest {
    return ExecutionSessionSignalRequestToJSONTyped(json, false);
}

export function ExecutionSessionSignalRequestToJSONTyped(value?: ExecutionSessionSignalRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'signal': value['signal'],
        'expected_attempt_id': value['expectedAttemptId'],
    };
}
