/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ExecutionSessionAttempt
 */
export interface ExecutionSessionAttempt {
    /**
     *
     * @type {string}
     * @memberof ExecutionSessionAttempt
     */
    id: string;
    /**
     *
     * @type {number}
     * @memberof ExecutionSessionAttempt
     */
    number: number;
    /**
     *
     * @type {number}
     * @memberof ExecutionSessionAttempt
     */
    runtimeGeneration: number;
    /**
     *
     * @type {number}
     * @memberof ExecutionSessionAttempt
     */
    pid?: number;
    /**
     *
     * @type {Date}
     * @memberof ExecutionSessionAttempt
     */
    startedAt?: Date;
    /**
     *
     * @type {Date}
     * @memberof ExecutionSessionAttempt
     */
    finishedAt?: Date;
    /**
     *
     * @type {number}
     * @memberof ExecutionSessionAttempt
     */
    exitCode?: number;
    /**
     *
     * @type {string}
     * @memberof ExecutionSessionAttempt
     */
    reason?: string;
}

/**
 * Check if a given object implements the ExecutionSessionAttempt interface.
 */
export function instanceOfExecutionSessionAttempt(value: object): value is ExecutionSessionAttempt {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('number' in value) || value['number'] === undefined) return false;
    if (!('runtimeGeneration' in value) || value['runtimeGeneration'] === undefined) return false;
    return true;
}

export function ExecutionSessionAttemptFromJSON(json: any): ExecutionSessionAttempt {
    return ExecutionSessionAttemptFromJSONTyped(json, false);
}

export function ExecutionSessionAttemptFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExecutionSessionAttempt {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'number': json['number'],
        'runtimeGeneration': json['runtime_generation'],
        'pid': json['pid'] == null ? undefined : json['pid'],
        'startedAt': json['started_at'] == null ? undefined : (new Date(json['started_at'])),
        'finishedAt': json['finished_at'] == null ? undefined : (new Date(json['finished_at'])),
        'exitCode': json['exit_code'] == null ? undefined : json['exit_code'],
        'reason': json['reason'] == null ? undefined : json['reason'],
    };
}

export function ExecutionSessionAttemptToJSON(json: any): ExecutionSessionAttempt {
    return ExecutionSessionAttemptToJSONTyped(json, false);
}

export function ExecutionSessionAttemptToJSONTyped(value?: ExecutionSessionAttempt | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'number': value['number'],
        'runtime_generation': value['runtimeGeneration'],
        'pid': value['pid'],
        'started_at': value['startedAt'] == null ? value['startedAt'] : value['startedAt'].toISOString(),
        'finished_at': value['finishedAt'] == null ? value['finishedAt'] : value['finishedAt'].toISOString(),
        'exit_code': value['exitCode'],
        'reason': value['reason'],
    };
}
