/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Declares how descendants of this trusted supervisor process expose a
 * logical execution scope. The runtime reads only the named environment
 * variable and never exports the descendant process environment.
 * 
 * @export
 * @interface ExecutionSessionScopeSpec
 */
export interface ExecutionSessionScopeSpec {
    /**
     * Producer namespace for the logical scope, for example codex.
     * @type {string}
     * @memberof ExecutionSessionScopeSpec
     */
    namespace: string;
    /**
     * Native scope kind, for example native_session.
     * @type {string}
     * @memberof ExecutionSessionScopeSpec
     */
    kind: string;
    /**
     * Environment variable carrying the native scope identifier in descendant processes.
     * @type {string}
     * @memberof ExecutionSessionScopeSpec
     */
    idEnvironmentVariable: string;
}

/**
 * Check if a given object implements the ExecutionSessionScopeSpec interface.
 */
export function instanceOfExecutionSessionScopeSpec(value: object): value is ExecutionSessionScopeSpec {
    if (!('namespace' in value) || value['namespace'] === undefined) return false;
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('idEnvironmentVariable' in value) || value['idEnvironmentVariable'] === undefined) return false;
    return true;
}

export function ExecutionSessionScopeSpecFromJSON(json: any): ExecutionSessionScopeSpec {
    return ExecutionSessionScopeSpecFromJSONTyped(json, false);
}

export function ExecutionSessionScopeSpecFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExecutionSessionScopeSpec {
    if (json == null) {
        return json;
    }
    return {
        
        'namespace': json['namespace'],
        'kind': json['kind'],
        'idEnvironmentVariable': json['id_environment_variable'],
    };
}

export function ExecutionSessionScopeSpecToJSON(json: any): ExecutionSessionScopeSpec {
    return ExecutionSessionScopeSpecToJSONTyped(json, false);
}

export function ExecutionSessionScopeSpecToJSONTyped(value?: ExecutionSessionScopeSpec | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'namespace': value['namespace'],
        'kind': value['kind'],
        'id_environment_variable': value['idEnvironmentVariable'],
    };
}

