/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExecutionSessionDesiredState } from './ExecutionSessionDesiredState';
import {
    ExecutionSessionDesiredStateFromJSON,
    ExecutionSessionDesiredStateFromJSONTyped,
    ExecutionSessionDesiredStateToJSON,
    ExecutionSessionDesiredStateToJSONTyped,
} from './ExecutionSessionDesiredState';

/**
 *
 * @export
 * @interface ExecutionSessionDesiredStateRequest
 */
export interface ExecutionSessionDesiredStateRequest {
    /**
     *
     * @type {ExecutionSessionDesiredState}
     * @memberof ExecutionSessionDesiredStateRequest
     */
    state: ExecutionSessionDesiredState;
}



/**
 * Check if a given object implements the ExecutionSessionDesiredStateRequest interface.
 */
export function instanceOfExecutionSessionDesiredStateRequest(value: object): value is ExecutionSessionDesiredStateRequest {
    if (!('state' in value) || value['state'] === undefined) return false;
    return true;
}

export function ExecutionSessionDesiredStateRequestFromJSON(json: any): ExecutionSessionDesiredStateRequest {
    return ExecutionSessionDesiredStateRequestFromJSONTyped(json, false);
}

export function ExecutionSessionDesiredStateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExecutionSessionDesiredStateRequest {
    if (json == null) {
        return json;
    }
    return {

        'state': ExecutionSessionDesiredStateFromJSON(json['state']),
    };
}

export function ExecutionSessionDesiredStateRequestToJSON(json: any): ExecutionSessionDesiredStateRequest {
    return ExecutionSessionDesiredStateRequestToJSONTyped(json, false);
}

export function ExecutionSessionDesiredStateRequestToJSONTyped(value?: ExecutionSessionDesiredStateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'state': ExecutionSessionDesiredStateToJSON(value['state']),
    };
}

