/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by internal-gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FileWatchSubscribeRequest
 */
export interface FileWatchSubscribeRequest {
    /**
     * 
     * @type {string}
     * @memberof FileWatchSubscribeRequest
     */
    action: FileWatchSubscribeRequestActionEnum;
    /**
     * 
     * @type {string}
     * @memberof FileWatchSubscribeRequest
     */
    path: string;
    /**
     * 
     * @type {boolean}
     * @memberof FileWatchSubscribeRequest
     */
    recursive?: boolean;
}


/**
 * @export
 */
export const FileWatchSubscribeRequestActionEnum = {
    Subscribe: 'subscribe'
} as const;
export type FileWatchSubscribeRequestActionEnum = typeof FileWatchSubscribeRequestActionEnum[keyof typeof FileWatchSubscribeRequestActionEnum];


/**
 * Check if a given object implements the FileWatchSubscribeRequest interface.
 */
export function instanceOfFileWatchSubscribeRequest(value: object): value is FileWatchSubscribeRequest {
    if (!('action' in value) || value['action'] === undefined) return false;
    if (!('path' in value) || value['path'] === undefined) return false;
    return true;
}

export function FileWatchSubscribeRequestFromJSON(json: any): FileWatchSubscribeRequest {
    return FileWatchSubscribeRequestFromJSONTyped(json, false);
}

export function FileWatchSubscribeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileWatchSubscribeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'action': json['action'],
        'path': json['path'],
        'recursive': json['recursive'] == null ? undefined : json['recursive'],
    };
}

export function FileWatchSubscribeRequestToJSON(json: any): FileWatchSubscribeRequest {
    return FileWatchSubscribeRequestToJSONTyped(json, false);
}

export function FileWatchSubscribeRequestToJSONTyped(value?: FileWatchSubscribeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'action': value['action'],
        'path': value['path'],
        'recursive': value['recursive'],
    };
}

