/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FunctionRuntimeState } from './FunctionRuntimeState';
import {
    FunctionRuntimeStateFromJSON,
    FunctionRuntimeStateFromJSONTyped,
    FunctionRuntimeStateToJSON,
    FunctionRuntimeStateToJSONTyped,
} from './FunctionRuntimeState';

/**
 * 
 * @export
 * @interface FunctionRuntimeStatus
 */
export interface FunctionRuntimeStatus {
    /**
     * 
     * @type {string}
     * @memberof FunctionRuntimeStatus
     */
    functionId: string;
    /**
     * 
     * @type {string}
     * @memberof FunctionRuntimeStatus
     */
    revisionId: string;
    /**
     * 
     * @type {number}
     * @memberof FunctionRuntimeStatus
     */
    revisionNumber: number;
    /**
     * 
     * @type {FunctionRuntimeState}
     * @memberof FunctionRuntimeStatus
     */
    state: FunctionRuntimeState;
    /**
     * Current restored runtime sandbox, if one exists.
     * @type {string}
     * @memberof FunctionRuntimeStatus
     */
    runtimeSandboxId?: string;
    /**
     * Current runtime process context, if one exists.
     * @type {string}
     * @memberof FunctionRuntimeStatus
     */
    runtimeContextId?: string;
    /**
     * Last time the runtime mapping was updated.
     * @type {Date}
     * @memberof FunctionRuntimeStatus
     */
    runtimeUpdatedAt?: Date;
}



/**
 * Check if a given object implements the FunctionRuntimeStatus interface.
 */
export function instanceOfFunctionRuntimeStatus(value: object): value is FunctionRuntimeStatus {
    if (!('functionId' in value) || value['functionId'] === undefined) return false;
    if (!('revisionId' in value) || value['revisionId'] === undefined) return false;
    if (!('revisionNumber' in value) || value['revisionNumber'] === undefined) return false;
    if (!('state' in value) || value['state'] === undefined) return false;
    return true;
}

export function FunctionRuntimeStatusFromJSON(json: any): FunctionRuntimeStatus {
    return FunctionRuntimeStatusFromJSONTyped(json, false);
}

export function FunctionRuntimeStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): FunctionRuntimeStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'functionId': json['function_id'],
        'revisionId': json['revision_id'],
        'revisionNumber': json['revision_number'],
        'state': FunctionRuntimeStateFromJSON(json['state']),
        'runtimeSandboxId': json['runtime_sandbox_id'] == null ? undefined : json['runtime_sandbox_id'],
        'runtimeContextId': json['runtime_context_id'] == null ? undefined : json['runtime_context_id'],
        'runtimeUpdatedAt': json['runtime_updated_at'] == null ? undefined : (new Date(json['runtime_updated_at'])),
    };
}

export function FunctionRuntimeStatusToJSON(json: any): FunctionRuntimeStatus {
    return FunctionRuntimeStatusToJSONTyped(json, false);
}

export function FunctionRuntimeStatusToJSONTyped(value?: FunctionRuntimeStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'function_id': value['functionId'],
        'revision_id': value['revisionId'],
        'revision_number': value['revisionNumber'],
        'state': FunctionRuntimeStateToJSON(value['state']),
        'runtime_sandbox_id': value['runtimeSandboxId'],
        'runtime_context_id': value['runtimeContextId'],
        'runtime_updated_at': value['runtimeUpdatedAt'] == null ? value['runtimeUpdatedAt'] : value['runtimeUpdatedAt'].toISOString(),
    };
}

