/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FunctionRevisionSpec } from './FunctionRevisionSpec';
import {
    FunctionRevisionSpecFromJSON,
    FunctionRevisionSpecFromJSONTyped,
    FunctionRevisionSpecToJSON,
    FunctionRevisionSpecToJSONTyped,
} from './FunctionRevisionSpec';
import type { FunctionRevisionStatus } from './FunctionRevisionStatus';
import {
    FunctionRevisionStatusFromJSON,
    FunctionRevisionStatusFromJSONTyped,
    FunctionRevisionStatusToJSON,
    FunctionRevisionStatusToJSONTyped,
} from './FunctionRevisionStatus';
import type { FunctionSource } from './FunctionSource';
import {
    FunctionSourceFromJSON,
    FunctionSourceFromJSONTyped,
    FunctionSourceToJSON,
    FunctionSourceToJSONTyped,
} from './FunctionSource';

/**
 * 
 * @export
 * @interface FunctionRevision
 */
export interface FunctionRevision {
    /**
     * 
     * @type {string}
     * @memberof FunctionRevision
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof FunctionRevision
     */
    functionId: string;
    /**
     * 
     * @type {string}
     * @memberof FunctionRevision
     */
    teamId: string;
    /**
     * 
     * @type {number}
     * @memberof FunctionRevision
     */
    number: number;
    /**
     * 
     * @type {FunctionSource}
     * @memberof FunctionRevision
     */
    source: FunctionSource;
    /**
     * 
     * @type {FunctionRevisionSpec}
     * @memberof FunctionRevision
     */
    spec: FunctionRevisionSpec;
    /**
     * 
     * @type {FunctionRevisionStatus}
     * @memberof FunctionRevision
     */
    status: FunctionRevisionStatus;
    /**
     * 
     * @type {string}
     * @memberof FunctionRevision
     */
    runtimeSandboxId?: string;
    /**
     * 
     * @type {string}
     * @memberof FunctionRevision
     */
    runtimeClusterId?: string;
    /**
     * 
     * @type {string}
     * @memberof FunctionRevision
     */
    runtimeContextId?: string;
    /**
     * 
     * @type {Date}
     * @memberof FunctionRevision
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof FunctionRevision
     */
    activatedAt?: Date;
}



/**
 * Check if a given object implements the FunctionRevision interface.
 */
export function instanceOfFunctionRevision(value: object): value is FunctionRevision {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('functionId' in value) || value['functionId'] === undefined) return false;
    if (!('teamId' in value) || value['teamId'] === undefined) return false;
    if (!('number' in value) || value['number'] === undefined) return false;
    if (!('source' in value) || value['source'] === undefined) return false;
    if (!('spec' in value) || value['spec'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function FunctionRevisionFromJSON(json: any): FunctionRevision {
    return FunctionRevisionFromJSONTyped(json, false);
}

export function FunctionRevisionFromJSONTyped(json: any, ignoreDiscriminator: boolean): FunctionRevision {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'functionId': json['function_id'],
        'teamId': json['team_id'],
        'number': json['number'],
        'source': FunctionSourceFromJSON(json['source']),
        'spec': FunctionRevisionSpecFromJSON(json['spec']),
        'status': FunctionRevisionStatusFromJSON(json['status']),
        'runtimeSandboxId': json['runtime_sandbox_id'] == null ? undefined : json['runtime_sandbox_id'],
        'runtimeClusterId': json['runtime_cluster_id'] == null ? undefined : json['runtime_cluster_id'],
        'runtimeContextId': json['runtime_context_id'] == null ? undefined : json['runtime_context_id'],
        'createdAt': (new Date(json['created_at'])),
        'activatedAt': json['activated_at'] == null ? undefined : (new Date(json['activated_at'])),
    };
}

export function FunctionRevisionToJSON(json: any): FunctionRevision {
    return FunctionRevisionToJSONTyped(json, false);
}

export function FunctionRevisionToJSONTyped(value?: FunctionRevision | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'function_id': value['functionId'],
        'team_id': value['teamId'],
        'number': value['number'],
        'source': FunctionSourceToJSON(value['source']),
        'spec': FunctionRevisionSpecToJSON(value['spec']),
        'status': FunctionRevisionStatusToJSON(value['status']),
        'runtime_sandbox_id': value['runtimeSandboxId'],
        'runtime_cluster_id': value['runtimeClusterId'],
        'runtime_context_id': value['runtimeContextId'],
        'created_at': value['createdAt'].toISOString(),
        'activated_at': value['activatedAt'] == null ? value['activatedAt'] : value['activatedAt'].toISOString(),
    };
}

