/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FunctionRevisionSpec } from './FunctionRevisionSpec';
import {
    FunctionRevisionSpecFromJSON,
    FunctionRevisionSpecFromJSONTyped,
    FunctionRevisionSpecToJSON,
    FunctionRevisionSpecToJSONTyped,
} from './FunctionRevisionSpec';
import type { FunctionSandboxServiceSource } from './FunctionSandboxServiceSource';
import {
    FunctionSandboxServiceSourceFromJSON,
    FunctionSandboxServiceSourceFromJSONTyped,
    FunctionSandboxServiceSourceToJSON,
    FunctionSandboxServiceSourceToJSONTyped,
} from './FunctionSandboxServiceSource';
import type { FunctionRevisionInputSourceType } from './FunctionRevisionInputSourceType';
import {
    FunctionRevisionInputSourceTypeFromJSON,
    FunctionRevisionInputSourceTypeFromJSONTyped,
    FunctionRevisionInputSourceTypeToJSON,
    FunctionRevisionInputSourceTypeToJSONTyped,
} from './FunctionRevisionInputSourceType';

/**
 * Source used to create a function revision. Omitting type with sandbox_id and service_id keeps the sandbox-service shortcut shape; internally it is compiled into an immutable FunctionRevisionSpec.
 *
 * @export
 * @interface FunctionSourceRequest
 */
export interface FunctionSourceRequest {
    /**
     *
     * @type {FunctionRevisionInputSourceType}
     * @memberof FunctionSourceRequest
     */
    type?: FunctionRevisionInputSourceType;
    /**
     * Compatibility shortcut for type=sandbox_service.
     * @type {string}
     * @memberof FunctionSourceRequest
     */
    sandboxId?: string;
    /**
     * Compatibility shortcut for type=sandbox_service.
     * @type {string}
     * @memberof FunctionSourceRequest
     */
    serviceId?: string;
    /**
     *
     * @type {FunctionSandboxServiceSource}
     * @memberof FunctionSourceRequest
     */
    sandboxService?: FunctionSandboxServiceSource;
    /**
     *
     * @type {FunctionRevisionSpec}
     * @memberof FunctionSourceRequest
     */
    revisionSpec?: FunctionRevisionSpec;
    /**
     * Optional non-execution metadata describing how the revision spec was produced.
     * @type {{ [key: string]: any; }}
     * @memberof FunctionSourceRequest
     */
    provenance?: { [key: string]: any; };
}



/**
 * Check if a given object implements the FunctionSourceRequest interface.
 */
export function instanceOfFunctionSourceRequest(value: object): value is FunctionSourceRequest {
    return true;
}

export function FunctionSourceRequestFromJSON(json: any): FunctionSourceRequest {
    return FunctionSourceRequestFromJSONTyped(json, false);
}

export function FunctionSourceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): FunctionSourceRequest {
    if (json == null) {
        return json;
    }
    return {

        'type': json['type'] == null ? undefined : FunctionRevisionInputSourceTypeFromJSON(json['type']),
        'sandboxId': json['sandbox_id'] == null ? undefined : json['sandbox_id'],
        'serviceId': json['service_id'] == null ? undefined : json['service_id'],
        'sandboxService': json['sandbox_service'] == null ? undefined : FunctionSandboxServiceSourceFromJSON(json['sandbox_service']),
        'revisionSpec': json['revision_spec'] == null ? undefined : FunctionRevisionSpecFromJSON(json['revision_spec']),
        'provenance': json['provenance'] == null ? undefined : json['provenance'],
    };
}

export function FunctionSourceRequestToJSON(json: any): FunctionSourceRequest {
    return FunctionSourceRequestToJSONTyped(json, false);
}

export function FunctionSourceRequestToJSONTyped(value?: FunctionSourceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'type': FunctionRevisionInputSourceTypeToJSON(value['type']),
        'sandbox_id': value['sandboxId'],
        'service_id': value['serviceId'],
        'sandbox_service': FunctionSandboxServiceSourceToJSON(value['sandboxService']),
        'revision_spec': FunctionRevisionSpecToJSON(value['revisionSpec']),
        'provenance': value['provenance'],
    };
}

