/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FunctionRuntimeEvent } from './FunctionRuntimeEvent';
import {
    FunctionRuntimeEventFromJSON,
    FunctionRuntimeEventFromJSONTyped,
    FunctionRuntimeEventToJSON,
    FunctionRuntimeEventToJSONTyped,
} from './FunctionRuntimeEvent';
import type { FunctionRuntimePhase } from './FunctionRuntimePhase';
import {
    FunctionRuntimePhaseFromJSON,
    FunctionRuntimePhaseFromJSONTyped,
    FunctionRuntimePhaseToJSON,
    FunctionRuntimePhaseToJSONTyped,
} from './FunctionRuntimePhase';
import type { FunctionRuntimeInstance } from './FunctionRuntimeInstance';
import {
    FunctionRuntimeInstanceFromJSON,
    FunctionRuntimeInstanceFromJSONTyped,
    FunctionRuntimeInstanceToJSON,
    FunctionRuntimeInstanceToJSONTyped,
} from './FunctionRuntimeInstance';
import type { FunctionRuntimeReadinessState } from './FunctionRuntimeReadinessState';
import {
    FunctionRuntimeReadinessStateFromJSON,
    FunctionRuntimeReadinessStateFromJSONTyped,
    FunctionRuntimeReadinessStateToJSON,
    FunctionRuntimeReadinessStateToJSONTyped,
} from './FunctionRuntimeReadinessState';
import type { FunctionAutoscaling } from './FunctionAutoscaling';
import {
    FunctionAutoscalingFromJSON,
    FunctionAutoscalingFromJSONTyped,
    FunctionAutoscalingToJSON,
    FunctionAutoscalingToJSONTyped,
} from './FunctionAutoscaling';
import type { FunctionRuntimeState } from './FunctionRuntimeState';
import {
    FunctionRuntimeStateFromJSON,
    FunctionRuntimeStateFromJSONTyped,
    FunctionRuntimeStateToJSON,
    FunctionRuntimeStateToJSONTyped,
} from './FunctionRuntimeState';

/**
 *
 * @export
 * @interface FunctionRuntimeStatus
 */
export interface FunctionRuntimeStatus {
    /**
     *
     * @type {string}
     * @memberof FunctionRuntimeStatus
     */
    functionId: string;
    /**
     *
     * @type {string}
     * @memberof FunctionRuntimeStatus
     */
    revisionId: string;
    /**
     *
     * @type {number}
     * @memberof FunctionRuntimeStatus
     */
    revisionNumber: number;
    /**
     *
     * @type {FunctionRuntimeState}
     * @memberof FunctionRuntimeStatus
     */
    state: FunctionRuntimeState;
    /**
     *
     * @type {FunctionRuntimePhase}
     * @memberof FunctionRuntimeStatus
     */
    phase: FunctionRuntimePhase;
    /**
     *
     * @type {FunctionAutoscaling}
     * @memberof FunctionRuntimeStatus
     */
    autoscaling: FunctionAutoscaling;
    /**
     *
     * @type {FunctionRuntimeReadinessState}
     * @memberof FunctionRuntimeStatus
     */
    readinessState: FunctionRuntimeReadinessState;
    /**
     * Compatibility summary for one current restored runtime sandbox, if one exists. Use instances for the full runtime pool.
     * @type {string}
     * @memberof FunctionRuntimeStatus
     */
    runtimeSandboxId?: string;
    /**
     * Compatibility summary for one current runtime process context, if one exists. Use instances for the full runtime pool.
     * @type {string}
     * @memberof FunctionRuntimeStatus
     */
    runtimeContextId?: string;
    /**
     * Last time the runtime mapping was updated.
     * @type {Date}
     * @memberof FunctionRuntimeStatus
     */
    runtimeUpdatedAt?: Date;
    /**
     *
     * @type {number}
     * @memberof FunctionRuntimeStatus
     */
    startupDurationMs?: number;
    /**
     *
     * @type {string}
     * @memberof FunctionRuntimeStatus
     */
    lastError?: string;
    /**
     *
     * @type {Date}
     * @memberof FunctionRuntimeStatus
     */
    lastErrorAt?: Date;
    /**
     *
     * @type {Array<FunctionRuntimeInstance>}
     * @memberof FunctionRuntimeStatus
     */
    instances?: Array<FunctionRuntimeInstance>;
    /**
     *
     * @type {Array<FunctionRuntimeEvent>}
     * @memberof FunctionRuntimeStatus
     */
    recentEvents?: Array<FunctionRuntimeEvent>;
}



/**
 * Check if a given object implements the FunctionRuntimeStatus interface.
 */
export function instanceOfFunctionRuntimeStatus(value: object): value is FunctionRuntimeStatus {
    if (!('functionId' in value) || value['functionId'] === undefined) return false;
    if (!('revisionId' in value) || value['revisionId'] === undefined) return false;
    if (!('revisionNumber' in value) || value['revisionNumber'] === undefined) return false;
    if (!('state' in value) || value['state'] === undefined) return false;
    if (!('phase' in value) || value['phase'] === undefined) return false;
    if (!('autoscaling' in value) || value['autoscaling'] === undefined) return false;
    if (!('readinessState' in value) || value['readinessState'] === undefined) return false;
    return true;
}

export function FunctionRuntimeStatusFromJSON(json: any): FunctionRuntimeStatus {
    return FunctionRuntimeStatusFromJSONTyped(json, false);
}

export function FunctionRuntimeStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): FunctionRuntimeStatus {
    if (json == null) {
        return json;
    }
    return {

        'functionId': json['function_id'],
        'revisionId': json['revision_id'],
        'revisionNumber': json['revision_number'],
        'state': FunctionRuntimeStateFromJSON(json['state']),
        'phase': FunctionRuntimePhaseFromJSON(json['phase']),
        'autoscaling': FunctionAutoscalingFromJSON(json['autoscaling']),
        'readinessState': FunctionRuntimeReadinessStateFromJSON(json['readiness_state']),
        'runtimeSandboxId': json['runtime_sandbox_id'] == null ? undefined : json['runtime_sandbox_id'],
        'runtimeContextId': json['runtime_context_id'] == null ? undefined : json['runtime_context_id'],
        'runtimeUpdatedAt': json['runtime_updated_at'] == null ? undefined : (new Date(json['runtime_updated_at'])),
        'startupDurationMs': json['startup_duration_ms'] == null ? undefined : json['startup_duration_ms'],
        'lastError': json['last_error'] == null ? undefined : json['last_error'],
        'lastErrorAt': json['last_error_at'] == null ? undefined : (new Date(json['last_error_at'])),
        'instances': json['instances'] == null ? undefined : ((json['instances'] as Array<any>).map(FunctionRuntimeInstanceFromJSON)),
        'recentEvents': json['recent_events'] == null ? undefined : ((json['recent_events'] as Array<any>).map(FunctionRuntimeEventFromJSON)),
    };
}

export function FunctionRuntimeStatusToJSON(json: any): FunctionRuntimeStatus {
    return FunctionRuntimeStatusToJSONTyped(json, false);
}

export function FunctionRuntimeStatusToJSONTyped(value?: FunctionRuntimeStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'function_id': value['functionId'],
        'revision_id': value['revisionId'],
        'revision_number': value['revisionNumber'],
        'state': FunctionRuntimeStateToJSON(value['state']),
        'phase': FunctionRuntimePhaseToJSON(value['phase']),
        'autoscaling': FunctionAutoscalingToJSON(value['autoscaling']),
        'readiness_state': FunctionRuntimeReadinessStateToJSON(value['readinessState']),
        'runtime_sandbox_id': value['runtimeSandboxId'],
        'runtime_context_id': value['runtimeContextId'],
        'runtime_updated_at': value['runtimeUpdatedAt'] == null ? value['runtimeUpdatedAt'] : value['runtimeUpdatedAt'].toISOString(),
        'startup_duration_ms': value['startupDurationMs'],
        'last_error': value['lastError'],
        'last_error_at': value['lastErrorAt'] == null ? value['lastErrorAt'] : value['lastErrorAt'].toISOString(),
        'instances': value['instances'] == null ? undefined : ((value['instances'] as Array<any>).map(FunctionRuntimeInstanceToJSON)),
        'recent_events': value['recentEvents'] == null ? undefined : ((value['recentEvents'] as Array<any>).map(FunctionRuntimeEventToJSON)),
    };
}

