/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FunctionStaticAsset
 */
export interface FunctionStaticAsset {
    /**
     * 
     * @type {string}
     * @memberof FunctionStaticAsset
     */
    artifactId: string;
    /**
     * 
     * @type {string}
     * @memberof FunctionStaticAsset
     */
    routePrefix: string;
    /**
     * 
     * @type {string}
     * @memberof FunctionStaticAsset
     */
    digest?: string;
}

/**
 * Check if a given object implements the FunctionStaticAsset interface.
 */
export function instanceOfFunctionStaticAsset(value: object): value is FunctionStaticAsset {
    if (!('artifactId' in value) || value['artifactId'] === undefined) return false;
    if (!('routePrefix' in value) || value['routePrefix'] === undefined) return false;
    return true;
}

export function FunctionStaticAssetFromJSON(json: any): FunctionStaticAsset {
    return FunctionStaticAssetFromJSONTyped(json, false);
}

export function FunctionStaticAssetFromJSONTyped(json: any, ignoreDiscriminator: boolean): FunctionStaticAsset {
    if (json == null) {
        return json;
    }
    return {
        
        'artifactId': json['artifact_id'],
        'routePrefix': json['route_prefix'],
        'digest': json['digest'] == null ? undefined : json['digest'],
    };
}

export function FunctionStaticAssetToJSON(json: any): FunctionStaticAsset {
    return FunctionStaticAssetToJSONTyped(json, false);
}

export function FunctionStaticAssetToJSONTyped(value?: FunctionStaticAsset | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'artifact_id': value['artifactId'],
        'route_prefix': value['routePrefix'],
        'digest': value['digest'],
    };
}

