/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FunctionSourceRequest } from './FunctionSourceRequest';
import {
    FunctionSourceRequestFromJSON,
    FunctionSourceRequestFromJSONTyped,
    FunctionSourceRequestToJSON,
    FunctionSourceRequestToJSONTyped,
} from './FunctionSourceRequest';

/**
 * 
 * @export
 * @interface FunctionCreateRequest
 */
export interface FunctionCreateRequest {
    /**
     * Function display name. Defaults to the source service name or ID when omitted.
     * @type {string}
     * @memberof FunctionCreateRequest
     */
    name?: string;
    /**
     * 
     * @type {FunctionSourceRequest}
     * @memberof FunctionCreateRequest
     */
    source: FunctionSourceRequest;
}

/**
 * Check if a given object implements the FunctionCreateRequest interface.
 */
export function instanceOfFunctionCreateRequest(value: object): value is FunctionCreateRequest {
    if (!('source' in value) || value['source'] === undefined) return false;
    return true;
}

export function FunctionCreateRequestFromJSON(json: any): FunctionCreateRequest {
    return FunctionCreateRequestFromJSONTyped(json, false);
}

export function FunctionCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): FunctionCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'source': FunctionSourceRequestFromJSON(json['source']),
    };
}

export function FunctionCreateRequestToJSON(json: any): FunctionCreateRequest {
    return FunctionCreateRequestToJSONTyped(json, false);
}

export function FunctionCreateRequestToJSONTyped(value?: FunctionCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'source': FunctionSourceRequestToJSON(value['source']),
    };
}

