/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FunctionAutoscaling } from './FunctionAutoscaling';
import {
    FunctionAutoscalingFromJSON,
    FunctionAutoscalingFromJSONTyped,
    FunctionAutoscalingToJSON,
    FunctionAutoscalingToJSONTyped,
} from './FunctionAutoscaling';

/**
 * 
 * @export
 * @interface FunctionUpdateRequest
 */
export interface FunctionUpdateRequest {
    /**
     * Mutable function display name. Slug and domain label stay stable.
     * @type {string}
     * @memberof FunctionUpdateRequest
     */
    name?: string;
    /**
     * Whether the function host should serve traffic. Disabled functions do not restore runtime sandboxes.
     * @type {boolean}
     * @memberof FunctionUpdateRequest
     */
    enabled?: boolean;
    /**
     * 
     * @type {FunctionAutoscaling}
     * @memberof FunctionUpdateRequest
     */
    autoscaling?: FunctionAutoscaling;
}

/**
 * Check if a given object implements the FunctionUpdateRequest interface.
 */
export function instanceOfFunctionUpdateRequest(value: object): value is FunctionUpdateRequest {
    return true;
}

export function FunctionUpdateRequestFromJSON(json: any): FunctionUpdateRequest {
    return FunctionUpdateRequestFromJSONTyped(json, false);
}

export function FunctionUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): FunctionUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'autoscaling': json['autoscaling'] == null ? undefined : FunctionAutoscalingFromJSON(json['autoscaling']),
    };
}

export function FunctionUpdateRequestToJSON(json: any): FunctionUpdateRequest {
    return FunctionUpdateRequestToJSONTyped(json, false);
}

export function FunctionUpdateRequestToJSONTyped(value?: FunctionUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'enabled': value['enabled'],
        'autoscaling': FunctionAutoscalingToJSON(value['autoscaling']),
    };
}

