/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SandboxAppService } from './SandboxAppService';
import {
    SandboxAppServiceFromJSON,
    SandboxAppServiceFromJSONTyped,
    SandboxAppServiceToJSON,
    SandboxAppServiceToJSONTyped,
} from './SandboxAppService';
import type { FunctionRestoreMount } from './FunctionRestoreMount';
import {
    FunctionRestoreMountFromJSON,
    FunctionRestoreMountFromJSONTyped,
    FunctionRestoreMountToJSON,
    FunctionRestoreMountToJSONTyped,
} from './FunctionRestoreMount';

/**
 * 
 * @export
 * @interface FunctionRevision
 */
export interface FunctionRevision {
    /**
     * 
     * @type {string}
     * @memberof FunctionRevision
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof FunctionRevision
     */
    functionId: string;
    /**
     * 
     * @type {string}
     * @memberof FunctionRevision
     */
    teamId: string;
    /**
     * 
     * @type {number}
     * @memberof FunctionRevision
     */
    revisionNumber: number;
    /**
     * 
     * @type {string}
     * @memberof FunctionRevision
     */
    sourceSandboxId: string;
    /**
     * 
     * @type {string}
     * @memberof FunctionRevision
     */
    sourceServiceId: string;
    /**
     * 
     * @type {string}
     * @memberof FunctionRevision
     */
    sourceTemplateId: string;
    /**
     * SandboxVolume mounts captured from the source sandbox and reused when the function runtime sandbox is restored.
     * @type {Array<FunctionRestoreMount>}
     * @memberof FunctionRevision
     */
    restoreMounts?: Array<FunctionRestoreMount>;
    /**
     * 
     * @type {SandboxAppService}
     * @memberof FunctionRevision
     */
    serviceSnapshot: SandboxAppService;
    /**
     * Current restored runtime sandbox, when the source sandbox no longer exists.
     * @type {string}
     * @memberof FunctionRevision
     */
    runtimeSandboxId?: string;
    /**
     * Current runtime process context inside the restored runtime sandbox.
     * @type {string}
     * @memberof FunctionRevision
     */
    runtimeContextId?: string;
    /**
     * Last time the restored runtime sandbox mapping was updated.
     * @type {Date}
     * @memberof FunctionRevision
     */
    runtimeUpdatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof FunctionRevision
     */
    createdBy?: string;
    /**
     * 
     * @type {Date}
     * @memberof FunctionRevision
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the FunctionRevision interface.
 */
export function instanceOfFunctionRevision(value: object): value is FunctionRevision {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('functionId' in value) || value['functionId'] === undefined) return false;
    if (!('teamId' in value) || value['teamId'] === undefined) return false;
    if (!('revisionNumber' in value) || value['revisionNumber'] === undefined) return false;
    if (!('sourceSandboxId' in value) || value['sourceSandboxId'] === undefined) return false;
    if (!('sourceServiceId' in value) || value['sourceServiceId'] === undefined) return false;
    if (!('sourceTemplateId' in value) || value['sourceTemplateId'] === undefined) return false;
    if (!('serviceSnapshot' in value) || value['serviceSnapshot'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function FunctionRevisionFromJSON(json: any): FunctionRevision {
    return FunctionRevisionFromJSONTyped(json, false);
}

export function FunctionRevisionFromJSONTyped(json: any, ignoreDiscriminator: boolean): FunctionRevision {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'functionId': json['function_id'],
        'teamId': json['team_id'],
        'revisionNumber': json['revision_number'],
        'sourceSandboxId': json['source_sandbox_id'],
        'sourceServiceId': json['source_service_id'],
        'sourceTemplateId': json['source_template_id'],
        'restoreMounts': json['restore_mounts'] == null ? undefined : ((json['restore_mounts'] as Array<any>).map(FunctionRestoreMountFromJSON)),
        'serviceSnapshot': SandboxAppServiceFromJSON(json['service_snapshot']),
        'runtimeSandboxId': json['runtime_sandbox_id'] == null ? undefined : json['runtime_sandbox_id'],
        'runtimeContextId': json['runtime_context_id'] == null ? undefined : json['runtime_context_id'],
        'runtimeUpdatedAt': json['runtime_updated_at'] == null ? undefined : (new Date(json['runtime_updated_at'])),
        'createdBy': json['created_by'] == null ? undefined : json['created_by'],
        'createdAt': (new Date(json['created_at'])),
    };
}

export function FunctionRevisionToJSON(json: any): FunctionRevision {
    return FunctionRevisionToJSONTyped(json, false);
}

export function FunctionRevisionToJSONTyped(value?: FunctionRevision | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'function_id': value['functionId'],
        'team_id': value['teamId'],
        'revision_number': value['revisionNumber'],
        'source_sandbox_id': value['sourceSandboxId'],
        'source_service_id': value['sourceServiceId'],
        'source_template_id': value['sourceTemplateId'],
        'restore_mounts': value['restoreMounts'] == null ? undefined : ((value['restoreMounts'] as Array<any>).map(FunctionRestoreMountToJSON)),
        'service_snapshot': SandboxAppServiceToJSON(value['serviceSnapshot']),
        'runtime_sandbox_id': value['runtimeSandboxId'],
        'runtime_context_id': value['runtimeContextId'],
        'runtime_updated_at': value['runtimeUpdatedAt'] == null ? value['runtimeUpdatedAt'] : value['runtimeUpdatedAt'].toISOString(),
        'created_by': value['createdBy'],
        'created_at': value['createdAt'].toISOString(),
    };
}

