/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GatewayMetadata
 */
export interface GatewayMetadata {
    /**
     * 
     * @type {string}
     * @memberof GatewayMetadata
     */
    gatewayMode: GatewayMetadataGatewayModeEnum;
    /**
     * 
     * @type {string}
     * @memberof GatewayMetadata
     */
    service: string;
}


/**
 * @export
 */
export const GatewayMetadataGatewayModeEnum = {
    Direct: 'direct',
    Global: 'global'
} as const;
export type GatewayMetadataGatewayModeEnum = typeof GatewayMetadataGatewayModeEnum[keyof typeof GatewayMetadataGatewayModeEnum];


/**
 * Check if a given object implements the GatewayMetadata interface.
 */
export function instanceOfGatewayMetadata(value: object): value is GatewayMetadata {
    if (!('gatewayMode' in value) || value['gatewayMode'] === undefined) return false;
    if (!('service' in value) || value['service'] === undefined) return false;
    return true;
}

export function GatewayMetadataFromJSON(json: any): GatewayMetadata {
    return GatewayMetadataFromJSONTyped(json, false);
}

export function GatewayMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GatewayMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'gatewayMode': json['gateway_mode'],
        'service': json['service'],
    };
}

export function GatewayMetadataToJSON(json: any): GatewayMetadata {
    return GatewayMetadataToJSONTyped(json, false);
}

export function GatewayMetadataToJSONTyped(value?: GatewayMetadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'gateway_mode': value['gatewayMode'],
        'service': value['service'],
    };
}

