/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HTTPMethodPolicy } from './HTTPMethodPolicy';
import {
    HTTPMethodPolicyFromJSON,
    HTTPMethodPolicyFromJSONTyped,
    HTTPMethodPolicyToJSON,
    HTTPMethodPolicyToJSONTyped,
} from './HTTPMethodPolicy';
import type { HTTPPathPolicy } from './HTTPPathPolicy';
import {
    HTTPPathPolicyFromJSON,
    HTTPPathPolicyFromJSONTyped,
    HTTPPathPolicyToJSON,
    HTTPPathPolicyToJSONTyped,
} from './HTTPPathPolicy';

/**
 * HTTP request operation policy.
 * @export
 * @interface HTTPProtocolRule
 */
export interface HTTPProtocolRule {
    /**
     * 
     * @type {HTTPMethodPolicy}
     * @memberof HTTPProtocolRule
     */
    methods?: HTTPMethodPolicy;
    /**
     * 
     * @type {HTTPPathPolicy}
     * @memberof HTTPProtocolRule
     */
    paths?: HTTPPathPolicy;
}

/**
 * Check if a given object implements the HTTPProtocolRule interface.
 */
export function instanceOfHTTPProtocolRule(value: object): value is HTTPProtocolRule {
    return true;
}

export function HTTPProtocolRuleFromJSON(json: any): HTTPProtocolRule {
    return HTTPProtocolRuleFromJSONTyped(json, false);
}

export function HTTPProtocolRuleFromJSONTyped(json: any, ignoreDiscriminator: boolean): HTTPProtocolRule {
    if (json == null) {
        return json;
    }
    return {
        
        'methods': json['methods'] == null ? undefined : HTTPMethodPolicyFromJSON(json['methods']),
        'paths': json['paths'] == null ? undefined : HTTPPathPolicyFromJSON(json['paths']),
    };
}

export function HTTPProtocolRuleToJSON(json: any): HTTPProtocolRule {
    return HTTPProtocolRuleToJSONTyped(json, false);
}

export function HTTPProtocolRuleToJSONTyped(value?: HTTPProtocolRule | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'methods': HTTPMethodPolicyToJSON(value['methods']),
        'paths': HTTPPathPolicyToJSON(value['paths']),
    };
}

