/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HTTPValueMatch } from './HTTPValueMatch';
import {
    HTTPValueMatchFromJSON,
    HTTPValueMatchFromJSONTyped,
    HTTPValueMatchToJSON,
    HTTPValueMatchToJSONTyped,
} from './HTTPValueMatch';

/**
 * Request-level matcher for HTTP-family egress credential rules.
 * @export
 * @interface HTTPMatch
 */
export interface HTTPMatch {
    /**
     * HTTP methods matched case-insensitively after uppercasing.
     * @type {Array<string>}
     * @memberof HTTPMatch
     */
    methods?: Array<string>;
    /**
     * Exact URL path matches.
     * @type {Array<string>}
     * @memberof HTTPMatch
     */
    paths?: Array<string>;
    /**
     * URL path prefix matches.
     * @type {Array<string>}
     * @memberof HTTPMatch
     */
    pathPrefixes?: Array<string>;
    /**
     * Decoded query parameter matchers.
     * @type {Array<HTTPValueMatch>}
     * @memberof HTTPMatch
     */
    query?: Array<HTTPValueMatch>;
    /**
     * HTTP request header matchers.
     * @type {Array<HTTPValueMatch>}
     * @memberof HTTPMatch
     */
    headers?: Array<HTTPValueMatch>;
}

/**
 * Check if a given object implements the HTTPMatch interface.
 */
export function instanceOfHTTPMatch(value: object): value is HTTPMatch {
    return true;
}

export function HTTPMatchFromJSON(json: any): HTTPMatch {
    return HTTPMatchFromJSONTyped(json, false);
}

export function HTTPMatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): HTTPMatch {
    if (json == null) {
        return json;
    }
    return {
        
        'methods': json['methods'] == null ? undefined : json['methods'],
        'paths': json['paths'] == null ? undefined : json['paths'],
        'pathPrefixes': json['pathPrefixes'] == null ? undefined : json['pathPrefixes'],
        'query': json['query'] == null ? undefined : ((json['query'] as Array<any>).map(HTTPValueMatchFromJSON)),
        'headers': json['headers'] == null ? undefined : ((json['headers'] as Array<any>).map(HTTPValueMatchFromJSON)),
    };
}

export function HTTPMatchToJSON(json: any): HTTPMatch {
    return HTTPMatchToJSONTyped(json, false);
}

export function HTTPMatchToJSONTyped(value?: HTTPMatch | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'methods': value['methods'],
        'paths': value['paths'],
        'pathPrefixes': value['pathPrefixes'],
        'query': value['query'] == null ? undefined : ((value['query'] as Array<any>).map(HTTPValueMatchToJSON)),
        'headers': value['headers'] == null ? undefined : ((value['headers'] as Array<any>).map(HTTPValueMatchToJSON)),
    };
}

