/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MCPToolPolicy } from './MCPToolPolicy';
import {
    MCPToolPolicyFromJSON,
    MCPToolPolicyFromJSONTyped,
    MCPToolPolicyToJSON,
    MCPToolPolicyToJSONTyped,
} from './MCPToolPolicy';

/**
 * Model Context Protocol operation policy.
 * @export
 * @interface MCPProtocolRule
 */
export interface MCPProtocolRule {
    /**
     * 
     * @type {MCPToolPolicy}
     * @memberof MCPProtocolRule
     */
    tools?: MCPToolPolicy;
}

/**
 * Check if a given object implements the MCPProtocolRule interface.
 */
export function instanceOfMCPProtocolRule(value: object): value is MCPProtocolRule {
    return true;
}

export function MCPProtocolRuleFromJSON(json: any): MCPProtocolRule {
    return MCPProtocolRuleFromJSONTyped(json, false);
}

export function MCPProtocolRuleFromJSONTyped(json: any, ignoreDiscriminator: boolean): MCPProtocolRule {
    if (json == null) {
        return json;
    }
    return {
        
        'tools': json['tools'] == null ? undefined : MCPToolPolicyFromJSON(json['tools']),
    };
}

export function MCPProtocolRuleToJSON(json: any): MCPProtocolRule {
    return MCPProtocolRuleToJSONTyped(json, false);
}

export function MCPProtocolRuleToJSONTyped(value?: MCPProtocolRule | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tools': MCPToolPolicyToJSON(value['tools']),
    };
}

