/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by internal-gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VolumeConfig } from './VolumeConfig';
import {
    VolumeConfigFromJSON,
    VolumeConfigFromJSONTyped,
    VolumeConfigToJSON,
    VolumeConfigToJSONTyped,
} from './VolumeConfig';

/**
 * 
 * @export
 * @interface MountRequest
 */
export interface MountRequest {
    /**
     * 
     * @type {string}
     * @memberof MountRequest
     */
    sandboxvolumeId: string;
    /**
     * 
     * @type {string}
     * @memberof MountRequest
     */
    sandboxId?: string;
    /**
     * 
     * @type {string}
     * @memberof MountRequest
     */
    mountPoint: string;
    /**
     * 
     * @type {VolumeConfig}
     * @memberof MountRequest
     */
    volumeConfig?: VolumeConfig;
}

/**
 * Check if a given object implements the MountRequest interface.
 */
export function instanceOfMountRequest(value: object): value is MountRequest {
    if (!('sandboxvolumeId' in value) || value['sandboxvolumeId'] === undefined) return false;
    if (!('mountPoint' in value) || value['mountPoint'] === undefined) return false;
    return true;
}

export function MountRequestFromJSON(json: any): MountRequest {
    return MountRequestFromJSONTyped(json, false);
}

export function MountRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MountRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'sandboxvolumeId': json['sandboxvolume_id'],
        'sandboxId': json['sandbox_id'] == null ? undefined : json['sandbox_id'],
        'mountPoint': json['mount_point'],
        'volumeConfig': json['volume_config'] == null ? undefined : VolumeConfigFromJSON(json['volume_config']),
    };
}

export function MountRequestToJSON(json: any): MountRequest {
    return MountRequestToJSONTyped(json, false);
}

export function MountRequestToJSONTyped(value?: MountRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sandboxvolume_id': value['sandboxvolumeId'],
        'sandbox_id': value['sandboxId'],
        'mount_point': value['mountPoint'],
        'volume_config': VolumeConfigToJSON(value['volumeConfig']),
    };
}

