/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by internal-gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NodeSelector } from './NodeSelector';
import {
    NodeSelectorFromJSON,
    NodeSelectorFromJSONTyped,
    NodeSelectorToJSON,
    NodeSelectorToJSONTyped,
} from './NodeSelector';
import type { PreferredSchedulingTerm } from './PreferredSchedulingTerm';
import {
    PreferredSchedulingTermFromJSON,
    PreferredSchedulingTermFromJSONTyped,
    PreferredSchedulingTermToJSON,
    PreferredSchedulingTermToJSONTyped,
} from './PreferredSchedulingTerm';

/**
 * 
 * @export
 * @interface NodeAffinity
 */
export interface NodeAffinity {
    /**
     * 
     * @type {NodeSelector}
     * @memberof NodeAffinity
     */
    requiredDuringSchedulingIgnoredDuringExecution?: NodeSelector;
    /**
     * 
     * @type {Array<PreferredSchedulingTerm>}
     * @memberof NodeAffinity
     */
    preferredDuringSchedulingIgnoredDuringExecution?: Array<PreferredSchedulingTerm>;
}

/**
 * Check if a given object implements the NodeAffinity interface.
 */
export function instanceOfNodeAffinity(value: object): value is NodeAffinity {
    return true;
}

export function NodeAffinityFromJSON(json: any): NodeAffinity {
    return NodeAffinityFromJSONTyped(json, false);
}

export function NodeAffinityFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodeAffinity {
    if (json == null) {
        return json;
    }
    return {
        
        'requiredDuringSchedulingIgnoredDuringExecution': json['requiredDuringSchedulingIgnoredDuringExecution'] == null ? undefined : NodeSelectorFromJSON(json['requiredDuringSchedulingIgnoredDuringExecution']),
        'preferredDuringSchedulingIgnoredDuringExecution': json['preferredDuringSchedulingIgnoredDuringExecution'] == null ? undefined : ((json['preferredDuringSchedulingIgnoredDuringExecution'] as Array<any>).map(PreferredSchedulingTermFromJSON)),
    };
}

export function NodeAffinityToJSON(json: any): NodeAffinity {
    return NodeAffinityToJSONTyped(json, false);
}

export function NodeAffinityToJSONTyped(value?: NodeAffinity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'requiredDuringSchedulingIgnoredDuringExecution': NodeSelectorToJSON(value['requiredDuringSchedulingIgnoredDuringExecution']),
        'preferredDuringSchedulingIgnoredDuringExecution': value['preferredDuringSchedulingIgnoredDuringExecution'] == null ? undefined : ((value['preferredDuringSchedulingIgnoredDuringExecution'] as Array<any>).map(PreferredSchedulingTermToJSON)),
    };
}

