/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SandboxLifecycleStatus } from './SandboxLifecycleStatus';
import {
    SandboxLifecycleStatusFromJSON,
    SandboxLifecycleStatusFromJSONTyped,
    SandboxLifecycleStatusToJSON,
    SandboxLifecycleStatusToJSONTyped,
} from './SandboxLifecycleStatus';
import type { SandboxResourceUsage } from './SandboxResourceUsage';
import {
    SandboxResourceUsageFromJSON,
    SandboxResourceUsageFromJSONTyped,
    SandboxResourceUsageToJSON,
    SandboxResourceUsageToJSONTyped,
} from './SandboxResourceUsage';

/**
 * 
 * @export
 * @interface PauseSandboxResponse
 */
export interface PauseSandboxResponse {
    /**
     * 
     * @type {string}
     * @memberof PauseSandboxResponse
     */
    sandboxId: string;
    /**
     * True when checkpoint persistence has finished, runtime deletion has been accepted, and the sandbox is paused.
     * @type {boolean}
     * @memberof PauseSandboxResponse
     */
    paused: boolean;
    /**
     * 
     * @type {SandboxLifecycleStatus}
     * @memberof PauseSandboxResponse
     */
    status?: SandboxLifecycleStatus;
    /**
     * 
     * @type {SandboxResourceUsage}
     * @memberof PauseSandboxResponse
     */
    resourceUsage?: SandboxResourceUsage;
    /**
     * 
     * @type {string}
     * @memberof PauseSandboxResponse
     */
    updatedMemory?: string;
    /**
     * 
     * @type {string}
     * @memberof PauseSandboxResponse
     */
    updatedCpu?: string;
}



/**
 * Check if a given object implements the PauseSandboxResponse interface.
 */
export function instanceOfPauseSandboxResponse(value: object): value is PauseSandboxResponse {
    if (!('sandboxId' in value) || value['sandboxId'] === undefined) return false;
    if (!('paused' in value) || value['paused'] === undefined) return false;
    return true;
}

export function PauseSandboxResponseFromJSON(json: any): PauseSandboxResponse {
    return PauseSandboxResponseFromJSONTyped(json, false);
}

export function PauseSandboxResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PauseSandboxResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'sandboxId': json['sandbox_id'],
        'paused': json['paused'],
        'status': json['status'] == null ? undefined : SandboxLifecycleStatusFromJSON(json['status']),
        'resourceUsage': json['resource_usage'] == null ? undefined : SandboxResourceUsageFromJSON(json['resource_usage']),
        'updatedMemory': json['updated_memory'] == null ? undefined : json['updated_memory'],
        'updatedCpu': json['updated_cpu'] == null ? undefined : json['updated_cpu'],
    };
}

export function PauseSandboxResponseToJSON(json: any): PauseSandboxResponse {
    return PauseSandboxResponseToJSONTyped(json, false);
}

export function PauseSandboxResponseToJSONTyped(value?: PauseSandboxResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sandbox_id': value['sandboxId'],
        'paused': value['paused'],
        'status': SandboxLifecycleStatusToJSON(value['status']),
        'resource_usage': SandboxResourceUsageToJSON(value['resourceUsage']),
        'updated_memory': value['updatedMemory'],
        'updated_cpu': value['updatedCpu'],
    };
}

