/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by internal-gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LabelSelector } from './LabelSelector';
import {
    LabelSelectorFromJSON,
    LabelSelectorFromJSONTyped,
    LabelSelectorToJSON,
    LabelSelectorToJSONTyped,
} from './LabelSelector';

/**
 * 
 * @export
 * @interface PodAffinityTerm
 */
export interface PodAffinityTerm {
    /**
     * 
     * @type {LabelSelector}
     * @memberof PodAffinityTerm
     */
    labelSelector?: LabelSelector;
    /**
     * 
     * @type {Array<string>}
     * @memberof PodAffinityTerm
     */
    namespaces?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof PodAffinityTerm
     */
    topologyKey: string;
}

/**
 * Check if a given object implements the PodAffinityTerm interface.
 */
export function instanceOfPodAffinityTerm(value: object): value is PodAffinityTerm {
    if (!('topologyKey' in value) || value['topologyKey'] === undefined) return false;
    return true;
}

export function PodAffinityTermFromJSON(json: any): PodAffinityTerm {
    return PodAffinityTermFromJSONTyped(json, false);
}

export function PodAffinityTermFromJSONTyped(json: any, ignoreDiscriminator: boolean): PodAffinityTerm {
    if (json == null) {
        return json;
    }
    return {
        
        'labelSelector': json['labelSelector'] == null ? undefined : LabelSelectorFromJSON(json['labelSelector']),
        'namespaces': json['namespaces'] == null ? undefined : json['namespaces'],
        'topologyKey': json['topologyKey'],
    };
}

export function PodAffinityTermToJSON(json: any): PodAffinityTerm {
    return PodAffinityTermToJSONTyped(json, false);
}

export function PodAffinityTermToJSONTyped(value?: PodAffinityTerm | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'labelSelector': LabelSelectorToJSON(value['labelSelector']),
        'namespaces': value['namespaces'],
        'topologyKey': value['topologyKey'],
    };
}

