/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type ProbePort
 * 
 * @export
 */
export type ProbePort = number | string;

export function ProbePortFromJSON(json: any): ProbePort {
    return ProbePortFromJSONTyped(json, false);
}

export function ProbePortFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProbePort {
    if (json == null) {
        return json;
    }
    if (typeof json === 'number') {
        return json;
    }
    if (typeof json === 'string') {
        return json;
    }
    return {} as any;
}

export function ProbePortToJSON(json: any): any {
    return ProbePortToJSONTyped(json, false);
}

export function ProbePortToJSONTyped(value?: ProbePort | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value === 'number') {
        return value;
    }
    if (typeof value === 'string') {
        return value;
    }
    return {};
}

