/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProcessEventLogSnapshot
 */
export interface ProcessEventLogSnapshot {
    /**
     * 
     * @type {number}
     * @memberof ProcessEventLogSnapshot
     */
    nextSeq: number;
    /**
     * 
     * @type {number}
     * @memberof ProcessEventLogSnapshot
     */
    oldestSeq: number;
    /**
     * 
     * @type {number}
     * @memberof ProcessEventLogSnapshot
     */
    capacity: number;
}

/**
 * Check if a given object implements the ProcessEventLogSnapshot interface.
 */
export function instanceOfProcessEventLogSnapshot(value: object): value is ProcessEventLogSnapshot {
    if (!('nextSeq' in value) || value['nextSeq'] === undefined) return false;
    if (!('oldestSeq' in value) || value['oldestSeq'] === undefined) return false;
    if (!('capacity' in value) || value['capacity'] === undefined) return false;
    return true;
}

export function ProcessEventLogSnapshotFromJSON(json: any): ProcessEventLogSnapshot {
    return ProcessEventLogSnapshotFromJSONTyped(json, false);
}

export function ProcessEventLogSnapshotFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProcessEventLogSnapshot {
    if (json == null) {
        return json;
    }
    return {
        
        'nextSeq': json['next_seq'],
        'oldestSeq': json['oldest_seq'],
        'capacity': json['capacity'],
    };
}

export function ProcessEventLogSnapshotToJSON(json: any): ProcessEventLogSnapshot {
    return ProcessEventLogSnapshotToJSONTyped(json, false);
}

export function ProcessEventLogSnapshotToJSONTyped(value?: ProcessEventLogSnapshot | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'next_seq': value['nextSeq'],
        'oldest_seq': value['oldestSeq'],
        'capacity': value['capacity'],
    };
}

