/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProcessCleanupSpec
 */
export interface ProcessCleanupSpec {
    /**
     * 
     * @type {number}
     * @memberof ProcessCleanupSpec
     */
    idleTimeoutSec?: number;
    /**
     * 
     * @type {number}
     * @memberof ProcessCleanupSpec
     */
    ttlSec?: number;
}

/**
 * Check if a given object implements the ProcessCleanupSpec interface.
 */
export function instanceOfProcessCleanupSpec(value: object): value is ProcessCleanupSpec {
    return true;
}

export function ProcessCleanupSpecFromJSON(json: any): ProcessCleanupSpec {
    return ProcessCleanupSpecFromJSONTyped(json, false);
}

export function ProcessCleanupSpecFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProcessCleanupSpec {
    if (json == null) {
        return json;
    }
    return {
        
        'idleTimeoutSec': json['idle_timeout_sec'] == null ? undefined : json['idle_timeout_sec'],
        'ttlSec': json['ttl_sec'] == null ? undefined : json['ttl_sec'],
    };
}

export function ProcessCleanupSpecToJSON(json: any): ProcessCleanupSpec {
    return ProcessCleanupSpecToJSONTyped(json, false);
}

export function ProcessCleanupSpecToJSONTyped(value?: ProcessCleanupSpec | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'idle_timeout_sec': value['idleTimeoutSec'],
        'ttl_sec': value['ttlSec'],
    };
}

