/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ProcessEventType = {
    ProcessStarted: 'process.started',
    ProcessExited: 'process.exited',
    ProcessCrashed: 'process.crashed',
    ProcessStopped: 'process.stopped',
    StdinWrite: 'stdin.write',
    StdoutChunk: 'stdout.chunk',
    StdoutLine: 'stdout.line',
    StderrChunk: 'stderr.chunk',
    StderrLine: 'stderr.line',
    PtyInput: 'pty.input',
    PtyOutput: 'pty.output',
    HttpRequest: 'http.request',
    HttpResponse: 'http.response',
    WebsocketOpen: 'websocket.open',
    WebsocketMessage: 'websocket.message',
    WebsocketClose: 'websocket.close',
    Error: 'error',
    CursorLost: 'cursor_lost'
} as const;
export type ProcessEventType = typeof ProcessEventType[keyof typeof ProcessEventType];


export function instanceOfProcessEventType(value: any): boolean {
    for (const key in ProcessEventType) {
        if (Object.prototype.hasOwnProperty.call(ProcessEventType, key)) {
            if (ProcessEventType[key as keyof typeof ProcessEventType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ProcessEventTypeFromJSON(json: any): ProcessEventType {
    return ProcessEventTypeFromJSONTyped(json, false);
}

export function ProcessEventTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProcessEventType {
    return json as ProcessEventType;
}

export function ProcessEventTypeToJSON(value?: ProcessEventType | null): any {
    return value as any;
}

export function ProcessEventTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): ProcessEventType {
    return value as ProcessEventType;
}

