/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CredentialProjectionType } from './CredentialProjectionType';
import {
    CredentialProjectionTypeFromJSON,
    CredentialProjectionTypeFromJSONTyped,
    CredentialProjectionTypeToJSON,
    CredentialProjectionTypeToJSONTyped,
} from './CredentialProjectionType';
import type { HTTPHeadersProjection } from './HTTPHeadersProjection';
import {
    HTTPHeadersProjectionFromJSON,
    HTTPHeadersProjectionFromJSONTyped,
    HTTPHeadersProjectionToJSON,
    HTTPHeadersProjectionToJSONTyped,
} from './HTTPHeadersProjection';

/**
 * 
 * @export
 * @interface ProjectionSpec
 */
export interface ProjectionSpec {
    /**
     * 
     * @type {CredentialProjectionType}
     * @memberof ProjectionSpec
     */
    type: CredentialProjectionType;
    /**
     * 
     * @type {HTTPHeadersProjection}
     * @memberof ProjectionSpec
     */
    httpHeaders?: HTTPHeadersProjection;
    /**
     * Client certificate projection used for TLS terminate-reoriginate auth.
     * @type {object}
     * @memberof ProjectionSpec
     */
    tlsClientCertificate?: object;
    /**
     * Username/password projection used for SOCKS5 and MQTT auth handshakes.
     * @type {object}
     * @memberof ProjectionSpec
     */
    usernamePassword?: object;
}



/**
 * Check if a given object implements the ProjectionSpec interface.
 */
export function instanceOfProjectionSpec(value: object): value is ProjectionSpec {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function ProjectionSpecFromJSON(json: any): ProjectionSpec {
    return ProjectionSpecFromJSONTyped(json, false);
}

export function ProjectionSpecFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectionSpec {
    if (json == null) {
        return json;
    }
    return {
        
        'type': CredentialProjectionTypeFromJSON(json['type']),
        'httpHeaders': json['httpHeaders'] == null ? undefined : HTTPHeadersProjectionFromJSON(json['httpHeaders']),
        'tlsClientCertificate': json['tlsClientCertificate'] == null ? undefined : json['tlsClientCertificate'],
        'usernamePassword': json['usernamePassword'] == null ? undefined : json['usernamePassword'],
    };
}

export function ProjectionSpecToJSON(json: any): ProjectionSpec {
    return ProjectionSpecToJSONTyped(json, false);
}

export function ProjectionSpecToJSONTyped(value?: ProjectionSpec | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': CredentialProjectionTypeToJSON(value['type']),
        'httpHeaders': HTTPHeadersProjectionToJSON(value['httpHeaders']),
        'tlsClientCertificate': value['tlsClientCertificate'],
        'usernamePassword': value['usernamePassword'],
    };
}

