/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ProtocolRuleProtocol = {
    ProtocolRuleProtocolHttp: 'http',
    ProtocolRuleProtocolMcp: 'mcp'
} as const;
export type ProtocolRuleProtocol = typeof ProtocolRuleProtocol[keyof typeof ProtocolRuleProtocol];


export function instanceOfProtocolRuleProtocol(value: any): boolean {
    for (const key in ProtocolRuleProtocol) {
        if (Object.prototype.hasOwnProperty.call(ProtocolRuleProtocol, key)) {
            if (ProtocolRuleProtocol[key as keyof typeof ProtocolRuleProtocol] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ProtocolRuleProtocolFromJSON(json: any): ProtocolRuleProtocol {
    return ProtocolRuleProtocolFromJSONTyped(json, false);
}

export function ProtocolRuleProtocolFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProtocolRuleProtocol {
    return json as ProtocolRuleProtocol;
}

export function ProtocolRuleProtocolToJSON(value?: ProtocolRuleProtocol | null): any {
    return value as any;
}

export function ProtocolRuleProtocolToJSONTyped(value: any, ignoreDiscriminator: boolean): ProtocolRuleProtocol {
    return value as ProtocolRuleProtocol;
}

