/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const QuotaDimension = {
    ActiveSandboxes: 'active_sandboxes',
    CpuMillicpu: 'cpu_millicpu',
    MemoryMib: 'memory_mib',
    VolumeStorageGb: 'volume_storage_gb',
    SnapshotStorageGb: 'snapshot_storage_gb',
    ApiRequests: 'api_requests',
    NetworkEgressBytes: 'network_egress_bytes',
    NetworkIngressBytes: 'network_ingress_bytes'
} as const;
export type QuotaDimension = typeof QuotaDimension[keyof typeof QuotaDimension];


export function instanceOfQuotaDimension(value: any): boolean {
    for (const key in QuotaDimension) {
        if (Object.prototype.hasOwnProperty.call(QuotaDimension, key)) {
            if (QuotaDimension[key as keyof typeof QuotaDimension] === value) {
                return true;
            }
        }
    }
    return false;
}

export function QuotaDimensionFromJSON(json: any): QuotaDimension {
    return QuotaDimensionFromJSONTyped(json, false);
}

export function QuotaDimensionFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuotaDimension {
    return json as QuotaDimension;
}

export function QuotaDimensionToJSON(value?: QuotaDimension | null): any {
    return value as any;
}

export function QuotaDimensionToJSONTyped(value: any, ignoreDiscriminator: boolean): QuotaDimension {
    return value as QuotaDimension;
}

