/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegistryCredentialsRequest
 */
export interface RegistryCredentialsRequest {
    /**
     * Target image name and tag requested for push, without credentials.
     * @type {string}
     * @memberof RegistryCredentialsRequest
     */
    targetImage?: string;
}

/**
 * Check if a given object implements the RegistryCredentialsRequest interface.
 */
export function instanceOfRegistryCredentialsRequest(value: object): value is RegistryCredentialsRequest {
    return true;
}

export function RegistryCredentialsRequestFromJSON(json: any): RegistryCredentialsRequest {
    return RegistryCredentialsRequestFromJSONTyped(json, false);
}

export function RegistryCredentialsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegistryCredentialsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'targetImage': json['targetImage'] == null ? undefined : json['targetImage'],
    };
}

export function RegistryCredentialsRequestToJSON(json: any): RegistryCredentialsRequest {
    return RegistryCredentialsRequestToJSONTyped(json, false);
}

export function RegistryCredentialsRequestToJSONTyped(value?: RegistryCredentialsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'targetImage': value['targetImage'],
    };
}

