/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by internal-gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegistryCredentials
 */
export interface RegistryCredentials {
    /**
     * 
     * @type {string}
     * @memberof RegistryCredentials
     */
    provider: string;
    /**
     * 
     * @type {string}
     * @memberof RegistryCredentials
     */
    registry: string;
    /**
     * 
     * @type {string}
     * @memberof RegistryCredentials
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof RegistryCredentials
     */
    password: string;
    /**
     * 
     * @type {Date}
     * @memberof RegistryCredentials
     */
    expiresAt?: Date;
}

/**
 * Check if a given object implements the RegistryCredentials interface.
 */
export function instanceOfRegistryCredentials(value: object): value is RegistryCredentials {
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if (!('registry' in value) || value['registry'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function RegistryCredentialsFromJSON(json: any): RegistryCredentials {
    return RegistryCredentialsFromJSONTyped(json, false);
}

export function RegistryCredentialsFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegistryCredentials {
    if (json == null) {
        return json;
    }
    return {
        
        'provider': json['provider'],
        'registry': json['registry'],
        'username': json['username'],
        'password': json['password'],
        'expiresAt': json['expiresAt'] == null ? undefined : (new Date(json['expiresAt'])),
    };
}

export function RegistryCredentialsToJSON(json: any): RegistryCredentials {
    return RegistryCredentialsToJSONTyped(json, false);
}

export function RegistryCredentialsToJSONTyped(value?: RegistryCredentials | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'provider': value['provider'],
        'registry': value['registry'],
        'username': value['username'],
        'password': value['password'],
        'expiresAt': value['expiresAt'] == null ? value['expiresAt'] : value['expiresAt'].toISOString(),
    };
}

