/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global directory.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Region
 */
export interface Region {
    /**
     * 
     * @type {string}
     * @memberof Region
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Region
     */
    displayName?: string;
    /**
     * 
     * @type {string}
     * @memberof Region
     */
    edgeGatewayUrl: string;
    /**
     * 
     * @type {boolean}
     * @memberof Region
     */
    enabled: boolean;
}

/**
 * Check if a given object implements the Region interface.
 */
export function instanceOfRegion(value: object): value is Region {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('edgeGatewayUrl' in value) || value['edgeGatewayUrl'] === undefined) return false;
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    return true;
}

export function RegionFromJSON(json: any): Region {
    return RegionFromJSONTyped(json, false);
}

export function RegionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Region {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'displayName': json['display_name'] == null ? undefined : json['display_name'],
        'edgeGatewayUrl': json['edge_gateway_url'],
        'enabled': json['enabled'],
    };
}

export function RegionToJSON(json: any): Region {
    return RegionToJSONTyped(json, false);
}

export function RegionToJSONTyped(value?: Region | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'display_name': value['displayName'],
        'edge_gateway_url': value['edgeGatewayUrl'],
        'enabled': value['enabled'],
    };
}

