/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResolveVolumeSyncConflictRequest
 */
export interface ResolveVolumeSyncConflictRequest {
    /**
     * 
     * @type {string}
     * @memberof ResolveVolumeSyncConflictRequest
     */
    status: ResolveVolumeSyncConflictRequestStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof ResolveVolumeSyncConflictRequest
     */
    resolution?: string;
    /**
     * 
     * @type {string}
     * @memberof ResolveVolumeSyncConflictRequest
     */
    note?: string;
}


/**
 * @export
 */
export const ResolveVolumeSyncConflictRequestStatusEnum = {
    Resolved: 'resolved',
    Ignored: 'ignored'
} as const;
export type ResolveVolumeSyncConflictRequestStatusEnum = typeof ResolveVolumeSyncConflictRequestStatusEnum[keyof typeof ResolveVolumeSyncConflictRequestStatusEnum];


/**
 * Check if a given object implements the ResolveVolumeSyncConflictRequest interface.
 */
export function instanceOfResolveVolumeSyncConflictRequest(value: object): value is ResolveVolumeSyncConflictRequest {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function ResolveVolumeSyncConflictRequestFromJSON(json: any): ResolveVolumeSyncConflictRequest {
    return ResolveVolumeSyncConflictRequestFromJSONTyped(json, false);
}

export function ResolveVolumeSyncConflictRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResolveVolumeSyncConflictRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'resolution': json['resolution'] == null ? undefined : json['resolution'],
        'note': json['note'] == null ? undefined : json['note'],
    };
}

export function ResolveVolumeSyncConflictRequestToJSON(json: any): ResolveVolumeSyncConflictRequest {
    return ResolveVolumeSyncConflictRequestToJSONTyped(json, false);
}

export function ResolveVolumeSyncConflictRequestToJSONTyped(value?: ResolveVolumeSyncConflictRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'resolution': value['resolution'],
        'note': value['note'],
    };
}

