/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Run } from './Run';
import {
    RunFromJSON,
    RunFromJSONTyped,
    RunToJSON,
    RunToJSONTyped,
} from './Run';
import type { RunRevision } from './RunRevision';
import {
    RunRevisionFromJSON,
    RunRevisionFromJSONTyped,
    RunRevisionToJSON,
    RunRevisionToJSONTyped,
} from './RunRevision';

/**
 * 
 * @export
 * @interface RunDeployResult
 */
export interface RunDeployResult {
    /**
     * 
     * @type {Run}
     * @memberof RunDeployResult
     */
    run: Run;
    /**
     * 
     * @type {RunRevision}
     * @memberof RunDeployResult
     */
    revision: RunRevision;
}

/**
 * Check if a given object implements the RunDeployResult interface.
 */
export function instanceOfRunDeployResult(value: object): value is RunDeployResult {
    if (!('run' in value) || value['run'] === undefined) return false;
    if (!('revision' in value) || value['revision'] === undefined) return false;
    return true;
}

export function RunDeployResultFromJSON(json: any): RunDeployResult {
    return RunDeployResultFromJSONTyped(json, false);
}

export function RunDeployResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): RunDeployResult {
    if (json == null) {
        return json;
    }
    return {
        
        'run': RunFromJSON(json['run']),
        'revision': RunRevisionFromJSON(json['revision']),
    };
}

export function RunDeployResultToJSON(json: any): RunDeployResult {
    return RunDeployResultToJSONTyped(json, false);
}

export function RunDeployResultToJSONTyped(value?: RunDeployResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'run': RunToJSON(value['run']),
        'revision': RunRevisionToJSON(value['revision']),
    };
}

