/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RunRevisionStatus } from './RunRevisionStatus';
import {
    RunRevisionStatusFromJSON,
    RunRevisionStatusFromJSONTyped,
    RunRevisionStatusToJSON,
    RunRevisionStatusToJSONTyped,
} from './RunRevisionStatus';
import type { RunSource } from './RunSource';
import {
    RunSourceFromJSON,
    RunSourceFromJSONTyped,
    RunSourceToJSON,
    RunSourceToJSONTyped,
} from './RunSource';
import type { RunRevisionSpec } from './RunRevisionSpec';
import {
    RunRevisionSpecFromJSON,
    RunRevisionSpecFromJSONTyped,
    RunRevisionSpecToJSON,
    RunRevisionSpecToJSONTyped,
} from './RunRevisionSpec';

/**
 * 
 * @export
 * @interface RunRevision
 */
export interface RunRevision {
    /**
     * 
     * @type {string}
     * @memberof RunRevision
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof RunRevision
     */
    runId: string;
    /**
     * 
     * @type {string}
     * @memberof RunRevision
     */
    teamId: string;
    /**
     * 
     * @type {number}
     * @memberof RunRevision
     */
    number: number;
    /**
     * 
     * @type {RunSource}
     * @memberof RunRevision
     */
    source: RunSource;
    /**
     * 
     * @type {RunRevisionSpec}
     * @memberof RunRevision
     */
    spec: RunRevisionSpec;
    /**
     * 
     * @type {RunRevisionStatus}
     * @memberof RunRevision
     */
    status: RunRevisionStatus;
    /**
     * 
     * @type {string}
     * @memberof RunRevision
     */
    runtimeSandboxId?: string;
    /**
     * 
     * @type {string}
     * @memberof RunRevision
     */
    runtimeClusterId?: string;
    /**
     * 
     * @type {string}
     * @memberof RunRevision
     */
    runtimeContextId?: string;
    /**
     * 
     * @type {Date}
     * @memberof RunRevision
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof RunRevision
     */
    activatedAt?: Date;
}



/**
 * Check if a given object implements the RunRevision interface.
 */
export function instanceOfRunRevision(value: object): value is RunRevision {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('runId' in value) || value['runId'] === undefined) return false;
    if (!('teamId' in value) || value['teamId'] === undefined) return false;
    if (!('number' in value) || value['number'] === undefined) return false;
    if (!('source' in value) || value['source'] === undefined) return false;
    if (!('spec' in value) || value['spec'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function RunRevisionFromJSON(json: any): RunRevision {
    return RunRevisionFromJSONTyped(json, false);
}

export function RunRevisionFromJSONTyped(json: any, ignoreDiscriminator: boolean): RunRevision {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'runId': json['run_id'],
        'teamId': json['team_id'],
        'number': json['number'],
        'source': RunSourceFromJSON(json['source']),
        'spec': RunRevisionSpecFromJSON(json['spec']),
        'status': RunRevisionStatusFromJSON(json['status']),
        'runtimeSandboxId': json['runtime_sandbox_id'] == null ? undefined : json['runtime_sandbox_id'],
        'runtimeClusterId': json['runtime_cluster_id'] == null ? undefined : json['runtime_cluster_id'],
        'runtimeContextId': json['runtime_context_id'] == null ? undefined : json['runtime_context_id'],
        'createdAt': (new Date(json['created_at'])),
        'activatedAt': json['activated_at'] == null ? undefined : (new Date(json['activated_at'])),
    };
}

export function RunRevisionToJSON(json: any): RunRevision {
    return RunRevisionToJSONTyped(json, false);
}

export function RunRevisionToJSONTyped(value?: RunRevision | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'run_id': value['runId'],
        'team_id': value['teamId'],
        'number': value['number'],
        'source': RunSourceToJSON(value['source']),
        'spec': RunRevisionSpecToJSON(value['spec']),
        'status': RunRevisionStatusToJSON(value['status']),
        'runtime_sandbox_id': value['runtimeSandboxId'],
        'runtime_cluster_id': value['runtimeClusterId'],
        'runtime_context_id': value['runtimeContextId'],
        'created_at': value['createdAt'].toISOString(),
        'activated_at': value['activatedAt'] == null ? value['activatedAt'] : value['activatedAt'].toISOString(),
    };
}

