/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Scale-to-zero policy. Runs do not have a minimum idle instance count.
 * @export
 * @interface RunScalePolicy
 */
export interface RunScalePolicy {
    /**
     * 
     * @type {number}
     * @memberof RunScalePolicy
     */
    maxInstances?: number;
    /**
     * 
     * @type {number}
     * @memberof RunScalePolicy
     */
    targetConcurrency?: number;
    /**
     * Seconds of inactivity before the runtime sandbox can scale back to zero.
     * @type {number}
     * @memberof RunScalePolicy
     */
    idleTimeoutSeconds?: number;
    /**
     * Maximum seconds to wait for a cold-started service health check.
     * @type {number}
     * @memberof RunScalePolicy
     */
    startupTimeoutSeconds?: number;
}

/**
 * Check if a given object implements the RunScalePolicy interface.
 */
export function instanceOfRunScalePolicy(value: object): value is RunScalePolicy {
    return true;
}

export function RunScalePolicyFromJSON(json: any): RunScalePolicy {
    return RunScalePolicyFromJSONTyped(json, false);
}

export function RunScalePolicyFromJSONTyped(json: any, ignoreDiscriminator: boolean): RunScalePolicy {
    if (json == null) {
        return json;
    }
    return {
        
        'maxInstances': json['max_instances'] == null ? undefined : json['max_instances'],
        'targetConcurrency': json['target_concurrency'] == null ? undefined : json['target_concurrency'],
        'idleTimeoutSeconds': json['idle_timeout_seconds'] == null ? undefined : json['idle_timeout_seconds'],
        'startupTimeoutSeconds': json['startup_timeout_seconds'] == null ? undefined : json['startup_timeout_seconds'],
    };
}

export function RunScalePolicyToJSON(json: any): RunScalePolicy {
    return RunScalePolicyToJSONTyped(json, false);
}

export function RunScalePolicyToJSONTyped(value?: RunScalePolicy | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'max_instances': value['maxInstances'],
        'target_concurrency': value['targetConcurrency'],
        'idle_timeout_seconds': value['idleTimeoutSeconds'],
        'startup_timeout_seconds': value['startupTimeoutSeconds'],
    };
}

