/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by internal-gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PoolStrategy } from './PoolStrategy';
import {
    PoolStrategyFromJSON,
    PoolStrategyFromJSONTyped,
    PoolStrategyToJSON,
    PoolStrategyToJSONTyped,
} from './PoolStrategy';
import type { ContainerSpec } from './ContainerSpec';
import {
    ContainerSpecFromJSON,
    ContainerSpecFromJSONTyped,
    ContainerSpecToJSON,
    ContainerSpecToJSONTyped,
} from './ContainerSpec';
import type { LifecyclePolicy } from './LifecyclePolicy';
import {
    LifecyclePolicyFromJSON,
    LifecyclePolicyFromJSONTyped,
    LifecyclePolicyToJSON,
    LifecyclePolicyToJSONTyped,
} from './LifecyclePolicy';
import type { TplSandboxNetworkPolicy } from './TplSandboxNetworkPolicy';
import {
    TplSandboxNetworkPolicyFromJSON,
    TplSandboxNetworkPolicyFromJSONTyped,
    TplSandboxNetworkPolicyToJSON,
    TplSandboxNetworkPolicyToJSONTyped,
} from './TplSandboxNetworkPolicy';
import type { PodSpecOverride } from './PodSpecOverride';
import {
    PodSpecOverrideFromJSON,
    PodSpecOverrideFromJSONTyped,
    PodSpecOverrideToJSON,
    PodSpecOverrideToJSONTyped,
} from './PodSpecOverride';

/**
 * 
 * @export
 * @interface SandboxTemplateSpec
 */
export interface SandboxTemplateSpec {
    /**
     * 
     * @type {string}
     * @memberof SandboxTemplateSpec
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof SandboxTemplateSpec
     */
    displayName?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof SandboxTemplateSpec
     */
    tags?: Array<string>;
    /**
     * 
     * @type {ContainerSpec}
     * @memberof SandboxTemplateSpec
     */
    mainContainer?: ContainerSpec;
    /**
     * 
     * @type {Array<ContainerSpec>}
     * @memberof SandboxTemplateSpec
     */
    sidecars?: Array<ContainerSpec>;
    /**
     * 
     * @type {PodSpecOverride}
     * @memberof SandboxTemplateSpec
     */
    pod?: PodSpecOverride;
    /**
     * 
     * @type {TplSandboxNetworkPolicy}
     * @memberof SandboxTemplateSpec
     */
    network?: TplSandboxNetworkPolicy;
    /**
     * 
     * @type {PoolStrategy}
     * @memberof SandboxTemplateSpec
     */
    pool?: PoolStrategy;
    /**
     * 
     * @type {LifecyclePolicy}
     * @memberof SandboxTemplateSpec
     */
    lifecycle?: LifecyclePolicy;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof SandboxTemplateSpec
     */
    envVars?: { [key: string]: string; };
    /**
     * 
     * @type {boolean}
     * @memberof SandboxTemplateSpec
     */
    _public?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof SandboxTemplateSpec
     */
    allowedTeams?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof SandboxTemplateSpec
     */
    runtimeClassName?: string;
    /**
     * 
     * @type {string}
     * @memberof SandboxTemplateSpec
     */
    clusterId?: string;
}

/**
 * Check if a given object implements the SandboxTemplateSpec interface.
 */
export function instanceOfSandboxTemplateSpec(value: object): value is SandboxTemplateSpec {
    return true;
}

export function SandboxTemplateSpecFromJSON(json: any): SandboxTemplateSpec {
    return SandboxTemplateSpecFromJSONTyped(json, false);
}

export function SandboxTemplateSpecFromJSONTyped(json: any, ignoreDiscriminator: boolean): SandboxTemplateSpec {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'displayName': json['displayName'] == null ? undefined : json['displayName'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'mainContainer': json['mainContainer'] == null ? undefined : ContainerSpecFromJSON(json['mainContainer']),
        'sidecars': json['sidecars'] == null ? undefined : ((json['sidecars'] as Array<any>).map(ContainerSpecFromJSON)),
        'pod': json['pod'] == null ? undefined : PodSpecOverrideFromJSON(json['pod']),
        'network': json['network'] == null ? undefined : TplSandboxNetworkPolicyFromJSON(json['network']),
        'pool': json['pool'] == null ? undefined : PoolStrategyFromJSON(json['pool']),
        'lifecycle': json['lifecycle'] == null ? undefined : LifecyclePolicyFromJSON(json['lifecycle']),
        'envVars': json['envVars'] == null ? undefined : json['envVars'],
        '_public': json['public'] == null ? undefined : json['public'],
        'allowedTeams': json['allowedTeams'] == null ? undefined : json['allowedTeams'],
        'runtimeClassName': json['runtimeClassName'] == null ? undefined : json['runtimeClassName'],
        'clusterId': json['clusterId'] == null ? undefined : json['clusterId'],
    };
}

export function SandboxTemplateSpecToJSON(json: any): SandboxTemplateSpec {
    return SandboxTemplateSpecToJSONTyped(json, false);
}

export function SandboxTemplateSpecToJSONTyped(value?: SandboxTemplateSpec | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'displayName': value['displayName'],
        'tags': value['tags'],
        'mainContainer': ContainerSpecToJSON(value['mainContainer']),
        'sidecars': value['sidecars'] == null ? undefined : ((value['sidecars'] as Array<any>).map(ContainerSpecToJSON)),
        'pod': PodSpecOverrideToJSON(value['pod']),
        'network': TplSandboxNetworkPolicyToJSON(value['network']),
        'pool': PoolStrategyToJSON(value['pool']),
        'lifecycle': LifecyclePolicyToJSON(value['lifecycle']),
        'envVars': value['envVars'],
        'public': value['_public'],
        'allowedTeams': value['allowedTeams'],
        'runtimeClassName': value['runtimeClassName'],
        'clusterId': value['clusterId'],
    };
}

