/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SandboxRuntimeMetricName } from './SandboxRuntimeMetricName';
import {
    SandboxRuntimeMetricNameFromJSON,
    SandboxRuntimeMetricNameFromJSONTyped,
    SandboxRuntimeMetricNameToJSON,
    SandboxRuntimeMetricNameToJSONTyped,
} from './SandboxRuntimeMetricName';
import type { SandboxRuntimeMetricUnit } from './SandboxRuntimeMetricUnit';
import {
    SandboxRuntimeMetricUnitFromJSON,
    SandboxRuntimeMetricUnitFromJSONTyped,
    SandboxRuntimeMetricUnitToJSON,
    SandboxRuntimeMetricUnitToJSONTyped,
} from './SandboxRuntimeMetricUnit';
import type { SandboxRuntimeMetricKind } from './SandboxRuntimeMetricKind';
import {
    SandboxRuntimeMetricKindFromJSON,
    SandboxRuntimeMetricKindFromJSONTyped,
    SandboxRuntimeMetricKindToJSON,
    SandboxRuntimeMetricKindToJSONTyped,
} from './SandboxRuntimeMetricKind';

/**
 * 
 * @export
 * @interface SandboxRuntimeMetricDescriptor
 */
export interface SandboxRuntimeMetricDescriptor {
    /**
     * 
     * @type {SandboxRuntimeMetricName}
     * @memberof SandboxRuntimeMetricDescriptor
     */
    name: SandboxRuntimeMetricName;
    /**
     * 
     * @type {SandboxRuntimeMetricKind}
     * @memberof SandboxRuntimeMetricDescriptor
     */
    kind: SandboxRuntimeMetricKind;
    /**
     * 
     * @type {SandboxRuntimeMetricUnit}
     * @memberof SandboxRuntimeMetricDescriptor
     */
    unit: SandboxRuntimeMetricUnit;
    /**
     * 
     * @type {Array<string>}
     * @memberof SandboxRuntimeMetricDescriptor
     */
    dimensions: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof SandboxRuntimeMetricDescriptor
     */
    description: string;
}



/**
 * Check if a given object implements the SandboxRuntimeMetricDescriptor interface.
 */
export function instanceOfSandboxRuntimeMetricDescriptor(value: object): value is SandboxRuntimeMetricDescriptor {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('unit' in value) || value['unit'] === undefined) return false;
    if (!('dimensions' in value) || value['dimensions'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function SandboxRuntimeMetricDescriptorFromJSON(json: any): SandboxRuntimeMetricDescriptor {
    return SandboxRuntimeMetricDescriptorFromJSONTyped(json, false);
}

export function SandboxRuntimeMetricDescriptorFromJSONTyped(json: any, ignoreDiscriminator: boolean): SandboxRuntimeMetricDescriptor {
    if (json == null) {
        return json;
    }
    return {
        
        'name': SandboxRuntimeMetricNameFromJSON(json['name']),
        'kind': SandboxRuntimeMetricKindFromJSON(json['kind']),
        'unit': SandboxRuntimeMetricUnitFromJSON(json['unit']),
        'dimensions': json['dimensions'],
        'description': json['description'],
    };
}

export function SandboxRuntimeMetricDescriptorToJSON(json: any): SandboxRuntimeMetricDescriptor {
    return SandboxRuntimeMetricDescriptorToJSONTyped(json, false);
}

export function SandboxRuntimeMetricDescriptorToJSONTyped(value?: SandboxRuntimeMetricDescriptor | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': SandboxRuntimeMetricNameToJSON(value['name']),
        'kind': SandboxRuntimeMetricKindToJSON(value['kind']),
        'unit': SandboxRuntimeMetricUnitToJSON(value['unit']),
        'dimensions': value['dimensions'],
        'description': value['description'],
    };
}

