/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by internal-gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SandboxTemplateCondition
 */
export interface SandboxTemplateCondition {
    /**
     * 
     * @type {string}
     * @memberof SandboxTemplateCondition
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof SandboxTemplateCondition
     */
    status?: string;
    /**
     * 
     * @type {Date}
     * @memberof SandboxTemplateCondition
     */
    lastTransitionTime?: Date;
    /**
     * 
     * @type {string}
     * @memberof SandboxTemplateCondition
     */
    reason?: string;
    /**
     * 
     * @type {string}
     * @memberof SandboxTemplateCondition
     */
    message?: string;
}

/**
 * Check if a given object implements the SandboxTemplateCondition interface.
 */
export function instanceOfSandboxTemplateCondition(value: object): value is SandboxTemplateCondition {
    return true;
}

export function SandboxTemplateConditionFromJSON(json: any): SandboxTemplateCondition {
    return SandboxTemplateConditionFromJSONTyped(json, false);
}

export function SandboxTemplateConditionFromJSONTyped(json: any, ignoreDiscriminator: boolean): SandboxTemplateCondition {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'status': json['status'] == null ? undefined : json['status'],
        'lastTransitionTime': json['lastTransitionTime'] == null ? undefined : (new Date(json['lastTransitionTime'])),
        'reason': json['reason'] == null ? undefined : json['reason'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function SandboxTemplateConditionToJSON(json: any): SandboxTemplateCondition {
    return SandboxTemplateConditionToJSONTyped(json, false);
}

export function SandboxTemplateConditionToJSONTyped(value?: SandboxTemplateCondition | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'status': value['status'],
        'lastTransitionTime': value['lastTransitionTime'] == null ? value['lastTransitionTime'] : value['lastTransitionTime'].toISOString(),
        'reason': value['reason'],
        'message': value['message'],
    };
}

