/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by internal-gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ObjectMeta } from './ObjectMeta';
import {
    ObjectMetaFromJSON,
    ObjectMetaFromJSONTyped,
    ObjectMetaToJSON,
    ObjectMetaToJSONTyped,
} from './ObjectMeta';
import type { SandboxTemplateSpec } from './SandboxTemplateSpec';
import {
    SandboxTemplateSpecFromJSON,
    SandboxTemplateSpecFromJSONTyped,
    SandboxTemplateSpecToJSON,
    SandboxTemplateSpecToJSONTyped,
} from './SandboxTemplateSpec';
import type { SandboxTemplateStatus } from './SandboxTemplateStatus';
import {
    SandboxTemplateStatusFromJSON,
    SandboxTemplateStatusFromJSONTyped,
    SandboxTemplateStatusToJSON,
    SandboxTemplateStatusToJSONTyped,
} from './SandboxTemplateStatus';

/**
 * 
 * @export
 * @interface SandboxTemplate
 */
export interface SandboxTemplate {
    /**
     * 
     * @type {string}
     * @memberof SandboxTemplate
     */
    apiVersion?: string;
    /**
     * 
     * @type {string}
     * @memberof SandboxTemplate
     */
    kind?: string;
    /**
     * 
     * @type {ObjectMeta}
     * @memberof SandboxTemplate
     */
    metadata?: ObjectMeta;
    /**
     * 
     * @type {SandboxTemplateSpec}
     * @memberof SandboxTemplate
     */
    spec?: SandboxTemplateSpec;
    /**
     * 
     * @type {SandboxTemplateStatus}
     * @memberof SandboxTemplate
     */
    status?: SandboxTemplateStatus;
}

/**
 * Check if a given object implements the SandboxTemplate interface.
 */
export function instanceOfSandboxTemplate(value: object): value is SandboxTemplate {
    return true;
}

export function SandboxTemplateFromJSON(json: any): SandboxTemplate {
    return SandboxTemplateFromJSONTyped(json, false);
}

export function SandboxTemplateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SandboxTemplate {
    if (json == null) {
        return json;
    }
    return {
        
        'apiVersion': json['apiVersion'] == null ? undefined : json['apiVersion'],
        'kind': json['kind'] == null ? undefined : json['kind'],
        'metadata': json['metadata'] == null ? undefined : ObjectMetaFromJSON(json['metadata']),
        'spec': json['spec'] == null ? undefined : SandboxTemplateSpecFromJSON(json['spec']),
        'status': json['status'] == null ? undefined : SandboxTemplateStatusFromJSON(json['status']),
    };
}

export function SandboxTemplateToJSON(json: any): SandboxTemplate {
    return SandboxTemplateToJSONTyped(json, false);
}

export function SandboxTemplateToJSONTyped(value?: SandboxTemplate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'apiVersion': value['apiVersion'],
        'kind': value['kind'],
        'metadata': ObjectMetaToJSON(value['metadata']),
        'spec': SandboxTemplateSpecToJSON(value['spec']),
        'status': SandboxTemplateStatusToJSON(value['status']),
    };
}

