/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SandboxExecutionStateRequest
 */
export interface SandboxExecutionStateRequest {
    /**
     * On pause, retain process memory and execution state; capture failures remain errors. On resume, prefer retained memory and fall back to the committed RootFS if memory is missing, incompatible, or cannot be restored. Omitted or false uses filesystem-only behavior.
     * @type {boolean}
     * @memberof SandboxExecutionStateRequest
     */
    memory?: boolean;
}

/**
 * Check if a given object implements the SandboxExecutionStateRequest interface.
 */
export function instanceOfSandboxExecutionStateRequest(value: object): value is SandboxExecutionStateRequest {
    return true;
}

export function SandboxExecutionStateRequestFromJSON(json: any): SandboxExecutionStateRequest {
    return SandboxExecutionStateRequestFromJSONTyped(json, false);
}

export function SandboxExecutionStateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SandboxExecutionStateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'memory': json['memory'] == null ? undefined : json['memory'],
    };
}

export function SandboxExecutionStateRequestToJSON(json: any): SandboxExecutionStateRequest {
    return SandboxExecutionStateRequestToJSONTyped(json, false);
}

export function SandboxExecutionStateRequestToJSONTyped(value?: SandboxExecutionStateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'memory': value['memory'],
    };
}

