/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Function source code stored in sandbox service config.
 * @export
 * @interface SandboxFunctionSource
 */
export interface SandboxFunctionSource {
    /**
     * Source transport. Only inline source is supported in this version.
     * @type {string}
     * @memberof SandboxFunctionSource
     */
    type: SandboxFunctionSourceTypeEnum;
    /**
     * Relative Python filename used when materializing the source. Defaults to main.py.
     * @type {string}
     * @memberof SandboxFunctionSource
     */
    filename?: string;
    /**
     * Inline source code. Limited to 256 KiB.
     * @type {string}
     * @memberof SandboxFunctionSource
     */
    code: string;
}


/**
 * @export
 */
export const SandboxFunctionSourceTypeEnum = {
    Inline: 'inline'
} as const;
export type SandboxFunctionSourceTypeEnum = typeof SandboxFunctionSourceTypeEnum[keyof typeof SandboxFunctionSourceTypeEnum];


/**
 * Check if a given object implements the SandboxFunctionSource interface.
 */
export function instanceOfSandboxFunctionSource(value: object): value is SandboxFunctionSource {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function SandboxFunctionSourceFromJSON(json: any): SandboxFunctionSource {
    return SandboxFunctionSourceFromJSONTyped(json, false);
}

export function SandboxFunctionSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): SandboxFunctionSource {
    if (json == null) {
        return json;
    }
    return {

        'type': json['type'],
        'filename': json['filename'] == null ? undefined : json['filename'],
        'code': json['code'],
    };
}

export function SandboxFunctionSourceToJSON(json: any): SandboxFunctionSource {
    return SandboxFunctionSourceToJSONTyped(json, false);
}

export function SandboxFunctionSourceToJSONTyped(value?: SandboxFunctionSource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'type': value['type'],
        'filename': value['filename'],
        'code': value['code'],
    };
}
