/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SandboxAppService } from './SandboxAppService';
import {
    SandboxAppServiceFromJSON,
    SandboxAppServiceFromJSONTyped,
    SandboxAppServiceToJSON,
    SandboxAppServiceToJSONTyped,
} from './SandboxAppService';
import type { SandboxResourceConfig } from './SandboxResourceConfig';
import {
    SandboxResourceConfigFromJSON,
    SandboxResourceConfigFromJSONTyped,
    SandboxResourceConfigToJSON,
    SandboxResourceConfigToJSONTyped,
} from './SandboxResourceConfig';
import type { SandboxNetworkPolicy } from './SandboxNetworkPolicy';
import {
    SandboxNetworkPolicyFromJSON,
    SandboxNetworkPolicyFromJSONTyped,
    SandboxNetworkPolicyToJSON,
    SandboxNetworkPolicyToJSONTyped,
} from './SandboxNetworkPolicy';
import type { WebhookConfig } from './WebhookConfig';
import {
    WebhookConfigFromJSON,
    WebhookConfigFromJSONTyped,
    WebhookConfigToJSON,
    WebhookConfigToJSONTyped,
} from './WebhookConfig';

/**
 *
 * @export
 * @interface SandboxConfig
 */
export interface SandboxConfig {
    /**
     *
     * @type {{ [key: string]: string; }}
     * @memberof SandboxConfig
     */
    envVars?: { [key: string]: string; };
    /**
     *
     * @type {SandboxResourceConfig}
     * @memberof SandboxConfig
     */
    resources?: SandboxResourceConfig;
    /**
     * Runtime soft time-to-live in seconds. When it expires, Sandbox0 checkpoints the writable rootfs, pauses the sandbox, and releases runtime compute while preserving durable sandbox state.
     * @type {number}
     * @memberof SandboxConfig
     */
    ttl?: number;
    /**
     * Sandbox hard time-to-live in seconds. When it expires, Sandbox0 deletes the sandbox identity and durable state, including paused rootfs checkpoints.
     * @type {number}
     * @memberof SandboxConfig
     */
    hardTtl?: number;
    /**
     *
     * @type {SandboxNetworkPolicy}
     * @memberof SandboxConfig
     */
    network?: SandboxNetworkPolicy;
    /**
     *
     * @type {WebhookConfig}
     * @memberof SandboxConfig
     */
    webhook?: WebhookConfig;
    /**
     * Sandbox-level resume gate for paused sandboxes. When false, any inbound request
     * (API or public exposure) must not auto resume the sandbox.
     *
     * @type {boolean}
     * @memberof SandboxConfig
     */
    autoResume?: boolean;
    /**
     *
     * @type {Array<SandboxAppService>}
     * @memberof SandboxConfig
     */
    services?: Array<SandboxAppService>;
}

/**
 * Check if a given object implements the SandboxConfig interface.
 */
export function instanceOfSandboxConfig(value: object): value is SandboxConfig {
    return true;
}

export function SandboxConfigFromJSON(json: any): SandboxConfig {
    return SandboxConfigFromJSONTyped(json, false);
}

export function SandboxConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): SandboxConfig {
    if (json == null) {
        return json;
    }
    return {

        'envVars': json['env_vars'] == null ? undefined : json['env_vars'],
        'resources': json['resources'] == null ? undefined : SandboxResourceConfigFromJSON(json['resources']),
        'ttl': json['ttl'] == null ? undefined : json['ttl'],
        'hardTtl': json['hard_ttl'] == null ? undefined : json['hard_ttl'],
        'network': json['network'] == null ? undefined : SandboxNetworkPolicyFromJSON(json['network']),
        'webhook': json['webhook'] == null ? undefined : WebhookConfigFromJSON(json['webhook']),
        'autoResume': json['auto_resume'] == null ? undefined : json['auto_resume'],
        'services': json['services'] == null ? undefined : ((json['services'] as Array<any>).map(SandboxAppServiceFromJSON)),
    };
}

export function SandboxConfigToJSON(json: any): SandboxConfig {
    return SandboxConfigToJSONTyped(json, false);
}

export function SandboxConfigToJSONTyped(value?: SandboxConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'env_vars': value['envVars'],
        'resources': SandboxResourceConfigToJSON(value['resources']),
        'ttl': value['ttl'],
        'hard_ttl': value['hardTtl'],
        'network': SandboxNetworkPolicyToJSON(value['network']),
        'webhook': WebhookConfigToJSON(value['webhook']),
        'auto_resume': value['autoResume'],
        'services': value['services'] == null ? undefined : ((value['services'] as Array<any>).map(SandboxAppServiceToJSON)),
    };
}

