/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { SandboxObservabilityEvent } from './SandboxObservabilityEvent';
import {
    instanceOfSandboxObservabilityEvent,
    SandboxObservabilityEventFromJSON,
    SandboxObservabilityEventFromJSONTyped,
    SandboxObservabilityEventToJSON,
} from './SandboxObservabilityEvent';
import type { SandboxObservabilityLogEntry } from './SandboxObservabilityLogEntry';
import {
    instanceOfSandboxObservabilityLogEntry,
    SandboxObservabilityLogEntryFromJSON,
    SandboxObservabilityLogEntryFromJSONTyped,
    SandboxObservabilityLogEntryToJSON,
} from './SandboxObservabilityLogEntry';
import type { SandboxObservabilityMetricSample } from './SandboxObservabilityMetricSample';
import {
    instanceOfSandboxObservabilityMetricSample,
    SandboxObservabilityMetricSampleFromJSON,
    SandboxObservabilityMetricSampleFromJSONTyped,
    SandboxObservabilityMetricSampleToJSON,
} from './SandboxObservabilityMetricSample';

/**
 * @type SandboxObservabilityWatchLineData
 * 
 * @export
 */
export type SandboxObservabilityWatchLineData = SandboxObservabilityEvent | SandboxObservabilityLogEntry | SandboxObservabilityMetricSample;

export function SandboxObservabilityWatchLineDataFromJSON(json: any): SandboxObservabilityWatchLineData {
    return SandboxObservabilityWatchLineDataFromJSONTyped(json, false);
}

export function SandboxObservabilityWatchLineDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SandboxObservabilityWatchLineData {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfSandboxObservabilityEvent(json)) {
        return SandboxObservabilityEventFromJSONTyped(json, true);
    }
    if (instanceOfSandboxObservabilityLogEntry(json)) {
        return SandboxObservabilityLogEntryFromJSONTyped(json, true);
    }
    if (instanceOfSandboxObservabilityMetricSample(json)) {
        return SandboxObservabilityMetricSampleFromJSONTyped(json, true);
    }
    return {} as any;
}

export function SandboxObservabilityWatchLineDataToJSON(json: any): any {
    return SandboxObservabilityWatchLineDataToJSONTyped(json, false);
}

export function SandboxObservabilityWatchLineDataToJSONTyped(value?: SandboxObservabilityWatchLineData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfSandboxObservabilityEvent(value)) {
        return SandboxObservabilityEventToJSON(value as SandboxObservabilityEvent);
    }
    if (instanceOfSandboxObservabilityLogEntry(value)) {
        return SandboxObservabilityLogEntryToJSON(value as SandboxObservabilityLogEntry);
    }
    if (instanceOfSandboxObservabilityMetricSample(value)) {
        return SandboxObservabilityMetricSampleToJSON(value as SandboxObservabilityMetricSample);
    }
    return {};
}

