/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SandboxServiceFunctionSource
 */
export interface SandboxServiceFunctionSource {
    /**
     * 
     * @type {string}
     * @memberof SandboxServiceFunctionSource
     */
    sandboxId: string;
    /**
     * 
     * @type {string}
     * @memberof SandboxServiceFunctionSource
     */
    serviceId: string;
}

/**
 * Check if a given object implements the SandboxServiceFunctionSource interface.
 */
export function instanceOfSandboxServiceFunctionSource(value: object): value is SandboxServiceFunctionSource {
    if (!('sandboxId' in value) || value['sandboxId'] === undefined) return false;
    if (!('serviceId' in value) || value['serviceId'] === undefined) return false;
    return true;
}

export function SandboxServiceFunctionSourceFromJSON(json: any): SandboxServiceFunctionSource {
    return SandboxServiceFunctionSourceFromJSONTyped(json, false);
}

export function SandboxServiceFunctionSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): SandboxServiceFunctionSource {
    if (json == null) {
        return json;
    }
    return {
        
        'sandboxId': json['sandbox_id'],
        'serviceId': json['service_id'],
    };
}

export function SandboxServiceFunctionSourceToJSON(json: any): SandboxServiceFunctionSource {
    return SandboxServiceFunctionSourceToJSONTyped(json, false);
}

export function SandboxServiceFunctionSourceToJSONTyped(value?: SandboxServiceFunctionSource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sandbox_id': value['sandboxId'],
        'service_id': value['serviceId'],
    };
}

