/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SandboxAppServiceHealth } from './SandboxAppServiceHealth';
import {
    SandboxAppServiceHealthFromJSON,
    SandboxAppServiceHealthFromJSONTyped,
    SandboxAppServiceHealthToJSON,
    SandboxAppServiceHealthToJSONTyped,
} from './SandboxAppServiceHealth';
import type { SandboxAppServiceIngress } from './SandboxAppServiceIngress';
import {
    SandboxAppServiceIngressFromJSON,
    SandboxAppServiceIngressFromJSONTyped,
    SandboxAppServiceIngressToJSON,
    SandboxAppServiceIngressToJSONTyped,
} from './SandboxAppServiceIngress';
import type { SandboxAppServiceRuntime } from './SandboxAppServiceRuntime';
import {
    SandboxAppServiceRuntimeFromJSON,
    SandboxAppServiceRuntimeFromJSONTyped,
    SandboxAppServiceRuntimeToJSON,
    SandboxAppServiceRuntimeToJSONTyped,
} from './SandboxAppServiceRuntime';

/**
 * 
 * @export
 * @interface SandboxAppServiceView
 */
export interface SandboxAppServiceView {
    /**
     * Stable service ID. Must be a DNS label.
     * @type {string}
     * @memberof SandboxAppServiceView
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof SandboxAppServiceView
     */
    displayName?: string;
    /**
     * Public exposure routing port. Required for manual and cmd services. Omit for function services; Sandbox0 assigns the internal function service port.
     * @type {number}
     * @memberof SandboxAppServiceView
     */
    port?: number;
    /**
     * 
     * @type {SandboxAppServiceRuntime}
     * @memberof SandboxAppServiceView
     */
    runtime?: SandboxAppServiceRuntime;
    /**
     * 
     * @type {SandboxAppServiceIngress}
     * @memberof SandboxAppServiceView
     */
    ingress: SandboxAppServiceIngress;
    /**
     * 
     * @type {SandboxAppServiceHealth}
     * @memberof SandboxAppServiceView
     */
    healthCheck?: SandboxAppServiceHealth;
    /**
     * 
     * @type {boolean}
     * @memberof SandboxAppServiceView
     */
    publishable: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof SandboxAppServiceView
     */
    publishBlockers?: Array<string>;
    /**
     * Public HTTPS URL for this service when public exposure is enabled.
     * @type {string}
     * @memberof SandboxAppServiceView
     */
    publicUrl?: string;
}

/**
 * Check if a given object implements the SandboxAppServiceView interface.
 */
export function instanceOfSandboxAppServiceView(value: object): value is SandboxAppServiceView {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('ingress' in value) || value['ingress'] === undefined) return false;
    if (!('publishable' in value) || value['publishable'] === undefined) return false;
    return true;
}

export function SandboxAppServiceViewFromJSON(json: any): SandboxAppServiceView {
    return SandboxAppServiceViewFromJSONTyped(json, false);
}

export function SandboxAppServiceViewFromJSONTyped(json: any, ignoreDiscriminator: boolean): SandboxAppServiceView {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'displayName': json['display_name'] == null ? undefined : json['display_name'],
        'port': json['port'] == null ? undefined : json['port'],
        'runtime': json['runtime'] == null ? undefined : SandboxAppServiceRuntimeFromJSON(json['runtime']),
        'ingress': SandboxAppServiceIngressFromJSON(json['ingress']),
        'healthCheck': json['health_check'] == null ? undefined : SandboxAppServiceHealthFromJSON(json['health_check']),
        'publishable': json['publishable'],
        'publishBlockers': json['publish_blockers'] == null ? undefined : json['publish_blockers'],
        'publicUrl': json['public_url'] == null ? undefined : json['public_url'],
    };
}

export function SandboxAppServiceViewToJSON(json: any): SandboxAppServiceView {
    return SandboxAppServiceViewToJSONTyped(json, false);
}

export function SandboxAppServiceViewToJSONTyped(value?: SandboxAppServiceView | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'display_name': value['displayName'],
        'port': value['port'],
        'runtime': SandboxAppServiceRuntimeToJSON(value['runtime']),
        'ingress': SandboxAppServiceIngressToJSON(value['ingress']),
        'health_check': SandboxAppServiceHealthToJSON(value['healthCheck']),
        'publishable': value['publishable'],
        'publish_blockers': value['publishBlockers'],
        'public_url': value['publicUrl'],
    };
}

