/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by internal-gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SandboxSummary
 */
export interface SandboxSummary {
    /**
     * 
     * @type {string}
     * @memberof SandboxSummary
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof SandboxSummary
     */
    templateId: string;
    /**
     * 
     * @type {string}
     * @memberof SandboxSummary
     */
    status: SandboxSummaryStatusEnum;
    /**
     * 
     * @type {boolean}
     * @memberof SandboxSummary
     */
    paused: boolean;
    /**
     * Cluster where sandbox runs (multi-cluster only)
     * @type {string}
     * @memberof SandboxSummary
     */
    clusterId?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof SandboxSummary
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof SandboxSummary
     */
    expiresAt: Date;
}


/**
 * @export
 */
export const SandboxSummaryStatusEnum = {
    Starting: 'starting',
    Running: 'running',
    Failed: 'failed',
    Completed: 'completed'
} as const;
export type SandboxSummaryStatusEnum = typeof SandboxSummaryStatusEnum[keyof typeof SandboxSummaryStatusEnum];


/**
 * Check if a given object implements the SandboxSummary interface.
 */
export function instanceOfSandboxSummary(value: object): value is SandboxSummary {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('templateId' in value) || value['templateId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('paused' in value) || value['paused'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('expiresAt' in value) || value['expiresAt'] === undefined) return false;
    return true;
}

export function SandboxSummaryFromJSON(json: any): SandboxSummary {
    return SandboxSummaryFromJSONTyped(json, false);
}

export function SandboxSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): SandboxSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'templateId': json['template_id'],
        'status': json['status'],
        'paused': json['paused'],
        'clusterId': json['cluster_id'] == null ? undefined : json['cluster_id'],
        'createdAt': (new Date(json['created_at'])),
        'expiresAt': (new Date(json['expires_at'])),
    };
}

export function SandboxSummaryToJSON(json: any): SandboxSummary {
    return SandboxSummaryToJSONTyped(json, false);
}

export function SandboxSummaryToJSONTyped(value?: SandboxSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'template_id': value['templateId'],
        'status': value['status'],
        'paused': value['paused'],
        'cluster_id': value['clusterId'],
        'created_at': value['createdAt'].toISOString(),
        'expires_at': value['expiresAt'].toISOString(),
    };
}

