/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by internal-gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebhookConfig } from './WebhookConfig';
import {
    WebhookConfigFromJSON,
    WebhookConfigFromJSONTyped,
    WebhookConfigToJSON,
    WebhookConfigToJSONTyped,
} from './WebhookConfig';
import type { ExposedPortConfig } from './ExposedPortConfig';
import {
    ExposedPortConfigFromJSON,
    ExposedPortConfigFromJSONTyped,
    ExposedPortConfigToJSON,
    ExposedPortConfigToJSONTyped,
} from './ExposedPortConfig';
import type { TplSandboxNetworkPolicy } from './TplSandboxNetworkPolicy';
import {
    TplSandboxNetworkPolicyFromJSON,
    TplSandboxNetworkPolicyFromJSONTyped,
    TplSandboxNetworkPolicyToJSON,
    TplSandboxNetworkPolicyToJSONTyped,
} from './TplSandboxNetworkPolicy';

/**
 * 
 * @export
 * @interface SandboxConfig
 */
export interface SandboxConfig {
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof SandboxConfig
     */
    envVars?: { [key: string]: string; };
    /**
     * 
     * @type {number}
     * @memberof SandboxConfig
     */
    ttl?: number;
    /**
     * 
     * @type {number}
     * @memberof SandboxConfig
     */
    hardTtl?: number;
    /**
     * 
     * @type {TplSandboxNetworkPolicy}
     * @memberof SandboxConfig
     */
    network?: TplSandboxNetworkPolicy;
    /**
     * 
     * @type {WebhookConfig}
     * @memberof SandboxConfig
     */
    webhook?: WebhookConfig;
    /**
     * Sandbox-level resume gate for paused sandboxes. When false, any inbound request
     * (API or public exposure) must not auto resume the sandbox.
     * 
     * @type {boolean}
     * @memberof SandboxConfig
     */
    autoResume?: boolean;
    /**
     * 
     * @type {Array<ExposedPortConfig>}
     * @memberof SandboxConfig
     */
    exposedPorts?: Array<ExposedPortConfig>;
}

/**
 * Check if a given object implements the SandboxConfig interface.
 */
export function instanceOfSandboxConfig(value: object): value is SandboxConfig {
    return true;
}

export function SandboxConfigFromJSON(json: any): SandboxConfig {
    return SandboxConfigFromJSONTyped(json, false);
}

export function SandboxConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): SandboxConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'envVars': json['env_vars'] == null ? undefined : json['env_vars'],
        'ttl': json['ttl'] == null ? undefined : json['ttl'],
        'hardTtl': json['hard_ttl'] == null ? undefined : json['hard_ttl'],
        'network': json['network'] == null ? undefined : TplSandboxNetworkPolicyFromJSON(json['network']),
        'webhook': json['webhook'] == null ? undefined : WebhookConfigFromJSON(json['webhook']),
        'autoResume': json['auto_resume'] == null ? undefined : json['auto_resume'],
        'exposedPorts': json['exposed_ports'] == null ? undefined : ((json['exposed_ports'] as Array<any>).map(ExposedPortConfigFromJSON)),
    };
}

export function SandboxConfigToJSON(json: any): SandboxConfig {
    return SandboxConfigToJSONTyped(json, false);
}

export function SandboxConfigToJSONTyped(value?: SandboxConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'env_vars': value['envVars'],
        'ttl': value['ttl'],
        'hard_ttl': value['hardTtl'],
        'network': TplSandboxNetworkPolicyToJSON(value['network']),
        'webhook': WebhookConfigToJSON(value['webhook']),
        'auto_resume': value['autoResume'],
        'exposed_ports': value['exposedPorts'] == null ? undefined : ((value['exposedPorts'] as Array<any>).map(ExposedPortConfigToJSON)),
    };
}

