/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by internal-gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContextResourceUsage } from './ContextResourceUsage';
import {
    ContextResourceUsageFromJSON,
    ContextResourceUsageFromJSONTyped,
    ContextResourceUsageToJSON,
    ContextResourceUsageToJSONTyped,
} from './ContextResourceUsage';

/**
 * 
 * @export
 * @interface SandboxResourceUsage
 */
export interface SandboxResourceUsage {
    /**
     * 
     * @type {number}
     * @memberof SandboxResourceUsage
     */
    containerMemoryUsage?: number;
    /**
     * 
     * @type {number}
     * @memberof SandboxResourceUsage
     */
    containerMemoryLimit?: number;
    /**
     * 
     * @type {number}
     * @memberof SandboxResourceUsage
     */
    containerMemoryWorkingSet?: number;
    /**
     * 
     * @type {number}
     * @memberof SandboxResourceUsage
     */
    totalMemoryRss?: number;
    /**
     * 
     * @type {number}
     * @memberof SandboxResourceUsage
     */
    totalMemoryVms?: number;
    /**
     * 
     * @type {number}
     * @memberof SandboxResourceUsage
     */
    totalOpenFiles?: number;
    /**
     * 
     * @type {number}
     * @memberof SandboxResourceUsage
     */
    totalThreadCount?: number;
    /**
     * 
     * @type {number}
     * @memberof SandboxResourceUsage
     */
    totalIoReadBytes?: number;
    /**
     * 
     * @type {number}
     * @memberof SandboxResourceUsage
     */
    totalIoWriteBytes?: number;
    /**
     * 
     * @type {number}
     * @memberof SandboxResourceUsage
     */
    contextCount?: number;
    /**
     * 
     * @type {number}
     * @memberof SandboxResourceUsage
     */
    runningContextCount?: number;
    /**
     * 
     * @type {number}
     * @memberof SandboxResourceUsage
     */
    pausedContextCount?: number;
    /**
     * 
     * @type {Array<ContextResourceUsage>}
     * @memberof SandboxResourceUsage
     */
    contexts?: Array<ContextResourceUsage>;
}

/**
 * Check if a given object implements the SandboxResourceUsage interface.
 */
export function instanceOfSandboxResourceUsage(value: object): value is SandboxResourceUsage {
    return true;
}

export function SandboxResourceUsageFromJSON(json: any): SandboxResourceUsage {
    return SandboxResourceUsageFromJSONTyped(json, false);
}

export function SandboxResourceUsageFromJSONTyped(json: any, ignoreDiscriminator: boolean): SandboxResourceUsage {
    if (json == null) {
        return json;
    }
    return {
        
        'containerMemoryUsage': json['container_memory_usage'] == null ? undefined : json['container_memory_usage'],
        'containerMemoryLimit': json['container_memory_limit'] == null ? undefined : json['container_memory_limit'],
        'containerMemoryWorkingSet': json['container_memory_working_set'] == null ? undefined : json['container_memory_working_set'],
        'totalMemoryRss': json['total_memory_rss'] == null ? undefined : json['total_memory_rss'],
        'totalMemoryVms': json['total_memory_vms'] == null ? undefined : json['total_memory_vms'],
        'totalOpenFiles': json['total_open_files'] == null ? undefined : json['total_open_files'],
        'totalThreadCount': json['total_thread_count'] == null ? undefined : json['total_thread_count'],
        'totalIoReadBytes': json['total_io_read_bytes'] == null ? undefined : json['total_io_read_bytes'],
        'totalIoWriteBytes': json['total_io_write_bytes'] == null ? undefined : json['total_io_write_bytes'],
        'contextCount': json['context_count'] == null ? undefined : json['context_count'],
        'runningContextCount': json['running_context_count'] == null ? undefined : json['running_context_count'],
        'pausedContextCount': json['paused_context_count'] == null ? undefined : json['paused_context_count'],
        'contexts': json['contexts'] == null ? undefined : ((json['contexts'] as Array<any>).map(ContextResourceUsageFromJSON)),
    };
}

export function SandboxResourceUsageToJSON(json: any): SandboxResourceUsage {
    return SandboxResourceUsageToJSONTyped(json, false);
}

export function SandboxResourceUsageToJSONTyped(value?: SandboxResourceUsage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'container_memory_usage': value['containerMemoryUsage'],
        'container_memory_limit': value['containerMemoryLimit'],
        'container_memory_working_set': value['containerMemoryWorkingSet'],
        'total_memory_rss': value['totalMemoryRss'],
        'total_memory_vms': value['totalMemoryVms'],
        'total_open_files': value['totalOpenFiles'],
        'total_thread_count': value['totalThreadCount'],
        'total_io_read_bytes': value['totalIoReadBytes'],
        'total_io_write_bytes': value['totalIoWriteBytes'],
        'context_count': value['contextCount'],
        'running_context_count': value['runningContextCount'],
        'paused_context_count': value['pausedContextCount'],
        'contexts': value['contexts'] == null ? undefined : ((value['contexts'] as Array<any>).map(ContextResourceUsageToJSON)),
    };
}

