/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *
 * @export
 */
export const SandboxAuditActorKind = {
    Human: 'human',
    ApiKey: 'api_key',
    Service: 'service',
    SandboxWorkload: 'sandbox_workload',
    SshUser: 'ssh_user',
    ExposureCredential: 'exposure_credential',
    Anonymous: 'anonymous'
} as const;
export type SandboxAuditActorKind = typeof SandboxAuditActorKind[keyof typeof SandboxAuditActorKind];


export function instanceOfSandboxAuditActorKind(value: any): boolean {
    for (const key in SandboxAuditActorKind) {
        if (Object.prototype.hasOwnProperty.call(SandboxAuditActorKind, key)) {
            if (SandboxAuditActorKind[key as keyof typeof SandboxAuditActorKind] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SandboxAuditActorKindFromJSON(json: any): SandboxAuditActorKind {
    return SandboxAuditActorKindFromJSONTyped(json, false);
}

export function SandboxAuditActorKindFromJSONTyped(json: any, ignoreDiscriminator: boolean): SandboxAuditActorKind {
    return json as SandboxAuditActorKind;
}

export function SandboxAuditActorKindToJSON(value?: SandboxAuditActorKind | null): any {
    return value as any;
}

export function SandboxAuditActorKindToJSONTyped(value: any, ignoreDiscriminator: boolean): SandboxAuditActorKind {
    return value as SandboxAuditActorKind;
}
