/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SandboxAuditProducer
 */
export interface SandboxAuditProducer {
    /**
     * 
     * @type {string}
     * @memberof SandboxAuditProducer
     */
    service: string;
    /**
     * 
     * @type {string}
     * @memberof SandboxAuditProducer
     */
    instance?: string;
    /**
     * 
     * @type {number}
     * @memberof SandboxAuditProducer
     */
    sequence?: number;
}

/**
 * Check if a given object implements the SandboxAuditProducer interface.
 */
export function instanceOfSandboxAuditProducer(value: object): value is SandboxAuditProducer {
    if (!('service' in value) || value['service'] === undefined) return false;
    return true;
}

export function SandboxAuditProducerFromJSON(json: any): SandboxAuditProducer {
    return SandboxAuditProducerFromJSONTyped(json, false);
}

export function SandboxAuditProducerFromJSONTyped(json: any, ignoreDiscriminator: boolean): SandboxAuditProducer {
    if (json == null) {
        return json;
    }
    return {
        
        'service': json['service'],
        'instance': json['instance'] == null ? undefined : json['instance'],
        'sequence': json['sequence'] == null ? undefined : json['sequence'],
    };
}

export function SandboxAuditProducerToJSON(json: any): SandboxAuditProducer {
    return SandboxAuditProducerToJSONTyped(json, false);
}

export function SandboxAuditProducerToJSONTyped(value?: SandboxAuditProducer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'service': value['service'],
        'instance': value['instance'],
        'sequence': value['sequence'],
    };
}

