/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Capabilities } from './Capabilities';
import {
    CapabilitiesFromJSON,
    CapabilitiesFromJSONTyped,
    CapabilitiesToJSON,
    CapabilitiesToJSONTyped,
} from './Capabilities';
import type { AppArmorProfile } from './AppArmorProfile';
import {
    AppArmorProfileFromJSON,
    AppArmorProfileFromJSONTyped,
    AppArmorProfileToJSON,
    AppArmorProfileToJSONTyped,
} from './AppArmorProfile';
import type { SeccompProfile } from './SeccompProfile';
import {
    SeccompProfileFromJSON,
    SeccompProfileFromJSONTyped,
    SeccompProfileToJSON,
    SeccompProfileToJSONTyped,
} from './SeccompProfile';

/**
 *
 * @export
 * @interface SecurityContext
 */
export interface SecurityContext {
    /**
     *
     * @type {Capabilities}
     * @memberof SecurityContext
     */
    capabilities?: Capabilities;
    /**
     *
     * @type {boolean}
     * @memberof SecurityContext
     */
    privileged?: boolean;
    /**
     *
     * @type {number}
     * @memberof SecurityContext
     */
    runAsUser?: number;
    /**
     *
     * @type {number}
     * @memberof SecurityContext
     */
    runAsGroup?: number;
    /**
     *
     * @type {boolean}
     * @memberof SecurityContext
     */
    runAsNonRoot?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof SecurityContext
     */
    readOnlyRootFilesystem?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof SecurityContext
     */
    allowPrivilegeEscalation?: boolean;
    /**
     *
     * @type {SeccompProfile}
     * @memberof SecurityContext
     */
    seccompProfile?: SeccompProfile;
    /**
     *
     * @type {AppArmorProfile}
     * @memberof SecurityContext
     */
    appArmorProfile?: AppArmorProfile;
}

/**
 * Check if a given object implements the SecurityContext interface.
 */
export function instanceOfSecurityContext(value: object): value is SecurityContext {
    return true;
}

export function SecurityContextFromJSON(json: any): SecurityContext {
    return SecurityContextFromJSONTyped(json, false);
}

export function SecurityContextFromJSONTyped(json: any, ignoreDiscriminator: boolean): SecurityContext {
    if (json == null) {
        return json;
    }
    return {

        'capabilities': json['capabilities'] == null ? undefined : CapabilitiesFromJSON(json['capabilities']),
        'privileged': json['privileged'] == null ? undefined : json['privileged'],
        'runAsUser': json['runAsUser'] == null ? undefined : json['runAsUser'],
        'runAsGroup': json['runAsGroup'] == null ? undefined : json['runAsGroup'],
        'runAsNonRoot': json['runAsNonRoot'] == null ? undefined : json['runAsNonRoot'],
        'readOnlyRootFilesystem': json['readOnlyRootFilesystem'] == null ? undefined : json['readOnlyRootFilesystem'],
        'allowPrivilegeEscalation': json['allowPrivilegeEscalation'] == null ? undefined : json['allowPrivilegeEscalation'],
        'seccompProfile': json['seccompProfile'] == null ? undefined : SeccompProfileFromJSON(json['seccompProfile']),
        'appArmorProfile': json['appArmorProfile'] == null ? undefined : AppArmorProfileFromJSON(json['appArmorProfile']),
    };
}

export function SecurityContextToJSON(json: any): SecurityContext {
    return SecurityContextToJSONTyped(json, false);
}

export function SecurityContextToJSONTyped(value?: SecurityContext | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'capabilities': CapabilitiesToJSON(value['capabilities']),
        'privileged': value['privileged'],
        'runAsUser': value['runAsUser'],
        'runAsGroup': value['runAsGroup'],
        'runAsNonRoot': value['runAsNonRoot'],
        'readOnlyRootFilesystem': value['readOnlyRootFilesystem'],
        'allowPrivilegeEscalation': value['allowPrivilegeEscalation'],
        'seccompProfile': SeccompProfileToJSON(value['seccompProfile']),
        'appArmorProfile': AppArmorProfileToJSON(value['appArmorProfile']),
    };
}
