/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SnapshotRunSource
 */
export interface SnapshotRunSource {
    /**
     * 
     * @type {Array<string>}
     * @memberof SnapshotRunSource
     */
    snapshotIds?: Array<string>;
}

/**
 * Check if a given object implements the SnapshotRunSource interface.
 */
export function instanceOfSnapshotRunSource(value: object): value is SnapshotRunSource {
    return true;
}

export function SnapshotRunSourceFromJSON(json: any): SnapshotRunSource {
    return SnapshotRunSourceFromJSONTyped(json, false);
}

export function SnapshotRunSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): SnapshotRunSource {
    if (json == null) {
        return json;
    }
    return {
        
        'snapshotIds': json['snapshot_ids'] == null ? undefined : json['snapshot_ids'],
    };
}

export function SnapshotRunSourceToJSON(json: any): SnapshotRunSource {
    return SnapshotRunSourceToJSONTyped(json, false);
}

export function SnapshotRunSourceToJSONTyped(value?: SnapshotRunSource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'snapshot_ids': value['snapshotIds'],
    };
}

