/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FunctionDeployResult } from './FunctionDeployResult';
import {
    FunctionDeployResultFromJSON,
    FunctionDeployResultFromJSONTyped,
    FunctionDeployResultToJSON,
    FunctionDeployResultToJSONTyped,
} from './FunctionDeployResult';

/**
 * 
 * @export
 * @interface SuccessFunctionDeployResultResponse
 */
export interface SuccessFunctionDeployResultResponse {
    /**
     * 
     * @type {boolean}
     * @memberof SuccessFunctionDeployResultResponse
     */
    success: boolean;
    /**
     * 
     * @type {FunctionDeployResult}
     * @memberof SuccessFunctionDeployResultResponse
     */
    data?: FunctionDeployResult;
}

/**
 * Check if a given object implements the SuccessFunctionDeployResultResponse interface.
 */
export function instanceOfSuccessFunctionDeployResultResponse(value: object): value is SuccessFunctionDeployResultResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function SuccessFunctionDeployResultResponseFromJSON(json: any): SuccessFunctionDeployResultResponse {
    return SuccessFunctionDeployResultResponseFromJSONTyped(json, false);
}

export function SuccessFunctionDeployResultResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessFunctionDeployResultResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': json['data'] == null ? undefined : FunctionDeployResultFromJSON(json['data']),
    };
}

export function SuccessFunctionDeployResultResponseToJSON(json: any): SuccessFunctionDeployResultResponse {
    return SuccessFunctionDeployResultResponseToJSONTyped(json, false);
}

export function SuccessFunctionDeployResultResponseToJSONTyped(value?: SuccessFunctionDeployResultResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': FunctionDeployResultToJSON(value['data']),
    };
}

