/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by internal-gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SuccessSignaledResponseAllOfData } from './SuccessSignaledResponseAllOfData';
import {
    SuccessSignaledResponseAllOfDataFromJSON,
    SuccessSignaledResponseAllOfDataFromJSONTyped,
    SuccessSignaledResponseAllOfDataToJSON,
    SuccessSignaledResponseAllOfDataToJSONTyped,
} from './SuccessSignaledResponseAllOfData';

/**
 * 
 * @export
 * @interface SuccessSignaledResponse
 */
export interface SuccessSignaledResponse {
    /**
     * 
     * @type {boolean}
     * @memberof SuccessSignaledResponse
     */
    success: boolean;
    /**
     * 
     * @type {SuccessSignaledResponseAllOfData}
     * @memberof SuccessSignaledResponse
     */
    data?: SuccessSignaledResponseAllOfData;
}

/**
 * Check if a given object implements the SuccessSignaledResponse interface.
 */
export function instanceOfSuccessSignaledResponse(value: object): value is SuccessSignaledResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function SuccessSignaledResponseFromJSON(json: any): SuccessSignaledResponse {
    return SuccessSignaledResponseFromJSONTyped(json, false);
}

export function SuccessSignaledResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessSignaledResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': json['data'] == null ? undefined : SuccessSignaledResponseAllOfDataFromJSON(json['data']),
    };
}

export function SuccessSignaledResponseToJSON(json: any): SuccessSignaledResponse {
    return SuccessSignaledResponseToJSONTyped(json, false);
}

export function SuccessSignaledResponseToJSONTyped(value?: SuccessSignaledResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': SuccessSignaledResponseAllOfDataToJSON(value['data']),
    };
}

