/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by internal-gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PauseSandboxResponse } from './PauseSandboxResponse';
import {
    PauseSandboxResponseFromJSON,
    PauseSandboxResponseFromJSONTyped,
    PauseSandboxResponseToJSON,
    PauseSandboxResponseToJSONTyped,
} from './PauseSandboxResponse';

/**
 * 
 * @export
 * @interface SuccessPauseSandboxResponse
 */
export interface SuccessPauseSandboxResponse {
    /**
     * 
     * @type {boolean}
     * @memberof SuccessPauseSandboxResponse
     */
    success: boolean;
    /**
     * 
     * @type {PauseSandboxResponse}
     * @memberof SuccessPauseSandboxResponse
     */
    data?: PauseSandboxResponse;
}

/**
 * Check if a given object implements the SuccessPauseSandboxResponse interface.
 */
export function instanceOfSuccessPauseSandboxResponse(value: object): value is SuccessPauseSandboxResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function SuccessPauseSandboxResponseFromJSON(json: any): SuccessPauseSandboxResponse {
    return SuccessPauseSandboxResponseFromJSONTyped(json, false);
}

export function SuccessPauseSandboxResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessPauseSandboxResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': json['data'] == null ? undefined : PauseSandboxResponseFromJSON(json['data']),
    };
}

export function SuccessPauseSandboxResponseToJSON(json: any): SuccessPauseSandboxResponse {
    return SuccessPauseSandboxResponseToJSONTyped(json, false);
}

export function SuccessPauseSandboxResponseToJSONTyped(value?: SuccessPauseSandboxResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': PauseSandboxResponseToJSON(value['data']),
    };
}

