/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by internal-gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContextResponse } from './ContextResponse';
import {
    ContextResponseFromJSON,
    ContextResponseFromJSONTyped,
    ContextResponseToJSON,
    ContextResponseToJSONTyped,
} from './ContextResponse';

/**
 * 
 * @export
 * @interface SuccessContextListResponseAllOfData
 */
export interface SuccessContextListResponseAllOfData {
    /**
     * 
     * @type {Array<ContextResponse>}
     * @memberof SuccessContextListResponseAllOfData
     */
    contexts?: Array<ContextResponse>;
}

/**
 * Check if a given object implements the SuccessContextListResponseAllOfData interface.
 */
export function instanceOfSuccessContextListResponseAllOfData(value: object): value is SuccessContextListResponseAllOfData {
    return true;
}

export function SuccessContextListResponseAllOfDataFromJSON(json: any): SuccessContextListResponseAllOfData {
    return SuccessContextListResponseAllOfDataFromJSONTyped(json, false);
}

export function SuccessContextListResponseAllOfDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessContextListResponseAllOfData {
    if (json == null) {
        return json;
    }
    return {
        
        'contexts': json['contexts'] == null ? undefined : ((json['contexts'] as Array<any>).map(ContextResponseFromJSON)),
    };
}

export function SuccessContextListResponseAllOfDataToJSON(json: any): SuccessContextListResponseAllOfData {
    return SuccessContextListResponseAllOfDataToJSONTyped(json, false);
}

export function SuccessContextListResponseAllOfDataToJSONTyped(value?: SuccessContextListResponseAllOfData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'contexts': value['contexts'] == null ? undefined : ((value['contexts'] as Array<any>).map(ContextResponseToJSON)),
    };
}

