/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by internal-gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';

/**
 * 
 * @export
 * @interface SuccessUserResponse
 */
export interface SuccessUserResponse {
    /**
     * 
     * @type {boolean}
     * @memberof SuccessUserResponse
     */
    success: boolean;
    /**
     * 
     * @type {User}
     * @memberof SuccessUserResponse
     */
    data?: User;
}

/**
 * Check if a given object implements the SuccessUserResponse interface.
 */
export function instanceOfSuccessUserResponse(value: object): value is SuccessUserResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function SuccessUserResponseFromJSON(json: any): SuccessUserResponse {
    return SuccessUserResponseFromJSONTyped(json, false);
}

export function SuccessUserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessUserResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': json['data'] == null ? undefined : UserFromJSON(json['data']),
    };
}

export function SuccessUserResponseToJSON(json: any): SuccessUserResponse {
    return SuccessUserResponseToJSONTyped(json, false);
}

export function SuccessUserResponseToJSONTyped(value?: SuccessUserResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': UserToJSON(value['data']),
    };
}

