/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FunctionRuntimeStatus } from './FunctionRuntimeStatus';
import {
    FunctionRuntimeStatusFromJSON,
    FunctionRuntimeStatusFromJSONTyped,
    FunctionRuntimeStatusToJSON,
    FunctionRuntimeStatusToJSONTyped,
} from './FunctionRuntimeStatus';

/**
 * 
 * @export
 * @interface SuccessFunctionRuntimeResponseAllOfData
 */
export interface SuccessFunctionRuntimeResponseAllOfData {
    /**
     * 
     * @type {FunctionRuntimeStatus}
     * @memberof SuccessFunctionRuntimeResponseAllOfData
     */
    runtime: FunctionRuntimeStatus;
}

/**
 * Check if a given object implements the SuccessFunctionRuntimeResponseAllOfData interface.
 */
export function instanceOfSuccessFunctionRuntimeResponseAllOfData(value: object): value is SuccessFunctionRuntimeResponseAllOfData {
    if (!('runtime' in value) || value['runtime'] === undefined) return false;
    return true;
}

export function SuccessFunctionRuntimeResponseAllOfDataFromJSON(json: any): SuccessFunctionRuntimeResponseAllOfData {
    return SuccessFunctionRuntimeResponseAllOfDataFromJSONTyped(json, false);
}

export function SuccessFunctionRuntimeResponseAllOfDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessFunctionRuntimeResponseAllOfData {
    if (json == null) {
        return json;
    }
    return {
        
        'runtime': FunctionRuntimeStatusFromJSON(json['runtime']),
    };
}

export function SuccessFunctionRuntimeResponseAllOfDataToJSON(json: any): SuccessFunctionRuntimeResponseAllOfData {
    return SuccessFunctionRuntimeResponseAllOfDataToJSONTyped(json, false);
}

export function SuccessFunctionRuntimeResponseAllOfDataToJSONTyped(value?: SuccessFunctionRuntimeResponseAllOfData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'runtime': FunctionRuntimeStatusToJSON(value['runtime']),
    };
}

