/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SuccessPublicGatewayResponseAllOfData } from './SuccessPublicGatewayResponseAllOfData';
import {
    SuccessPublicGatewayResponseAllOfDataFromJSON,
    SuccessPublicGatewayResponseAllOfDataFromJSONTyped,
    SuccessPublicGatewayResponseAllOfDataToJSON,
    SuccessPublicGatewayResponseAllOfDataToJSONTyped,
} from './SuccessPublicGatewayResponseAllOfData';

/**
 * 
 * @export
 * @interface SuccessPublicGatewayResponse
 */
export interface SuccessPublicGatewayResponse {
    /**
     * 
     * @type {boolean}
     * @memberof SuccessPublicGatewayResponse
     */
    success: boolean;
    /**
     * 
     * @type {SuccessPublicGatewayResponseAllOfData}
     * @memberof SuccessPublicGatewayResponse
     */
    data?: SuccessPublicGatewayResponseAllOfData;
}

/**
 * Check if a given object implements the SuccessPublicGatewayResponse interface.
 */
export function instanceOfSuccessPublicGatewayResponse(value: object): value is SuccessPublicGatewayResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function SuccessPublicGatewayResponseFromJSON(json: any): SuccessPublicGatewayResponse {
    return SuccessPublicGatewayResponseFromJSONTyped(json, false);
}

export function SuccessPublicGatewayResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessPublicGatewayResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': json['data'] == null ? undefined : SuccessPublicGatewayResponseAllOfDataFromJSON(json['data']),
    };
}

export function SuccessPublicGatewayResponseToJSON(json: any): SuccessPublicGatewayResponse {
    return SuccessPublicGatewayResponseToJSONTyped(json, false);
}

export function SuccessPublicGatewayResponseToJSONTyped(value?: SuccessPublicGatewayResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': SuccessPublicGatewayResponseAllOfDataToJSON(value['data']),
    };
}

