/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SuccessFunctionListResponseAllOfData } from './SuccessFunctionListResponseAllOfData';
import {
    SuccessFunctionListResponseAllOfDataFromJSON,
    SuccessFunctionListResponseAllOfDataFromJSONTyped,
    SuccessFunctionListResponseAllOfDataToJSON,
    SuccessFunctionListResponseAllOfDataToJSONTyped,
} from './SuccessFunctionListResponseAllOfData';

/**
 * 
 * @export
 * @interface SuccessFunctionListResponse
 */
export interface SuccessFunctionListResponse {
    /**
     * 
     * @type {boolean}
     * @memberof SuccessFunctionListResponse
     */
    success: boolean;
    /**
     * 
     * @type {SuccessFunctionListResponseAllOfData}
     * @memberof SuccessFunctionListResponse
     */
    data?: SuccessFunctionListResponseAllOfData;
}

/**
 * Check if a given object implements the SuccessFunctionListResponse interface.
 */
export function instanceOfSuccessFunctionListResponse(value: object): value is SuccessFunctionListResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function SuccessFunctionListResponseFromJSON(json: any): SuccessFunctionListResponse {
    return SuccessFunctionListResponseFromJSONTyped(json, false);
}

export function SuccessFunctionListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessFunctionListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': json['data'] == null ? undefined : SuccessFunctionListResponseAllOfDataFromJSON(json['data']),
    };
}

export function SuccessFunctionListResponseToJSON(json: any): SuccessFunctionListResponse {
    return SuccessFunctionListResponseToJSONTyped(json, false);
}

export function SuccessFunctionListResponseToJSONTyped(value?: SuccessFunctionListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': SuccessFunctionListResponseAllOfDataToJSON(value['data']),
    };
}

