/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by internal-gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SuccessIdentityListResponseAllOfData } from './SuccessIdentityListResponseAllOfData';
import {
    SuccessIdentityListResponseAllOfDataFromJSON,
    SuccessIdentityListResponseAllOfDataFromJSONTyped,
    SuccessIdentityListResponseAllOfDataToJSON,
    SuccessIdentityListResponseAllOfDataToJSONTyped,
} from './SuccessIdentityListResponseAllOfData';

/**
 * 
 * @export
 * @interface SuccessIdentityListResponse
 */
export interface SuccessIdentityListResponse {
    /**
     * 
     * @type {boolean}
     * @memberof SuccessIdentityListResponse
     */
    success: boolean;
    /**
     * 
     * @type {SuccessIdentityListResponseAllOfData}
     * @memberof SuccessIdentityListResponse
     */
    data?: SuccessIdentityListResponseAllOfData;
}

/**
 * Check if a given object implements the SuccessIdentityListResponse interface.
 */
export function instanceOfSuccessIdentityListResponse(value: object): value is SuccessIdentityListResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function SuccessIdentityListResponseFromJSON(json: any): SuccessIdentityListResponse {
    return SuccessIdentityListResponseFromJSONTyped(json, false);
}

export function SuccessIdentityListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessIdentityListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': json['data'] == null ? undefined : SuccessIdentityListResponseAllOfDataFromJSON(json['data']),
    };
}

export function SuccessIdentityListResponseToJSON(json: any): SuccessIdentityListResponse {
    return SuccessIdentityListResponseToJSONTyped(json, false);
}

export function SuccessIdentityListResponseToJSONTyped(value?: SuccessIdentityListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': SuccessIdentityListResponseAllOfDataToJSON(value['data']),
    };
}

