/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by internal-gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SandboxSummary } from './SandboxSummary';
import {
    SandboxSummaryFromJSON,
    SandboxSummaryFromJSONTyped,
    SandboxSummaryToJSON,
    SandboxSummaryToJSONTyped,
} from './SandboxSummary';

/**
 * 
 * @export
 * @interface SuccessSandboxListResponseAllOfData
 */
export interface SuccessSandboxListResponseAllOfData {
    /**
     * 
     * @type {Array<SandboxSummary>}
     * @memberof SuccessSandboxListResponseAllOfData
     */
    sandboxes: Array<SandboxSummary>;
    /**
     * Total matching sandboxes
     * @type {number}
     * @memberof SuccessSandboxListResponseAllOfData
     */
    count: number;
    /**
     * More results available
     * @type {boolean}
     * @memberof SuccessSandboxListResponseAllOfData
     */
    hasMore: boolean;
}

/**
 * Check if a given object implements the SuccessSandboxListResponseAllOfData interface.
 */
export function instanceOfSuccessSandboxListResponseAllOfData(value: object): value is SuccessSandboxListResponseAllOfData {
    if (!('sandboxes' in value) || value['sandboxes'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
    return true;
}

export function SuccessSandboxListResponseAllOfDataFromJSON(json: any): SuccessSandboxListResponseAllOfData {
    return SuccessSandboxListResponseAllOfDataFromJSONTyped(json, false);
}

export function SuccessSandboxListResponseAllOfDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessSandboxListResponseAllOfData {
    if (json == null) {
        return json;
    }
    return {
        
        'sandboxes': ((json['sandboxes'] as Array<any>).map(SandboxSummaryFromJSON)),
        'count': json['count'],
        'hasMore': json['has_more'],
    };
}

export function SuccessSandboxListResponseAllOfDataToJSON(json: any): SuccessSandboxListResponseAllOfData {
    return SuccessSandboxListResponseAllOfDataToJSONTyped(json, false);
}

export function SuccessSandboxListResponseAllOfDataToJSONTyped(value?: SuccessSandboxListResponseAllOfData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sandboxes': ((value['sandboxes'] as Array<any>).map(SandboxSummaryToJSON)),
        'count': value['count'],
        'has_more': value['hasMore'],
    };
}

