/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CurrentAPIKeyResponse } from './CurrentAPIKeyResponse';
import {
    CurrentAPIKeyResponseFromJSON,
    CurrentAPIKeyResponseFromJSONTyped,
    CurrentAPIKeyResponseToJSON,
    CurrentAPIKeyResponseToJSONTyped,
} from './CurrentAPIKeyResponse';

/**
 * 
 * @export
 * @interface SuccessCurrentAPIKeyResponseAllOfData
 */
export interface SuccessCurrentAPIKeyResponseAllOfData {
    /**
     * 
     * @type {CurrentAPIKeyResponse}
     * @memberof SuccessCurrentAPIKeyResponseAllOfData
     */
    apiKey?: CurrentAPIKeyResponse;
}

/**
 * Check if a given object implements the SuccessCurrentAPIKeyResponseAllOfData interface.
 */
export function instanceOfSuccessCurrentAPIKeyResponseAllOfData(value: object): value is SuccessCurrentAPIKeyResponseAllOfData {
    return true;
}

export function SuccessCurrentAPIKeyResponseAllOfDataFromJSON(json: any): SuccessCurrentAPIKeyResponseAllOfData {
    return SuccessCurrentAPIKeyResponseAllOfDataFromJSONTyped(json, false);
}

export function SuccessCurrentAPIKeyResponseAllOfDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessCurrentAPIKeyResponseAllOfData {
    if (json == null) {
        return json;
    }
    return {
        
        'apiKey': json['api_key'] == null ? undefined : CurrentAPIKeyResponseFromJSON(json['api_key']),
    };
}

export function SuccessCurrentAPIKeyResponseAllOfDataToJSON(json: any): SuccessCurrentAPIKeyResponseAllOfData {
    return SuccessCurrentAPIKeyResponseAllOfDataToJSONTyped(json, false);
}

export function SuccessCurrentAPIKeyResponseAllOfDataToJSONTyped(value?: SuccessCurrentAPIKeyResponseAllOfData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'api_key': CurrentAPIKeyResponseToJSON(value['apiKey']),
    };
}

