/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SandboxObservabilityLogsResponse } from './SandboxObservabilityLogsResponse';
import {
    SandboxObservabilityLogsResponseFromJSON,
    SandboxObservabilityLogsResponseFromJSONTyped,
    SandboxObservabilityLogsResponseToJSON,
    SandboxObservabilityLogsResponseToJSONTyped,
} from './SandboxObservabilityLogsResponse';

/**
 * 
 * @export
 * @interface SuccessSandboxObservabilityLogsResponse
 */
export interface SuccessSandboxObservabilityLogsResponse {
    /**
     * 
     * @type {boolean}
     * @memberof SuccessSandboxObservabilityLogsResponse
     */
    success: boolean;
    /**
     * 
     * @type {SandboxObservabilityLogsResponse}
     * @memberof SuccessSandboxObservabilityLogsResponse
     */
    data?: SandboxObservabilityLogsResponse;
}

/**
 * Check if a given object implements the SuccessSandboxObservabilityLogsResponse interface.
 */
export function instanceOfSuccessSandboxObservabilityLogsResponse(value: object): value is SuccessSandboxObservabilityLogsResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function SuccessSandboxObservabilityLogsResponseFromJSON(json: any): SuccessSandboxObservabilityLogsResponse {
    return SuccessSandboxObservabilityLogsResponseFromJSONTyped(json, false);
}

export function SuccessSandboxObservabilityLogsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessSandboxObservabilityLogsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': json['data'] == null ? undefined : SandboxObservabilityLogsResponseFromJSON(json['data']),
    };
}

export function SuccessSandboxObservabilityLogsResponseToJSON(json: any): SuccessSandboxObservabilityLogsResponse {
    return SuccessSandboxObservabilityLogsResponseToJSONTyped(json, false);
}

export function SuccessSandboxObservabilityLogsResponseToJSONTyped(value?: SuccessSandboxObservabilityLogsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': SandboxObservabilityLogsResponseToJSON(value['data']),
    };
}

