/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProcessSession } from './ProcessSession';
import {
    ProcessSessionFromJSON,
    ProcessSessionFromJSONTyped,
    ProcessSessionToJSON,
    ProcessSessionToJSONTyped,
} from './ProcessSession';

/**
 * 
 * @export
 * @interface SuccessProcessSessionResponseAllOfData
 */
export interface SuccessProcessSessionResponseAllOfData {
    /**
     * 
     * @type {ProcessSession}
     * @memberof SuccessProcessSessionResponseAllOfData
     */
    process?: ProcessSession;
}

/**
 * Check if a given object implements the SuccessProcessSessionResponseAllOfData interface.
 */
export function instanceOfSuccessProcessSessionResponseAllOfData(value: object): value is SuccessProcessSessionResponseAllOfData {
    return true;
}

export function SuccessProcessSessionResponseAllOfDataFromJSON(json: any): SuccessProcessSessionResponseAllOfData {
    return SuccessProcessSessionResponseAllOfDataFromJSONTyped(json, false);
}

export function SuccessProcessSessionResponseAllOfDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessProcessSessionResponseAllOfData {
    if (json == null) {
        return json;
    }
    return {
        
        'process': json['process'] == null ? undefined : ProcessSessionFromJSON(json['process']),
    };
}

export function SuccessProcessSessionResponseAllOfDataToJSON(json: any): SuccessProcessSessionResponseAllOfData {
    return SuccessProcessSessionResponseAllOfDataToJSONTyped(json, false);
}

export function SuccessProcessSessionResponseAllOfDataToJSONTyped(value?: SuccessProcessSessionResponseAllOfData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'process': ProcessSessionToJSON(value['process']),
    };
}

