/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SuccessRunRevisionListResponseAllOfData } from './SuccessRunRevisionListResponseAllOfData';
import {
    SuccessRunRevisionListResponseAllOfDataFromJSON,
    SuccessRunRevisionListResponseAllOfDataFromJSONTyped,
    SuccessRunRevisionListResponseAllOfDataToJSON,
    SuccessRunRevisionListResponseAllOfDataToJSONTyped,
} from './SuccessRunRevisionListResponseAllOfData';

/**
 * 
 * @export
 * @interface SuccessRunRevisionListResponse
 */
export interface SuccessRunRevisionListResponse {
    /**
     * 
     * @type {boolean}
     * @memberof SuccessRunRevisionListResponse
     */
    success: boolean;
    /**
     * 
     * @type {SuccessRunRevisionListResponseAllOfData}
     * @memberof SuccessRunRevisionListResponse
     */
    data?: SuccessRunRevisionListResponseAllOfData;
}

/**
 * Check if a given object implements the SuccessRunRevisionListResponse interface.
 */
export function instanceOfSuccessRunRevisionListResponse(value: object): value is SuccessRunRevisionListResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function SuccessRunRevisionListResponseFromJSON(json: any): SuccessRunRevisionListResponse {
    return SuccessRunRevisionListResponseFromJSONTyped(json, false);
}

export function SuccessRunRevisionListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessRunRevisionListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': json['data'] == null ? undefined : SuccessRunRevisionListResponseAllOfDataFromJSON(json['data']),
    };
}

export function SuccessRunRevisionListResponseToJSON(json: any): SuccessRunRevisionListResponse {
    return SuccessRunRevisionListResponseToJSONTyped(json, false);
}

export function SuccessRunRevisionListResponseToJSONTyped(value?: SuccessRunRevisionListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': SuccessRunRevisionListResponseAllOfDataToJSON(value['data']),
    };
}

