/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Region } from './Region';
import {
    RegionFromJSON,
    RegionFromJSONTyped,
    RegionToJSON,
    RegionToJSONTyped,
} from './Region';

/**
 * 
 * @export
 * @interface SuccessRegionResponse
 */
export interface SuccessRegionResponse {
    /**
     * 
     * @type {boolean}
     * @memberof SuccessRegionResponse
     */
    success: boolean;
    /**
     * 
     * @type {Region}
     * @memberof SuccessRegionResponse
     */
    data?: Region;
}

/**
 * Check if a given object implements the SuccessRegionResponse interface.
 */
export function instanceOfSuccessRegionResponse(value: object): value is SuccessRegionResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function SuccessRegionResponseFromJSON(json: any): SuccessRegionResponse {
    return SuccessRegionResponseFromJSONTyped(json, false);
}

export function SuccessRegionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessRegionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': json['data'] == null ? undefined : RegionFromJSON(json['data']),
    };
}

export function SuccessRegionResponseToJSON(json: any): SuccessRegionResponse {
    return SuccessRegionResponseToJSONTyped(json, false);
}

export function SuccessRegionResponseToJSONTyped(value?: SuccessRegionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': RegionToJSON(value['data']),
    };
}

