/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by internal-gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RefreshResponse } from './RefreshResponse';
import {
    RefreshResponseFromJSON,
    RefreshResponseFromJSONTyped,
    RefreshResponseToJSON,
    RefreshResponseToJSONTyped,
} from './RefreshResponse';

/**
 * 
 * @export
 * @interface SuccessRefreshResponse
 */
export interface SuccessRefreshResponse {
    /**
     * 
     * @type {boolean}
     * @memberof SuccessRefreshResponse
     */
    success: boolean;
    /**
     * 
     * @type {RefreshResponse}
     * @memberof SuccessRefreshResponse
     */
    data?: RefreshResponse;
}

/**
 * Check if a given object implements the SuccessRefreshResponse interface.
 */
export function instanceOfSuccessRefreshResponse(value: object): value is SuccessRefreshResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function SuccessRefreshResponseFromJSON(json: any): SuccessRefreshResponse {
    return SuccessRefreshResponseFromJSONTyped(json, false);
}

export function SuccessRefreshResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessRefreshResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': json['data'] == null ? undefined : RefreshResponseFromJSON(json['data']),
    };
}

export function SuccessRefreshResponseToJSON(json: any): SuccessRefreshResponse {
    return SuccessRefreshResponseToJSONTyped(json, false);
}

export function SuccessRefreshResponseToJSONTyped(value?: SuccessRefreshResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': RefreshResponseToJSON(value['data']),
    };
}

