/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SandboxLogs } from './SandboxLogs';
import {
    SandboxLogsFromJSON,
    SandboxLogsFromJSONTyped,
    SandboxLogsToJSON,
    SandboxLogsToJSONTyped,
} from './SandboxLogs';

/**
 * 
 * @export
 * @interface SuccessSandboxLogsResponse
 */
export interface SuccessSandboxLogsResponse {
    /**
     * 
     * @type {boolean}
     * @memberof SuccessSandboxLogsResponse
     */
    success: boolean;
    /**
     * 
     * @type {SandboxLogs}
     * @memberof SuccessSandboxLogsResponse
     */
    data?: SandboxLogs;
}

/**
 * Check if a given object implements the SuccessSandboxLogsResponse interface.
 */
export function instanceOfSuccessSandboxLogsResponse(value: object): value is SuccessSandboxLogsResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function SuccessSandboxLogsResponseFromJSON(json: any): SuccessSandboxLogsResponse {
    return SuccessSandboxLogsResponseFromJSONTyped(json, false);
}

export function SuccessSandboxLogsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessSandboxLogsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': json['data'] == null ? undefined : SandboxLogsFromJSON(json['data']),
    };
}

export function SuccessSandboxLogsResponseToJSON(json: any): SuccessSandboxLogsResponse {
    return SuccessSandboxLogsResponseToJSONTyped(json, false);
}

export function SuccessSandboxLogsResponseToJSONTyped(value?: SuccessSandboxLogsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': SandboxLogsToJSON(value['data']),
    };
}

