/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by internal-gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContextResponse } from './ContextResponse';
import {
    ContextResponseFromJSON,
    ContextResponseFromJSONTyped,
    ContextResponseToJSON,
    ContextResponseToJSONTyped,
} from './ContextResponse';

/**
 * 
 * @export
 * @interface SuccessContextResponse
 */
export interface SuccessContextResponse {
    /**
     * 
     * @type {boolean}
     * @memberof SuccessContextResponse
     */
    success: boolean;
    /**
     * 
     * @type {ContextResponse}
     * @memberof SuccessContextResponse
     */
    data?: ContextResponse;
}

/**
 * Check if a given object implements the SuccessContextResponse interface.
 */
export function instanceOfSuccessContextResponse(value: object): value is SuccessContextResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function SuccessContextResponseFromJSON(json: any): SuccessContextResponse {
    return SuccessContextResponseFromJSONTyped(json, false);
}

export function SuccessContextResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessContextResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': json['data'] == null ? undefined : ContextResponseFromJSON(json['data']),
    };
}

export function SuccessContextResponseToJSON(json: any): SuccessContextResponse {
    return SuccessContextResponseToJSONTyped(json, false);
}

export function SuccessContextResponseToJSONTyped(value?: SuccessContextResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': ContextResponseToJSON(value['data']),
    };
}

