/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FunctionRevision } from './FunctionRevision';
import {
    FunctionRevisionFromJSON,
    FunctionRevisionFromJSONTyped,
    FunctionRevisionToJSON,
    FunctionRevisionToJSONTyped,
} from './FunctionRevision';

/**
 * 
 * @export
 * @interface SuccessFunctionRevisionListResponseAllOfData
 */
export interface SuccessFunctionRevisionListResponseAllOfData {
    /**
     * 
     * @type {Array<FunctionRevision>}
     * @memberof SuccessFunctionRevisionListResponseAllOfData
     */
    revisions: Array<FunctionRevision>;
}

/**
 * Check if a given object implements the SuccessFunctionRevisionListResponseAllOfData interface.
 */
export function instanceOfSuccessFunctionRevisionListResponseAllOfData(value: object): value is SuccessFunctionRevisionListResponseAllOfData {
    if (!('revisions' in value) || value['revisions'] === undefined) return false;
    return true;
}

export function SuccessFunctionRevisionListResponseAllOfDataFromJSON(json: any): SuccessFunctionRevisionListResponseAllOfData {
    return SuccessFunctionRevisionListResponseAllOfDataFromJSONTyped(json, false);
}

export function SuccessFunctionRevisionListResponseAllOfDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessFunctionRevisionListResponseAllOfData {
    if (json == null) {
        return json;
    }
    return {
        
        'revisions': ((json['revisions'] as Array<any>).map(FunctionRevisionFromJSON)),
    };
}

export function SuccessFunctionRevisionListResponseAllOfDataToJSON(json: any): SuccessFunctionRevisionListResponseAllOfData {
    return SuccessFunctionRevisionListResponseAllOfDataToJSONTyped(json, false);
}

export function SuccessFunctionRevisionListResponseAllOfDataToJSONTyped(value?: SuccessFunctionRevisionListResponseAllOfData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'revisions': ((value['revisions'] as Array<any>).map(FunctionRevisionToJSON)),
    };
}

