/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CredentialSourceMetadata } from './CredentialSourceMetadata';
import {
    CredentialSourceMetadataFromJSON,
    CredentialSourceMetadataFromJSONTyped,
    CredentialSourceMetadataToJSON,
    CredentialSourceMetadataToJSONTyped,
} from './CredentialSourceMetadata';

/**
 * 
 * @export
 * @interface SuccessCredentialSourceResponse
 */
export interface SuccessCredentialSourceResponse {
    /**
     * 
     * @type {boolean}
     * @memberof SuccessCredentialSourceResponse
     */
    success: boolean;
    /**
     * 
     * @type {CredentialSourceMetadata}
     * @memberof SuccessCredentialSourceResponse
     */
    data?: CredentialSourceMetadata;
}

/**
 * Check if a given object implements the SuccessCredentialSourceResponse interface.
 */
export function instanceOfSuccessCredentialSourceResponse(value: object): value is SuccessCredentialSourceResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function SuccessCredentialSourceResponseFromJSON(json: any): SuccessCredentialSourceResponse {
    return SuccessCredentialSourceResponseFromJSONTyped(json, false);
}

export function SuccessCredentialSourceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessCredentialSourceResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': json['data'] == null ? undefined : CredentialSourceMetadataFromJSON(json['data']),
    };
}

export function SuccessCredentialSourceResponseToJSON(json: any): SuccessCredentialSourceResponse {
    return SuccessCredentialSourceResponseToJSONTyped(json, false);
}

export function SuccessCredentialSourceResponseToJSONTyped(value?: SuccessCredentialSourceResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': CredentialSourceMetadataToJSON(value['data']),
    };
}

