/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SandboxRuntimeMetricsCatalogResponse } from './SandboxRuntimeMetricsCatalogResponse';
import {
    SandboxRuntimeMetricsCatalogResponseFromJSON,
    SandboxRuntimeMetricsCatalogResponseFromJSONTyped,
    SandboxRuntimeMetricsCatalogResponseToJSON,
    SandboxRuntimeMetricsCatalogResponseToJSONTyped,
} from './SandboxRuntimeMetricsCatalogResponse';

/**
 * 
 * @export
 * @interface SuccessSandboxRuntimeMetricsCatalogResponse
 */
export interface SuccessSandboxRuntimeMetricsCatalogResponse {
    /**
     * 
     * @type {boolean}
     * @memberof SuccessSandboxRuntimeMetricsCatalogResponse
     */
    success: boolean;
    /**
     * 
     * @type {SandboxRuntimeMetricsCatalogResponse}
     * @memberof SuccessSandboxRuntimeMetricsCatalogResponse
     */
    data?: SandboxRuntimeMetricsCatalogResponse;
}

/**
 * Check if a given object implements the SuccessSandboxRuntimeMetricsCatalogResponse interface.
 */
export function instanceOfSuccessSandboxRuntimeMetricsCatalogResponse(value: object): value is SuccessSandboxRuntimeMetricsCatalogResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function SuccessSandboxRuntimeMetricsCatalogResponseFromJSON(json: any): SuccessSandboxRuntimeMetricsCatalogResponse {
    return SuccessSandboxRuntimeMetricsCatalogResponseFromJSONTyped(json, false);
}

export function SuccessSandboxRuntimeMetricsCatalogResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessSandboxRuntimeMetricsCatalogResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': json['data'] == null ? undefined : SandboxRuntimeMetricsCatalogResponseFromJSON(json['data']),
    };
}

export function SuccessSandboxRuntimeMetricsCatalogResponseToJSON(json: any): SuccessSandboxRuntimeMetricsCatalogResponse {
    return SuccessSandboxRuntimeMetricsCatalogResponseToJSONTyped(json, false);
}

export function SuccessSandboxRuntimeMetricsCatalogResponseToJSONTyped(value?: SuccessSandboxRuntimeMetricsCatalogResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': SandboxRuntimeMetricsCatalogResponseToJSON(value['data']),
    };
}

