/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SuccessAcceptedResponseAllOfData
 */
export interface SuccessAcceptedResponseAllOfData {
    /**
     * 
     * @type {boolean}
     * @memberof SuccessAcceptedResponseAllOfData
     */
    accepted: boolean;
}

/**
 * Check if a given object implements the SuccessAcceptedResponseAllOfData interface.
 */
export function instanceOfSuccessAcceptedResponseAllOfData(value: object): value is SuccessAcceptedResponseAllOfData {
    if (!('accepted' in value) || value['accepted'] === undefined) return false;
    return true;
}

export function SuccessAcceptedResponseAllOfDataFromJSON(json: any): SuccessAcceptedResponseAllOfData {
    return SuccessAcceptedResponseAllOfDataFromJSONTyped(json, false);
}

export function SuccessAcceptedResponseAllOfDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessAcceptedResponseAllOfData {
    if (json == null) {
        return json;
    }
    return {
        
        'accepted': json['accepted'],
    };
}

export function SuccessAcceptedResponseAllOfDataToJSON(json: any): SuccessAcceptedResponseAllOfData {
    return SuccessAcceptedResponseAllOfDataToJSONTyped(json, false);
}

export function SuccessAcceptedResponseAllOfDataToJSONTyped(value?: SuccessAcceptedResponseAllOfData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accepted': value['accepted'],
    };
}

