/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SandboxAppServiceView } from './SandboxAppServiceView';
import {
    SandboxAppServiceViewFromJSON,
    SandboxAppServiceViewFromJSONTyped,
    SandboxAppServiceViewToJSON,
    SandboxAppServiceViewToJSONTyped,
} from './SandboxAppServiceView';

/**
 * 
 * @export
 * @interface SuccessSandboxServicesResponseAllOfData
 */
export interface SuccessSandboxServicesResponseAllOfData {
    /**
     * 
     * @type {string}
     * @memberof SuccessSandboxServicesResponseAllOfData
     */
    sandboxId: string;
    /**
     * 
     * @type {Array<SandboxAppServiceView>}
     * @memberof SuccessSandboxServicesResponseAllOfData
     */
    services: Array<SandboxAppServiceView>;
    /**
     * 
     * @type {string}
     * @memberof SuccessSandboxServicesResponseAllOfData
     */
    exposureDomain?: string;
}

/**
 * Check if a given object implements the SuccessSandboxServicesResponseAllOfData interface.
 */
export function instanceOfSuccessSandboxServicesResponseAllOfData(value: object): value is SuccessSandboxServicesResponseAllOfData {
    if (!('sandboxId' in value) || value['sandboxId'] === undefined) return false;
    if (!('services' in value) || value['services'] === undefined) return false;
    return true;
}

export function SuccessSandboxServicesResponseAllOfDataFromJSON(json: any): SuccessSandboxServicesResponseAllOfData {
    return SuccessSandboxServicesResponseAllOfDataFromJSONTyped(json, false);
}

export function SuccessSandboxServicesResponseAllOfDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessSandboxServicesResponseAllOfData {
    if (json == null) {
        return json;
    }
    return {
        
        'sandboxId': json['sandbox_id'],
        'services': ((json['services'] as Array<any>).map(SandboxAppServiceViewFromJSON)),
        'exposureDomain': json['exposure_domain'] == null ? undefined : json['exposure_domain'],
    };
}

export function SuccessSandboxServicesResponseAllOfDataToJSON(json: any): SuccessSandboxServicesResponseAllOfData {
    return SuccessSandboxServicesResponseAllOfDataToJSONTyped(json, false);
}

export function SuccessSandboxServicesResponseAllOfDataToJSONTyped(value?: SuccessSandboxServicesResponseAllOfData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sandbox_id': value['sandboxId'],
        'services': ((value['services'] as Array<any>).map(SandboxAppServiceViewToJSON)),
        'exposure_domain': value['exposureDomain'],
    };
}

