/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SuccessFunctionResponseAllOfData } from './SuccessFunctionResponseAllOfData';
import {
    SuccessFunctionResponseAllOfDataFromJSON,
    SuccessFunctionResponseAllOfDataFromJSONTyped,
    SuccessFunctionResponseAllOfDataToJSON,
    SuccessFunctionResponseAllOfDataToJSONTyped,
} from './SuccessFunctionResponseAllOfData';

/**
 * 
 * @export
 * @interface SuccessFunctionResponse
 */
export interface SuccessFunctionResponse {
    /**
     * 
     * @type {boolean}
     * @memberof SuccessFunctionResponse
     */
    success: boolean;
    /**
     * 
     * @type {SuccessFunctionResponseAllOfData}
     * @memberof SuccessFunctionResponse
     */
    data?: SuccessFunctionResponseAllOfData;
}

/**
 * Check if a given object implements the SuccessFunctionResponse interface.
 */
export function instanceOfSuccessFunctionResponse(value: object): value is SuccessFunctionResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function SuccessFunctionResponseFromJSON(json: any): SuccessFunctionResponse {
    return SuccessFunctionResponseFromJSONTyped(json, false);
}

export function SuccessFunctionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessFunctionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': json['data'] == null ? undefined : SuccessFunctionResponseAllOfDataFromJSON(json['data']),
    };
}

export function SuccessFunctionResponseToJSON(json: any): SuccessFunctionResponse {
    return SuccessFunctionResponseToJSONTyped(json, false);
}

export function SuccessFunctionResponseToJSONTyped(value?: SuccessFunctionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': SuccessFunctionResponseAllOfDataToJSON(value['data']),
    };
}

