/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SuccessFunctionRevisionResponseAllOfData } from './SuccessFunctionRevisionResponseAllOfData';
import {
    SuccessFunctionRevisionResponseAllOfDataFromJSON,
    SuccessFunctionRevisionResponseAllOfDataFromJSONTyped,
    SuccessFunctionRevisionResponseAllOfDataToJSON,
    SuccessFunctionRevisionResponseAllOfDataToJSONTyped,
} from './SuccessFunctionRevisionResponseAllOfData';

/**
 * 
 * @export
 * @interface SuccessFunctionRevisionResponse
 */
export interface SuccessFunctionRevisionResponse {
    /**
     * 
     * @type {boolean}
     * @memberof SuccessFunctionRevisionResponse
     */
    success: boolean;
    /**
     * 
     * @type {SuccessFunctionRevisionResponseAllOfData}
     * @memberof SuccessFunctionRevisionResponse
     */
    data?: SuccessFunctionRevisionResponseAllOfData;
}

/**
 * Check if a given object implements the SuccessFunctionRevisionResponse interface.
 */
export function instanceOfSuccessFunctionRevisionResponse(value: object): value is SuccessFunctionRevisionResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function SuccessFunctionRevisionResponseFromJSON(json: any): SuccessFunctionRevisionResponse {
    return SuccessFunctionRevisionResponseFromJSONTyped(json, false);
}

export function SuccessFunctionRevisionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessFunctionRevisionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': json['data'] == null ? undefined : SuccessFunctionRevisionResponseAllOfDataFromJSON(json['data']),
    };
}

export function SuccessFunctionRevisionResponseToJSON(json: any): SuccessFunctionRevisionResponse {
    return SuccessFunctionRevisionResponseToJSONTyped(json, false);
}

export function SuccessFunctionRevisionResponseToJSONTyped(value?: SuccessFunctionRevisionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': SuccessFunctionRevisionResponseAllOfDataToJSON(value['data']),
    };
}

