/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CloneVolumeFileResult } from './CloneVolumeFileResult';
import {
    CloneVolumeFileResultFromJSON,
    CloneVolumeFileResultFromJSONTyped,
    CloneVolumeFileResultToJSON,
    CloneVolumeFileResultToJSONTyped,
} from './CloneVolumeFileResult';

/**
 * 
 * @export
 * @interface SuccessCloneVolumeFilesResponseAllOfData
 */
export interface SuccessCloneVolumeFilesResponseAllOfData {
    /**
     * 
     * @type {Array<CloneVolumeFileResult>}
     * @memberof SuccessCloneVolumeFilesResponseAllOfData
     */
    entries?: Array<CloneVolumeFileResult>;
}

/**
 * Check if a given object implements the SuccessCloneVolumeFilesResponseAllOfData interface.
 */
export function instanceOfSuccessCloneVolumeFilesResponseAllOfData(value: object): value is SuccessCloneVolumeFilesResponseAllOfData {
    return true;
}

export function SuccessCloneVolumeFilesResponseAllOfDataFromJSON(json: any): SuccessCloneVolumeFilesResponseAllOfData {
    return SuccessCloneVolumeFilesResponseAllOfDataFromJSONTyped(json, false);
}

export function SuccessCloneVolumeFilesResponseAllOfDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessCloneVolumeFilesResponseAllOfData {
    if (json == null) {
        return json;
    }
    return {
        
        'entries': json['entries'] == null ? undefined : ((json['entries'] as Array<any>).map(CloneVolumeFileResultFromJSON)),
    };
}

export function SuccessCloneVolumeFilesResponseAllOfDataToJSON(json: any): SuccessCloneVolumeFilesResponseAllOfData {
    return SuccessCloneVolumeFilesResponseAllOfDataToJSONTyped(json, false);
}

export function SuccessCloneVolumeFilesResponseAllOfDataToJSONTyped(value?: SuccessCloneVolumeFilesResponseAllOfData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'entries': value['entries'] == null ? undefined : ((value['entries'] as Array<any>).map(CloneVolumeFileResultToJSON)),
    };
}

