/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SSHPublicKey } from './SSHPublicKey';
import {
    SSHPublicKeyFromJSON,
    SSHPublicKeyFromJSONTyped,
    SSHPublicKeyToJSON,
    SSHPublicKeyToJSONTyped,
} from './SSHPublicKey';

/**
 * 
 * @export
 * @interface SuccessSSHPublicKeyListResponseAllOfData
 */
export interface SuccessSSHPublicKeyListResponseAllOfData {
    /**
     * 
     * @type {Array<SSHPublicKey>}
     * @memberof SuccessSSHPublicKeyListResponseAllOfData
     */
    sshKeys?: Array<SSHPublicKey>;
}

/**
 * Check if a given object implements the SuccessSSHPublicKeyListResponseAllOfData interface.
 */
export function instanceOfSuccessSSHPublicKeyListResponseAllOfData(value: object): value is SuccessSSHPublicKeyListResponseAllOfData {
    return true;
}

export function SuccessSSHPublicKeyListResponseAllOfDataFromJSON(json: any): SuccessSSHPublicKeyListResponseAllOfData {
    return SuccessSSHPublicKeyListResponseAllOfDataFromJSONTyped(json, false);
}

export function SuccessSSHPublicKeyListResponseAllOfDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessSSHPublicKeyListResponseAllOfData {
    if (json == null) {
        return json;
    }
    return {
        
        'sshKeys': json['ssh_keys'] == null ? undefined : ((json['ssh_keys'] as Array<any>).map(SSHPublicKeyFromJSON)),
    };
}

export function SuccessSSHPublicKeyListResponseAllOfDataToJSON(json: any): SuccessSSHPublicKeyListResponseAllOfData {
    return SuccessSSHPublicKeyListResponseAllOfDataToJSONTyped(json, false);
}

export function SuccessSSHPublicKeyListResponseAllOfDataToJSONTyped(value?: SuccessSSHPublicKeyListResponseAllOfData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ssh_keys': value['sshKeys'] == null ? undefined : ((value['sshKeys'] as Array<any>).map(SSHPublicKeyToJSON)),
    };
}

