/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by internal-gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SuccessHealthResponseAllOfData
 */
export interface SuccessHealthResponseAllOfData {
    /**
     * 
     * @type {string}
     * @memberof SuccessHealthResponseAllOfData
     */
    status?: string;
    /**
     * 
     * @type {number}
     * @memberof SuccessHealthResponseAllOfData
     */
    timestamp?: number;
}

/**
 * Check if a given object implements the SuccessHealthResponseAllOfData interface.
 */
export function instanceOfSuccessHealthResponseAllOfData(value: object): value is SuccessHealthResponseAllOfData {
    return true;
}

export function SuccessHealthResponseAllOfDataFromJSON(json: any): SuccessHealthResponseAllOfData {
    return SuccessHealthResponseAllOfDataFromJSONTyped(json, false);
}

export function SuccessHealthResponseAllOfDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessHealthResponseAllOfData {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
    };
}

export function SuccessHealthResponseAllOfDataToJSON(json: any): SuccessHealthResponseAllOfData {
    return SuccessHealthResponseAllOfDataToJSONTyped(json, false);
}

export function SuccessHealthResponseAllOfDataToJSONTyped(value?: SuccessHealthResponseAllOfData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'timestamp': value['timestamp'],
    };
}

