/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExecutionSession } from './ExecutionSession';
import {
    ExecutionSessionFromJSON,
    ExecutionSessionFromJSONTyped,
    ExecutionSessionToJSON,
    ExecutionSessionToJSONTyped,
} from './ExecutionSession';

/**
 * 
 * @export
 * @interface SuccessExecutionSessionListResponseAllOfData
 */
export interface SuccessExecutionSessionListResponseAllOfData {
    /**
     * 
     * @type {Array<ExecutionSession>}
     * @memberof SuccessExecutionSessionListResponseAllOfData
     */
    sessions: Array<ExecutionSession>;
}

/**
 * Check if a given object implements the SuccessExecutionSessionListResponseAllOfData interface.
 */
export function instanceOfSuccessExecutionSessionListResponseAllOfData(value: object): value is SuccessExecutionSessionListResponseAllOfData {
    if (!('sessions' in value) || value['sessions'] === undefined) return false;
    return true;
}

export function SuccessExecutionSessionListResponseAllOfDataFromJSON(json: any): SuccessExecutionSessionListResponseAllOfData {
    return SuccessExecutionSessionListResponseAllOfDataFromJSONTyped(json, false);
}

export function SuccessExecutionSessionListResponseAllOfDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessExecutionSessionListResponseAllOfData {
    if (json == null) {
        return json;
    }
    return {
        
        'sessions': ((json['sessions'] as Array<any>).map(ExecutionSessionFromJSON)),
    };
}

export function SuccessExecutionSessionListResponseAllOfDataToJSON(json: any): SuccessExecutionSessionListResponseAllOfData {
    return SuccessExecutionSessionListResponseAllOfDataToJSONTyped(json, false);
}

export function SuccessExecutionSessionListResponseAllOfDataToJSONTyped(value?: SuccessExecutionSessionListResponseAllOfData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sessions': ((value['sessions'] as Array<any>).map(ExecutionSessionToJSON)),
    };
}

