/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SyncConflict
 */
export interface SyncConflict {
    /**
     * 
     * @type {string}
     * @memberof SyncConflict
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof SyncConflict
     */
    volumeId?: string;
    /**
     * 
     * @type {string}
     * @memberof SyncConflict
     */
    teamId?: string;
    /**
     * 
     * @type {string}
     * @memberof SyncConflict
     */
    replicaId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SyncConflict
     */
    path?: string;
    /**
     * 
     * @type {string}
     * @memberof SyncConflict
     */
    normalizedPath?: string;
    /**
     * 
     * @type {string}
     * @memberof SyncConflict
     */
    artifactPath?: string;
    /**
     * 
     * @type {string}
     * @memberof SyncConflict
     */
    incomingPath?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SyncConflict
     */
    incomingOldPath?: string | null;
    /**
     * 
     * @type {number}
     * @memberof SyncConflict
     */
    existingSeq?: number | null;
    /**
     * 
     * @type {string}
     * @memberof SyncConflict
     */
    reason?: string;
    /**
     * 
     * @type {string}
     * @memberof SyncConflict
     */
    status?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof SyncConflict
     */
    metadata?: { [key: string]: any; } | null;
    /**
     * 
     * @type {Date}
     * @memberof SyncConflict
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof SyncConflict
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the SyncConflict interface.
 */
export function instanceOfSyncConflict(value: object): value is SyncConflict {
    return true;
}

export function SyncConflictFromJSON(json: any): SyncConflict {
    return SyncConflictFromJSONTyped(json, false);
}

export function SyncConflictFromJSONTyped(json: any, ignoreDiscriminator: boolean): SyncConflict {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'volumeId': json['volume_id'] == null ? undefined : json['volume_id'],
        'teamId': json['team_id'] == null ? undefined : json['team_id'],
        'replicaId': json['replica_id'] == null ? undefined : json['replica_id'],
        'path': json['path'] == null ? undefined : json['path'],
        'normalizedPath': json['normalized_path'] == null ? undefined : json['normalized_path'],
        'artifactPath': json['artifact_path'] == null ? undefined : json['artifact_path'],
        'incomingPath': json['incoming_path'] == null ? undefined : json['incoming_path'],
        'incomingOldPath': json['incoming_old_path'] == null ? undefined : json['incoming_old_path'],
        'existingSeq': json['existing_seq'] == null ? undefined : json['existing_seq'],
        'reason': json['reason'] == null ? undefined : json['reason'],
        'status': json['status'] == null ? undefined : json['status'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
    };
}

export function SyncConflictToJSON(json: any): SyncConflict {
    return SyncConflictToJSONTyped(json, false);
}

export function SyncConflictToJSONTyped(value?: SyncConflict | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'volume_id': value['volumeId'],
        'team_id': value['teamId'],
        'replica_id': value['replicaId'],
        'path': value['path'],
        'normalized_path': value['normalizedPath'],
        'artifact_path': value['artifactPath'],
        'incoming_path': value['incomingPath'],
        'incoming_old_path': value['incomingOldPath'],
        'existing_seq': value['existingSeq'],
        'reason': value['reason'],
        'status': value['status'],
        'metadata': value['metadata'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

