/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TCPSocketAction
 */
export interface TCPSocketAction {
    /**
     * 
     * @type {number}
     * @memberof TCPSocketAction
     */
    port: number;
    /**
     * 
     * @type {string}
     * @memberof TCPSocketAction
     */
    host?: string;
}

/**
 * Check if a given object implements the TCPSocketAction interface.
 */
export function instanceOfTCPSocketAction(value: object): value is TCPSocketAction {
    if (!('port' in value) || value['port'] === undefined) return false;
    return true;
}

export function TCPSocketActionFromJSON(json: any): TCPSocketAction {
    return TCPSocketActionFromJSONTyped(json, false);
}

export function TCPSocketActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): TCPSocketAction {
    if (json == null) {
        return json;
    }
    return {
        
        'port': json['port'],
        'host': json['host'] == null ? undefined : json['host'],
    };
}

export function TCPSocketActionToJSON(json: any): TCPSocketAction {
    return TCPSocketActionToJSONTyped(json, false);
}

export function TCPSocketActionToJSONTyped(value?: TCPSocketAction | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'port': value['port'],
        'host': value['host'],
    };
}

