/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by internal-gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TeamMember
 */
export interface TeamMember {
    /**
     * 
     * @type {string}
     * @memberof TeamMember
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof TeamMember
     */
    teamId: string;
    /**
     * 
     * @type {string}
     * @memberof TeamMember
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof TeamMember
     */
    role: string;
    /**
     * 
     * @type {Date}
     * @memberof TeamMember
     */
    joinedAt: Date;
}

/**
 * Check if a given object implements the TeamMember interface.
 */
export function instanceOfTeamMember(value: object): value is TeamMember {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('teamId' in value) || value['teamId'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('joinedAt' in value) || value['joinedAt'] === undefined) return false;
    return true;
}

export function TeamMemberFromJSON(json: any): TeamMember {
    return TeamMemberFromJSONTyped(json, false);
}

export function TeamMemberFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamMember {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'teamId': json['team_id'],
        'userId': json['user_id'],
        'role': json['role'],
        'joinedAt': (new Date(json['joined_at'])),
    };
}

export function TeamMemberToJSON(json: any): TeamMember {
    return TeamMemberToJSONTyped(json, false);
}

export function TeamMemberToJSONTyped(value?: TeamMember | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'team_id': value['teamId'],
        'user_id': value['userId'],
        'role': value['role'],
        'joined_at': value['joinedAt'].toISOString(),
    };
}

