/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by internal-gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NetworkEgressPolicy } from './NetworkEgressPolicy';
import {
    NetworkEgressPolicyFromJSON,
    NetworkEgressPolicyFromJSONTyped,
    NetworkEgressPolicyToJSON,
    NetworkEgressPolicyToJSONTyped,
} from './NetworkEgressPolicy';

/**
 * 
 * @export
 * @interface TplSandboxNetworkPolicy
 */
export interface TplSandboxNetworkPolicy {
    /**
     * 
     * @type {string}
     * @memberof TplSandboxNetworkPolicy
     */
    mode: TplSandboxNetworkPolicyModeEnum;
    /**
     * 
     * @type {NetworkEgressPolicy}
     * @memberof TplSandboxNetworkPolicy
     */
    egress?: NetworkEgressPolicy;
}


/**
 * @export
 */
export const TplSandboxNetworkPolicyModeEnum = {
    AllowAll: 'allow-all',
    BlockAll: 'block-all'
} as const;
export type TplSandboxNetworkPolicyModeEnum = typeof TplSandboxNetworkPolicyModeEnum[keyof typeof TplSandboxNetworkPolicyModeEnum];


/**
 * Check if a given object implements the TplSandboxNetworkPolicy interface.
 */
export function instanceOfTplSandboxNetworkPolicy(value: object): value is TplSandboxNetworkPolicy {
    if (!('mode' in value) || value['mode'] === undefined) return false;
    return true;
}

export function TplSandboxNetworkPolicyFromJSON(json: any): TplSandboxNetworkPolicy {
    return TplSandboxNetworkPolicyFromJSONTyped(json, false);
}

export function TplSandboxNetworkPolicyFromJSONTyped(json: any, ignoreDiscriminator: boolean): TplSandboxNetworkPolicy {
    if (json == null) {
        return json;
    }
    return {
        
        'mode': json['mode'],
        'egress': json['egress'] == null ? undefined : NetworkEgressPolicyFromJSON(json['egress']),
    };
}

export function TplSandboxNetworkPolicyToJSON(json: any): TplSandboxNetworkPolicy {
    return TplSandboxNetworkPolicyToJSONTyped(json, false);
}

export function TplSandboxNetworkPolicyToJSONTyped(value?: TplSandboxNetworkPolicy | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mode': value['mode'],
        'egress': NetworkEgressPolicyToJSON(value['egress']),
    };
}

