/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateSyncReplicaCursorRequest
 */
export interface UpdateSyncReplicaCursorRequest {
    /**
     * 
     * @type {number}
     * @memberof UpdateSyncReplicaCursorRequest
     */
    lastAppliedSeq: number;
}

/**
 * Check if a given object implements the UpdateSyncReplicaCursorRequest interface.
 */
export function instanceOfUpdateSyncReplicaCursorRequest(value: object): value is UpdateSyncReplicaCursorRequest {
    if (!('lastAppliedSeq' in value) || value['lastAppliedSeq'] === undefined) return false;
    return true;
}

export function UpdateSyncReplicaCursorRequestFromJSON(json: any): UpdateSyncReplicaCursorRequest {
    return UpdateSyncReplicaCursorRequestFromJSONTyped(json, false);
}

export function UpdateSyncReplicaCursorRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateSyncReplicaCursorRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'lastAppliedSeq': json['last_applied_seq'],
    };
}

export function UpdateSyncReplicaCursorRequestToJSON(json: any): UpdateSyncReplicaCursorRequest {
    return UpdateSyncReplicaCursorRequestToJSONTyped(json, false);
}

export function UpdateSyncReplicaCursorRequestToJSONTyped(value?: UpdateSyncReplicaCursorRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'last_applied_seq': value['lastAppliedSeq'],
    };
}

