/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsageWindow
 */
export interface UsageWindow {
    /**
     * 
     * @type {string}
     * @memberof UsageWindow
     */
    windowId: string;
    /**
     * 
     * @type {string}
     * @memberof UsageWindow
     */
    regionId?: string;
    /**
     * 
     * @type {string}
     * @memberof UsageWindow
     */
    clusterId?: string;
    /**
     * 
     * @type {string}
     * @memberof UsageWindow
     */
    windowType: string;
    /**
     * 
     * @type {string}
     * @memberof UsageWindow
     */
    subjectType: string;
    /**
     * 
     * @type {string}
     * @memberof UsageWindow
     */
    subjectId: string;
    /**
     * 
     * @type {string}
     * @memberof UsageWindow
     */
    sandboxId?: string;
    /**
     * 
     * @type {Date}
     * @memberof UsageWindow
     */
    windowStart: Date;
    /**
     * 
     * @type {Date}
     * @memberof UsageWindow
     */
    windowEnd: Date;
    /**
     * 
     * @type {number}
     * @memberof UsageWindow
     */
    value: number;
    /**
     * 
     * @type {string}
     * @memberof UsageWindow
     */
    unit: string;
    /**
     * 
     * @type {Date}
     * @memberof UsageWindow
     */
    recordedAt: Date;
}

/**
 * Check if a given object implements the UsageWindow interface.
 */
export function instanceOfUsageWindow(value: object): value is UsageWindow {
    if (!('windowId' in value) || value['windowId'] === undefined) return false;
    if (!('windowType' in value) || value['windowType'] === undefined) return false;
    if (!('subjectType' in value) || value['subjectType'] === undefined) return false;
    if (!('subjectId' in value) || value['subjectId'] === undefined) return false;
    if (!('windowStart' in value) || value['windowStart'] === undefined) return false;
    if (!('windowEnd' in value) || value['windowEnd'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    if (!('unit' in value) || value['unit'] === undefined) return false;
    if (!('recordedAt' in value) || value['recordedAt'] === undefined) return false;
    return true;
}

export function UsageWindowFromJSON(json: any): UsageWindow {
    return UsageWindowFromJSONTyped(json, false);
}

export function UsageWindowFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsageWindow {
    if (json == null) {
        return json;
    }
    return {
        
        'windowId': json['window_id'],
        'regionId': json['region_id'] == null ? undefined : json['region_id'],
        'clusterId': json['cluster_id'] == null ? undefined : json['cluster_id'],
        'windowType': json['window_type'],
        'subjectType': json['subject_type'],
        'subjectId': json['subject_id'],
        'sandboxId': json['sandbox_id'] == null ? undefined : json['sandbox_id'],
        'windowStart': (new Date(json['window_start'])),
        'windowEnd': (new Date(json['window_end'])),
        'value': json['value'],
        'unit': json['unit'],
        'recordedAt': (new Date(json['recorded_at'])),
    };
}

export function UsageWindowToJSON(json: any): UsageWindow {
    return UsageWindowToJSONTyped(json, false);
}

export function UsageWindowToJSONTyped(value?: UsageWindow | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'window_id': value['windowId'],
        'region_id': value['regionId'],
        'cluster_id': value['clusterId'],
        'window_type': value['windowType'],
        'subject_type': value['subjectType'],
        'subject_id': value['subjectId'],
        'sandbox_id': value['sandboxId'],
        'window_start': value['windowStart'].toISOString(),
        'window_end': value['windowEnd'].toISOString(),
        'value': value['value'],
        'unit': value['unit'],
        'recorded_at': value['recordedAt'].toISOString(),
    };
}

