/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Snapshot } from './Snapshot';
import {
    SnapshotFromJSON,
    SnapshotFromJSONTyped,
    SnapshotToJSON,
    SnapshotToJSONTyped,
} from './Snapshot';

/**
 * 
 * @export
 * @interface VolumeSyncBootstrap
 */
export interface VolumeSyncBootstrap {
    /**
     * 
     * @type {Snapshot}
     * @memberof VolumeSyncBootstrap
     */
    snapshot: Snapshot;
    /**
     * 
     * @type {number}
     * @memberof VolumeSyncBootstrap
     */
    replayAfterSeq: number;
    /**
     * 
     * @type {string}
     * @memberof VolumeSyncBootstrap
     */
    archiveDownloadPath: string;
}

/**
 * Check if a given object implements the VolumeSyncBootstrap interface.
 */
export function instanceOfVolumeSyncBootstrap(value: object): value is VolumeSyncBootstrap {
    if (!('snapshot' in value) || value['snapshot'] === undefined) return false;
    if (!('replayAfterSeq' in value) || value['replayAfterSeq'] === undefined) return false;
    if (!('archiveDownloadPath' in value) || value['archiveDownloadPath'] === undefined) return false;
    return true;
}

export function VolumeSyncBootstrapFromJSON(json: any): VolumeSyncBootstrap {
    return VolumeSyncBootstrapFromJSONTyped(json, false);
}

export function VolumeSyncBootstrapFromJSONTyped(json: any, ignoreDiscriminator: boolean): VolumeSyncBootstrap {
    if (json == null) {
        return json;
    }
    return {
        
        'snapshot': SnapshotFromJSON(json['snapshot']),
        'replayAfterSeq': json['replay_after_seq'],
        'archiveDownloadPath': json['archive_download_path'],
    };
}

export function VolumeSyncBootstrapToJSON(json: any): VolumeSyncBootstrap {
    return VolumeSyncBootstrapToJSONTyped(json, false);
}

export function VolumeSyncBootstrapToJSONTyped(value?: VolumeSyncBootstrap | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'snapshot': SnapshotToJSON(value['snapshot']),
        'replay_after_seq': value['replayAfterSeq'],
        'archive_download_path': value['archiveDownloadPath'],
    };
}

