/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by internal-gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Access mode for sandbox volumes. Enforcement is scoped to storage-proxy instances. RWO allows read-write mounts on a single instance; ROX allows read-only mounts across instances; RWX allows read-write mounts across instances.
 * @export
 */
export const VolumeAccessMode = {
    Rwo: 'RWO',
    Rox: 'ROX',
    Rwx: 'RWX'
} as const;
export type VolumeAccessMode = typeof VolumeAccessMode[keyof typeof VolumeAccessMode];


export function instanceOfVolumeAccessMode(value: any): boolean {
    for (const key in VolumeAccessMode) {
        if (Object.prototype.hasOwnProperty.call(VolumeAccessMode, key)) {
            if (VolumeAccessMode[key as keyof typeof VolumeAccessMode] === value) {
                return true;
            }
        }
    }
    return false;
}

export function VolumeAccessModeFromJSON(json: any): VolumeAccessMode {
    return VolumeAccessModeFromJSONTyped(json, false);
}

export function VolumeAccessModeFromJSONTyped(json: any, ignoreDiscriminator: boolean): VolumeAccessMode {
    return json as VolumeAccessMode;
}

export function VolumeAccessModeToJSON(value?: VolumeAccessMode | null): any {
    return value as any;
}

export function VolumeAccessModeToJSONTyped(value: any, ignoreDiscriminator: boolean): VolumeAccessMode {
    return value as VolumeAccessMode;
}

