/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Storage backend for a SandboxVolume. s0fs is the default durable Sandbox0 volume backend. s3 mounts an existing S3-compatible prefix through the volume portal and supports mount-s3-like object projection.
 * @export
 */
export const VolumeBackend = {
    S0fs: 's0fs',
    S3: 's3'
} as const;
export type VolumeBackend = typeof VolumeBackend[keyof typeof VolumeBackend];


export function instanceOfVolumeBackend(value: any): boolean {
    for (const key in VolumeBackend) {
        if (Object.prototype.hasOwnProperty.call(VolumeBackend, key)) {
            if (VolumeBackend[key as keyof typeof VolumeBackend] === value) {
                return true;
            }
        }
    }
    return false;
}

export function VolumeBackendFromJSON(json: any): VolumeBackend {
    return VolumeBackendFromJSONTyped(json, false);
}

export function VolumeBackendFromJSONTyped(json: any, ignoreDiscriminator: boolean): VolumeBackend {
    return json as VolumeBackend;
}

export function VolumeBackendToJSON(value?: VolumeBackend | null): any {
    return value as any;
}

export function VolumeBackendToJSONTyped(value: any, ignoreDiscriminator: boolean): VolumeBackend {
    return value as VolumeBackend;
}

