/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VolumeSyncReseedRequiredDetails
 */
export interface VolumeSyncReseedRequiredDetails {
    /**
     * 
     * @type {string}
     * @memberof VolumeSyncReseedRequiredDetails
     */
    reason: VolumeSyncReseedRequiredDetailsReasonEnum;
    /**
     * 
     * @type {number}
     * @memberof VolumeSyncReseedRequiredDetails
     */
    retainedAfterSeq: number;
    /**
     * 
     * @type {number}
     * @memberof VolumeSyncReseedRequiredDetails
     */
    headSeq: number;
}


/**
 * @export
 */
export const VolumeSyncReseedRequiredDetailsReasonEnum = {
    ReseedRequired: 'reseed_required'
} as const;
export type VolumeSyncReseedRequiredDetailsReasonEnum = typeof VolumeSyncReseedRequiredDetailsReasonEnum[keyof typeof VolumeSyncReseedRequiredDetailsReasonEnum];


/**
 * Check if a given object implements the VolumeSyncReseedRequiredDetails interface.
 */
export function instanceOfVolumeSyncReseedRequiredDetails(value: object): value is VolumeSyncReseedRequiredDetails {
    if (!('reason' in value) || value['reason'] === undefined) return false;
    if (!('retainedAfterSeq' in value) || value['retainedAfterSeq'] === undefined) return false;
    if (!('headSeq' in value) || value['headSeq'] === undefined) return false;
    return true;
}

export function VolumeSyncReseedRequiredDetailsFromJSON(json: any): VolumeSyncReseedRequiredDetails {
    return VolumeSyncReseedRequiredDetailsFromJSONTyped(json, false);
}

export function VolumeSyncReseedRequiredDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): VolumeSyncReseedRequiredDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'reason': json['reason'],
        'retainedAfterSeq': json['retained_after_seq'],
        'headSeq': json['head_seq'],
    };
}

export function VolumeSyncReseedRequiredDetailsToJSON(json: any): VolumeSyncReseedRequiredDetails {
    return VolumeSyncReseedRequiredDetailsToJSONTyped(json, false);
}

export function VolumeSyncReseedRequiredDetailsToJSONTyped(value?: VolumeSyncReseedRequiredDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reason': value['reason'],
        'retained_after_seq': value['retainedAfterSeq'],
        'head_seq': value['headSeq'],
    };
}

