/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VolumeSyncReseedRequiredErrorEnvelopeAllOfError } from './VolumeSyncReseedRequiredErrorEnvelopeAllOfError';
import {
    VolumeSyncReseedRequiredErrorEnvelopeAllOfErrorFromJSON,
    VolumeSyncReseedRequiredErrorEnvelopeAllOfErrorFromJSONTyped,
    VolumeSyncReseedRequiredErrorEnvelopeAllOfErrorToJSON,
    VolumeSyncReseedRequiredErrorEnvelopeAllOfErrorToJSONTyped,
} from './VolumeSyncReseedRequiredErrorEnvelopeAllOfError';

/**
 * 
 * @export
 * @interface VolumeSyncReseedRequiredErrorEnvelope
 */
export interface VolumeSyncReseedRequiredErrorEnvelope {
    /**
     * 
     * @type {boolean}
     * @memberof VolumeSyncReseedRequiredErrorEnvelope
     */
    success: boolean;
    /**
     * 
     * @type {VolumeSyncReseedRequiredErrorEnvelopeAllOfError}
     * @memberof VolumeSyncReseedRequiredErrorEnvelope
     */
    error: VolumeSyncReseedRequiredErrorEnvelopeAllOfError;
}

/**
 * Check if a given object implements the VolumeSyncReseedRequiredErrorEnvelope interface.
 */
export function instanceOfVolumeSyncReseedRequiredErrorEnvelope(value: object): value is VolumeSyncReseedRequiredErrorEnvelope {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function VolumeSyncReseedRequiredErrorEnvelopeFromJSON(json: any): VolumeSyncReseedRequiredErrorEnvelope {
    return VolumeSyncReseedRequiredErrorEnvelopeFromJSONTyped(json, false);
}

export function VolumeSyncReseedRequiredErrorEnvelopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): VolumeSyncReseedRequiredErrorEnvelope {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'error': VolumeSyncReseedRequiredErrorEnvelopeAllOfErrorFromJSON(json['error']),
    };
}

export function VolumeSyncReseedRequiredErrorEnvelopeToJSON(json: any): VolumeSyncReseedRequiredErrorEnvelope {
    return VolumeSyncReseedRequiredErrorEnvelopeToJSONTyped(json, false);
}

export function VolumeSyncReseedRequiredErrorEnvelopeToJSONTyped(value?: VolumeSyncReseedRequiredErrorEnvelope | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'error': VolumeSyncReseedRequiredErrorEnvelopeAllOfErrorToJSON(value['error']),
    };
}

