/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorEnvelope,
  ObservabilityEventSource,
  SandboxObservabilityEventType,
  SandboxObservabilityLogStream,
  SandboxObservabilityOutcome,
  SandboxObservabilityWatchLine,
  SuccessSandboxObservabilityEventsResponse,
  SuccessSandboxObservabilityLogsResponse,
  SuccessSandboxObservabilityMetricsResponse,
} from '../models/index';
import {
    ErrorEnvelopeFromJSON,
    ErrorEnvelopeToJSON,
    ObservabilityEventSourceFromJSON,
    ObservabilityEventSourceToJSON,
    SandboxObservabilityEventTypeFromJSON,
    SandboxObservabilityEventTypeToJSON,
    SandboxObservabilityLogStreamFromJSON,
    SandboxObservabilityLogStreamToJSON,
    SandboxObservabilityOutcomeFromJSON,
    SandboxObservabilityOutcomeToJSON,
    SandboxObservabilityWatchLineFromJSON,
    SandboxObservabilityWatchLineToJSON,
    SuccessSandboxObservabilityEventsResponseFromJSON,
    SuccessSandboxObservabilityEventsResponseToJSON,
    SuccessSandboxObservabilityLogsResponseFromJSON,
    SuccessSandboxObservabilityLogsResponseToJSON,
    SuccessSandboxObservabilityMetricsResponseFromJSON,
    SuccessSandboxObservabilityMetricsResponseToJSON,
} from '../models/index';

export interface ApiV1SandboxesIdObservabilityEventsGetRequest {
    id: string;
    startTime?: Date;
    endTime?: Date;
    limit?: number;
    cursor?: string;
    watch?: boolean;
    source?: ObservabilityEventSource;
    eventType?: SandboxObservabilityEventType;
    outcome?: SandboxObservabilityOutcome;
}

export interface ApiV1SandboxesIdObservabilityLogsGetRequest {
    id: string;
    startTime?: Date;
    endTime?: Date;
    limit?: number;
    cursor?: string;
    watch?: boolean;
    contextId?: string;
    stream?: SandboxObservabilityLogStream;
}

export interface ApiV1SandboxesIdObservabilityMetricsGetRequest {
    id: string;
    startTime?: Date;
    endTime?: Date;
    limit?: number;
    cursor?: string;
    watch?: boolean;
    contextId?: string;
    name?: Array<string>;
    names?: string;
}

/**
 * 
 */
export class ObservabilityApi extends runtime.BaseAPI {

    /**
     * Queries the asynchronous per-sandbox observability projection for lifecycle, network audit, and runtime stats events. This endpoint does not expose backend SQL and reads tables that are separate from the metering usage ledger. 
     * Query historical sandbox observability events
     */
    async apiV1SandboxesIdObservabilityEventsGetRaw(requestParameters: ApiV1SandboxesIdObservabilityEventsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessSandboxObservabilityEventsResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1SandboxesIdObservabilityEventsGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['startTime'] != null) {
            queryParameters['start_time'] = (requestParameters['startTime'] as any).toISOString();
        }

        if (requestParameters['endTime'] != null) {
            queryParameters['end_time'] = (requestParameters['endTime'] as any).toISOString();
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['watch'] != null) {
            queryParameters['watch'] = requestParameters['watch'];
        }

        if (requestParameters['source'] != null) {
            queryParameters['source'] = requestParameters['source'];
        }

        if (requestParameters['eventType'] != null) {
            queryParameters['event_type'] = requestParameters['eventType'];
        }

        if (requestParameters['outcome'] != null) {
            queryParameters['outcome'] = requestParameters['outcome'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/sandboxes/{id}/observability/events`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessSandboxObservabilityEventsResponseFromJSON(jsonValue));
    }

    /**
     * Queries the asynchronous per-sandbox observability projection for lifecycle, network audit, and runtime stats events. This endpoint does not expose backend SQL and reads tables that are separate from the metering usage ledger. 
     * Query historical sandbox observability events
     */
    async apiV1SandboxesIdObservabilityEventsGet(requestParameters: ApiV1SandboxesIdObservabilityEventsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessSandboxObservabilityEventsResponse> {
        const response = await this.apiV1SandboxesIdObservabilityEventsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Queries the asynchronous per-sandbox log projection. This endpoint is for historical log lookup and is separate from live log streaming. 
     * Query historical sandbox logs
     */
    async apiV1SandboxesIdObservabilityLogsGetRaw(requestParameters: ApiV1SandboxesIdObservabilityLogsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessSandboxObservabilityLogsResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1SandboxesIdObservabilityLogsGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['startTime'] != null) {
            queryParameters['start_time'] = (requestParameters['startTime'] as any).toISOString();
        }

        if (requestParameters['endTime'] != null) {
            queryParameters['end_time'] = (requestParameters['endTime'] as any).toISOString();
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['watch'] != null) {
            queryParameters['watch'] = requestParameters['watch'];
        }

        if (requestParameters['contextId'] != null) {
            queryParameters['context_id'] = requestParameters['contextId'];
        }

        if (requestParameters['stream'] != null) {
            queryParameters['stream'] = requestParameters['stream'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/sandboxes/{id}/observability/logs`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessSandboxObservabilityLogsResponseFromJSON(jsonValue));
    }

    /**
     * Queries the asynchronous per-sandbox log projection. This endpoint is for historical log lookup and is separate from live log streaming. 
     * Query historical sandbox logs
     */
    async apiV1SandboxesIdObservabilityLogsGet(requestParameters: ApiV1SandboxesIdObservabilityLogsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessSandboxObservabilityLogsResponse> {
        const response = await this.apiV1SandboxesIdObservabilityLogsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Queries the asynchronous per-sandbox metric sample projection. This endpoint is separate from platform service metrics and metering usage truth. 
     * Query historical sandbox metric samples
     */
    async apiV1SandboxesIdObservabilityMetricsGetRaw(requestParameters: ApiV1SandboxesIdObservabilityMetricsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessSandboxObservabilityMetricsResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1SandboxesIdObservabilityMetricsGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['startTime'] != null) {
            queryParameters['start_time'] = (requestParameters['startTime'] as any).toISOString();
        }

        if (requestParameters['endTime'] != null) {
            queryParameters['end_time'] = (requestParameters['endTime'] as any).toISOString();
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['watch'] != null) {
            queryParameters['watch'] = requestParameters['watch'];
        }

        if (requestParameters['contextId'] != null) {
            queryParameters['context_id'] = requestParameters['contextId'];
        }

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        if (requestParameters['names'] != null) {
            queryParameters['names'] = requestParameters['names'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/sandboxes/{id}/observability/metrics`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessSandboxObservabilityMetricsResponseFromJSON(jsonValue));
    }

    /**
     * Queries the asynchronous per-sandbox metric sample projection. This endpoint is separate from platform service metrics and metering usage truth. 
     * Query historical sandbox metric samples
     */
    async apiV1SandboxesIdObservabilityMetricsGet(requestParameters: ApiV1SandboxesIdObservabilityMetricsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessSandboxObservabilityMetricsResponse> {
        const response = await this.apiV1SandboxesIdObservabilityMetricsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
