/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorEnvelope,
  RegistryCredentialsRequest,
  SuccessRegistryCredentialsResponse,
} from '../models/index';
import {
    ErrorEnvelopeFromJSON,
    ErrorEnvelopeToJSON,
    RegistryCredentialsRequestFromJSON,
    RegistryCredentialsRequestToJSON,
    SuccessRegistryCredentialsResponseFromJSON,
    SuccessRegistryCredentialsResponseToJSON,
} from '../models/index';

export interface ApiV1RegistryCredentialsPostRequest {
    registryCredentialsRequest?: RegistryCredentialsRequest;
}

/**
 * 
 */
export class RegistryApi extends runtime.BaseAPI {

    /**
     * Get registry credentials for uploads
     */
    async apiV1RegistryCredentialsPostRaw(requestParameters: ApiV1RegistryCredentialsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessRegistryCredentialsResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/registry/credentials`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RegistryCredentialsRequestToJSON(requestParameters['registryCredentialsRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessRegistryCredentialsResponseFromJSON(jsonValue));
    }

    /**
     * Get registry credentials for uploads
     */
    async apiV1RegistryCredentialsPost(requestParameters: ApiV1RegistryCredentialsPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessRegistryCredentialsResponse> {
        const response = await this.apiV1RegistryCredentialsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
