/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateSandboxVolumeRequest,
  ErrorEnvelope,
  ForkVolumeRequest,
  SuccessDeletedResponse,
  SuccessSandboxVolumeListResponse,
  SuccessSandboxVolumeResponse,
} from '../models/index';
import {
    CreateSandboxVolumeRequestFromJSON,
    CreateSandboxVolumeRequestToJSON,
    ErrorEnvelopeFromJSON,
    ErrorEnvelopeToJSON,
    ForkVolumeRequestFromJSON,
    ForkVolumeRequestToJSON,
    SuccessDeletedResponseFromJSON,
    SuccessDeletedResponseToJSON,
    SuccessSandboxVolumeListResponseFromJSON,
    SuccessSandboxVolumeListResponseToJSON,
    SuccessSandboxVolumeResponseFromJSON,
    SuccessSandboxVolumeResponseToJSON,
} from '../models/index';

export interface ApiV1SandboxvolumesIdDeleteRequest {
    id: string;
    force?: boolean;
}

export interface ApiV1SandboxvolumesIdForkPostRequest {
    id: string;
    forkVolumeRequest?: ForkVolumeRequest;
}

export interface ApiV1SandboxvolumesIdGetRequest {
    id: string;
}

export interface ApiV1SandboxvolumesPostRequest {
    createSandboxVolumeRequest: CreateSandboxVolumeRequest;
}

/**
 * 
 */
export class SandboxVolumesApi extends runtime.BaseAPI {

    /**
     * List sandbox volumes
     */
    async apiV1SandboxvolumesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessSandboxVolumeListResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/sandboxvolumes`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessSandboxVolumeListResponseFromJSON(jsonValue));
    }

    /**
     * List sandbox volumes
     */
    async apiV1SandboxvolumesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessSandboxVolumeListResponse> {
        const response = await this.apiV1SandboxvolumesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Delete sandbox volume
     */
    async apiV1SandboxvolumesIdDeleteRaw(requestParameters: ApiV1SandboxvolumesIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessDeletedResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1SandboxvolumesIdDelete().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['force'] != null) {
            queryParameters['force'] = requestParameters['force'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/sandboxvolumes/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessDeletedResponseFromJSON(jsonValue));
    }

    /**
     * Delete sandbox volume
     */
    async apiV1SandboxvolumesIdDelete(requestParameters: ApiV1SandboxvolumesIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessDeletedResponse> {
        const response = await this.apiV1SandboxvolumesIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Fork sandbox volume
     */
    async apiV1SandboxvolumesIdForkPostRaw(requestParameters: ApiV1SandboxvolumesIdForkPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessSandboxVolumeResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1SandboxvolumesIdForkPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/sandboxvolumes/{id}/fork`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ForkVolumeRequestToJSON(requestParameters['forkVolumeRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessSandboxVolumeResponseFromJSON(jsonValue));
    }

    /**
     * Fork sandbox volume
     */
    async apiV1SandboxvolumesIdForkPost(requestParameters: ApiV1SandboxvolumesIdForkPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessSandboxVolumeResponse> {
        const response = await this.apiV1SandboxvolumesIdForkPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get sandbox volume
     */
    async apiV1SandboxvolumesIdGetRaw(requestParameters: ApiV1SandboxvolumesIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessSandboxVolumeResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1SandboxvolumesIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/sandboxvolumes/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessSandboxVolumeResponseFromJSON(jsonValue));
    }

    /**
     * Get sandbox volume
     */
    async apiV1SandboxvolumesIdGet(requestParameters: ApiV1SandboxvolumesIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessSandboxVolumeResponse> {
        const response = await this.apiV1SandboxvolumesIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create sandbox volume
     */
    async apiV1SandboxvolumesPostRaw(requestParameters: ApiV1SandboxvolumesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessSandboxVolumeResponse>> {
        if (requestParameters['createSandboxVolumeRequest'] == null) {
            throw new runtime.RequiredError(
                'createSandboxVolumeRequest',
                'Required parameter "createSandboxVolumeRequest" was null or undefined when calling apiV1SandboxvolumesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/sandboxvolumes`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateSandboxVolumeRequestToJSON(requestParameters['createSandboxVolumeRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessSandboxVolumeResponseFromJSON(jsonValue));
    }

    /**
     * Create sandbox volume
     */
    async apiV1SandboxvolumesPost(requestParameters: ApiV1SandboxvolumesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessSandboxVolumeResponse> {
        const response = await this.apiV1SandboxvolumesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
