/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by internal-gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ClaimRequest,
  ErrorEnvelope,
  RefreshRequest,
  SandboxUpdateRequest,
  SuccessClaimResponse,
  SuccessExposedPortsResponse,
  SuccessMessageResponse,
  SuccessPauseSandboxResponse,
  SuccessRefreshResponse,
  SuccessResumeSandboxResponse,
  SuccessSandboxListResponse,
  SuccessSandboxNetworkPolicyResponse,
  SuccessSandboxResponse,
  SuccessSandboxStatusResponse,
  TplSandboxNetworkPolicy,
  UpdateExposedPortsRequest,
} from '../models/index';
import {
    ClaimRequestFromJSON,
    ClaimRequestToJSON,
    ErrorEnvelopeFromJSON,
    ErrorEnvelopeToJSON,
    RefreshRequestFromJSON,
    RefreshRequestToJSON,
    SandboxUpdateRequestFromJSON,
    SandboxUpdateRequestToJSON,
    SuccessClaimResponseFromJSON,
    SuccessClaimResponseToJSON,
    SuccessExposedPortsResponseFromJSON,
    SuccessExposedPortsResponseToJSON,
    SuccessMessageResponseFromJSON,
    SuccessMessageResponseToJSON,
    SuccessPauseSandboxResponseFromJSON,
    SuccessPauseSandboxResponseToJSON,
    SuccessRefreshResponseFromJSON,
    SuccessRefreshResponseToJSON,
    SuccessResumeSandboxResponseFromJSON,
    SuccessResumeSandboxResponseToJSON,
    SuccessSandboxListResponseFromJSON,
    SuccessSandboxListResponseToJSON,
    SuccessSandboxNetworkPolicyResponseFromJSON,
    SuccessSandboxNetworkPolicyResponseToJSON,
    SuccessSandboxResponseFromJSON,
    SuccessSandboxResponseToJSON,
    SuccessSandboxStatusResponseFromJSON,
    SuccessSandboxStatusResponseToJSON,
    TplSandboxNetworkPolicyFromJSON,
    TplSandboxNetworkPolicyToJSON,
    UpdateExposedPortsRequestFromJSON,
    UpdateExposedPortsRequestToJSON,
} from '../models/index';

export interface ApiV1SandboxesGetRequest {
    status?: ApiV1SandboxesGetStatusEnum;
    templateId?: string;
    paused?: boolean;
    limit?: number;
    offset?: number;
}

export interface ApiV1SandboxesIdDeleteRequest {
    id: string;
}

export interface ApiV1SandboxesIdExposedPortsDeleteRequest {
    id: string;
}

export interface ApiV1SandboxesIdExposedPortsGetRequest {
    id: string;
}

export interface ApiV1SandboxesIdExposedPortsPortDeleteRequest {
    id: string;
    port: number;
}

export interface ApiV1SandboxesIdExposedPortsPutRequest {
    id: string;
    updateExposedPortsRequest: UpdateExposedPortsRequest;
}

export interface ApiV1SandboxesIdGetRequest {
    id: string;
}

export interface ApiV1SandboxesIdNetworkGetRequest {
    id: string;
}

export interface ApiV1SandboxesIdNetworkPutRequest {
    id: string;
    tplSandboxNetworkPolicy: TplSandboxNetworkPolicy;
}

export interface ApiV1SandboxesIdPausePostRequest {
    id: string;
}

export interface ApiV1SandboxesIdPutRequest {
    id: string;
    sandboxUpdateRequest: SandboxUpdateRequest;
}

export interface ApiV1SandboxesIdRefreshPostRequest {
    id: string;
    refreshRequest?: RefreshRequest;
}

export interface ApiV1SandboxesIdResumePostRequest {
    id: string;
}

export interface ApiV1SandboxesIdStatusGetRequest {
    id: string;
}

export interface ApiV1SandboxesPostRequest {
    claimRequest: ClaimRequest;
}

/**
 * 
 */
export class SandboxesApi extends runtime.BaseAPI {

    /**
     * List all sandboxes for the authenticated team. In multi-cluster mode, this endpoint aggregates results from all enabled clusters.
     * List sandboxes
     */
    async apiV1SandboxesGetRaw(requestParameters: ApiV1SandboxesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessSandboxListResponse>> {
        const queryParameters: any = {};

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['templateId'] != null) {
            queryParameters['template_id'] = requestParameters['templateId'];
        }

        if (requestParameters['paused'] != null) {
            queryParameters['paused'] = requestParameters['paused'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/sandboxes`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessSandboxListResponseFromJSON(jsonValue));
    }

    /**
     * List all sandboxes for the authenticated team. In multi-cluster mode, this endpoint aggregates results from all enabled clusters.
     * List sandboxes
     */
    async apiV1SandboxesGet(requestParameters: ApiV1SandboxesGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessSandboxListResponse> {
        const response = await this.apiV1SandboxesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete (terminate) a sandbox
     */
    async apiV1SandboxesIdDeleteRaw(requestParameters: ApiV1SandboxesIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessMessageResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1SandboxesIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/sandboxes/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessMessageResponseFromJSON(jsonValue));
    }

    /**
     * Delete (terminate) a sandbox
     */
    async apiV1SandboxesIdDelete(requestParameters: ApiV1SandboxesIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessMessageResponse> {
        const response = await this.apiV1SandboxesIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Clear all exposed ports
     */
    async apiV1SandboxesIdExposedPortsDeleteRaw(requestParameters: ApiV1SandboxesIdExposedPortsDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessExposedPortsResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1SandboxesIdExposedPortsDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/sandboxes/{id}/exposed-ports`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessExposedPortsResponseFromJSON(jsonValue));
    }

    /**
     * Clear all exposed ports
     */
    async apiV1SandboxesIdExposedPortsDelete(requestParameters: ApiV1SandboxesIdExposedPortsDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessExposedPortsResponse> {
        const response = await this.apiV1SandboxesIdExposedPortsDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get sandbox exposed ports
     */
    async apiV1SandboxesIdExposedPortsGetRaw(requestParameters: ApiV1SandboxesIdExposedPortsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessExposedPortsResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1SandboxesIdExposedPortsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/sandboxes/{id}/exposed-ports`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessExposedPortsResponseFromJSON(jsonValue));
    }

    /**
     * Get sandbox exposed ports
     */
    async apiV1SandboxesIdExposedPortsGet(requestParameters: ApiV1SandboxesIdExposedPortsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessExposedPortsResponse> {
        const response = await this.apiV1SandboxesIdExposedPortsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Remove a specific exposed port
     */
    async apiV1SandboxesIdExposedPortsPortDeleteRaw(requestParameters: ApiV1SandboxesIdExposedPortsPortDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessExposedPortsResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1SandboxesIdExposedPortsPortDelete().'
            );
        }

        if (requestParameters['port'] == null) {
            throw new runtime.RequiredError(
                'port',
                'Required parameter "port" was null or undefined when calling apiV1SandboxesIdExposedPortsPortDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/sandboxes/{id}/exposed-ports/{port}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"port"}}`, encodeURIComponent(String(requestParameters['port'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessExposedPortsResponseFromJSON(jsonValue));
    }

    /**
     * Remove a specific exposed port
     */
    async apiV1SandboxesIdExposedPortsPortDelete(requestParameters: ApiV1SandboxesIdExposedPortsPortDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessExposedPortsResponse> {
        const response = await this.apiV1SandboxesIdExposedPortsPortDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Replaces all exposed ports for the sandbox. Used to control which ports are publicly accessible via the exposure domain. 
     * Update sandbox exposed ports
     */
    async apiV1SandboxesIdExposedPortsPutRaw(requestParameters: ApiV1SandboxesIdExposedPortsPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessExposedPortsResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1SandboxesIdExposedPortsPut().'
            );
        }

        if (requestParameters['updateExposedPortsRequest'] == null) {
            throw new runtime.RequiredError(
                'updateExposedPortsRequest',
                'Required parameter "updateExposedPortsRequest" was null or undefined when calling apiV1SandboxesIdExposedPortsPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/sandboxes/{id}/exposed-ports`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateExposedPortsRequestToJSON(requestParameters['updateExposedPortsRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessExposedPortsResponseFromJSON(jsonValue));
    }

    /**
     * Replaces all exposed ports for the sandbox. Used to control which ports are publicly accessible via the exposure domain. 
     * Update sandbox exposed ports
     */
    async apiV1SandboxesIdExposedPortsPut(requestParameters: ApiV1SandboxesIdExposedPortsPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessExposedPortsResponse> {
        const response = await this.apiV1SandboxesIdExposedPortsPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get sandbox by ID
     */
    async apiV1SandboxesIdGetRaw(requestParameters: ApiV1SandboxesIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessSandboxResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1SandboxesIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/sandboxes/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessSandboxResponseFromJSON(jsonValue));
    }

    /**
     * Get sandbox by ID
     */
    async apiV1SandboxesIdGet(requestParameters: ApiV1SandboxesIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessSandboxResponse> {
        const response = await this.apiV1SandboxesIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get sandbox network policy
     */
    async apiV1SandboxesIdNetworkGetRaw(requestParameters: ApiV1SandboxesIdNetworkGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessSandboxNetworkPolicyResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1SandboxesIdNetworkGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/sandboxes/{id}/network`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessSandboxNetworkPolicyResponseFromJSON(jsonValue));
    }

    /**
     * Get sandbox network policy
     */
    async apiV1SandboxesIdNetworkGet(requestParameters: ApiV1SandboxesIdNetworkGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessSandboxNetworkPolicyResponse> {
        const response = await this.apiV1SandboxesIdNetworkGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update sandbox network policy
     */
    async apiV1SandboxesIdNetworkPutRaw(requestParameters: ApiV1SandboxesIdNetworkPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessSandboxNetworkPolicyResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1SandboxesIdNetworkPut().'
            );
        }

        if (requestParameters['tplSandboxNetworkPolicy'] == null) {
            throw new runtime.RequiredError(
                'tplSandboxNetworkPolicy',
                'Required parameter "tplSandboxNetworkPolicy" was null or undefined when calling apiV1SandboxesIdNetworkPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/sandboxes/{id}/network`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: TplSandboxNetworkPolicyToJSON(requestParameters['tplSandboxNetworkPolicy']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessSandboxNetworkPolicyResponseFromJSON(jsonValue));
    }

    /**
     * Update sandbox network policy
     */
    async apiV1SandboxesIdNetworkPut(requestParameters: ApiV1SandboxesIdNetworkPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessSandboxNetworkPolicyResponse> {
        const response = await this.apiV1SandboxesIdNetworkPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Pause a sandbox
     */
    async apiV1SandboxesIdPausePostRaw(requestParameters: ApiV1SandboxesIdPausePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessPauseSandboxResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1SandboxesIdPausePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/sandboxes/{id}/pause`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessPauseSandboxResponseFromJSON(jsonValue));
    }

    /**
     * Pause a sandbox
     */
    async apiV1SandboxesIdPausePost(requestParameters: ApiV1SandboxesIdPausePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessPauseSandboxResponse> {
        const response = await this.apiV1SandboxesIdPausePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update sandbox configuration
     */
    async apiV1SandboxesIdPutRaw(requestParameters: ApiV1SandboxesIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessSandboxResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1SandboxesIdPut().'
            );
        }

        if (requestParameters['sandboxUpdateRequest'] == null) {
            throw new runtime.RequiredError(
                'sandboxUpdateRequest',
                'Required parameter "sandboxUpdateRequest" was null or undefined when calling apiV1SandboxesIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/sandboxes/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SandboxUpdateRequestToJSON(requestParameters['sandboxUpdateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessSandboxResponseFromJSON(jsonValue));
    }

    /**
     * Update sandbox configuration
     */
    async apiV1SandboxesIdPut(requestParameters: ApiV1SandboxesIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessSandboxResponse> {
        const response = await this.apiV1SandboxesIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Refresh sandbox TTL
     */
    async apiV1SandboxesIdRefreshPostRaw(requestParameters: ApiV1SandboxesIdRefreshPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessRefreshResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1SandboxesIdRefreshPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/sandboxes/{id}/refresh`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RefreshRequestToJSON(requestParameters['refreshRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessRefreshResponseFromJSON(jsonValue));
    }

    /**
     * Refresh sandbox TTL
     */
    async apiV1SandboxesIdRefreshPost(requestParameters: ApiV1SandboxesIdRefreshPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessRefreshResponse> {
        const response = await this.apiV1SandboxesIdRefreshPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Resume a sandbox
     */
    async apiV1SandboxesIdResumePostRaw(requestParameters: ApiV1SandboxesIdResumePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessResumeSandboxResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1SandboxesIdResumePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/sandboxes/{id}/resume`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessResumeSandboxResponseFromJSON(jsonValue));
    }

    /**
     * Resume a sandbox
     */
    async apiV1SandboxesIdResumePost(requestParameters: ApiV1SandboxesIdResumePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessResumeSandboxResponse> {
        const response = await this.apiV1SandboxesIdResumePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get sandbox status
     */
    async apiV1SandboxesIdStatusGetRaw(requestParameters: ApiV1SandboxesIdStatusGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessSandboxStatusResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1SandboxesIdStatusGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/sandboxes/{id}/status`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessSandboxStatusResponseFromJSON(jsonValue));
    }

    /**
     * Get sandbox status
     */
    async apiV1SandboxesIdStatusGet(requestParameters: ApiV1SandboxesIdStatusGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessSandboxStatusResponse> {
        const response = await this.apiV1SandboxesIdStatusGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create (claim) a sandbox
     */
    async apiV1SandboxesPostRaw(requestParameters: ApiV1SandboxesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessClaimResponse>> {
        if (requestParameters['claimRequest'] == null) {
            throw new runtime.RequiredError(
                'claimRequest',
                'Required parameter "claimRequest" was null or undefined when calling apiV1SandboxesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/sandboxes`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ClaimRequestToJSON(requestParameters['claimRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessClaimResponseFromJSON(jsonValue));
    }

    /**
     * Create (claim) a sandbox
     */
    async apiV1SandboxesPost(requestParameters: ApiV1SandboxesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessClaimResponse> {
        const response = await this.apiV1SandboxesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ApiV1SandboxesGetStatusEnum = {
    Starting: 'starting',
    Running: 'running',
    Failed: 'failed',
    Completed: 'completed'
} as const;
export type ApiV1SandboxesGetStatusEnum = typeof ApiV1SandboxesGetStatusEnum[keyof typeof ApiV1SandboxesGetStatusEnum];
