/* tslint:disable */
/* eslint-disable */
/**
 * Sandbox0 API
 * Public HTTP APIs exposed by Sandbox0 regional gateways and the global gateway.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AppendReplicaChangesRequest,
  CreateVolumeSyncBootstrapRequest,
  ErrorEnvelope,
  ResolveVolumeSyncConflictRequest,
  SuccessVolumeSyncAppendResponse,
  SuccessVolumeSyncBootstrapResponse,
  SuccessVolumeSyncChangeListResponse,
  SuccessVolumeSyncConflictListResponse,
  SuccessVolumeSyncConflictResponse,
  SuccessVolumeSyncReplicaResponse,
  UpdateSyncReplicaCursorRequest,
  UpsertSyncReplicaRequest,
  VolumeSyncBootstrapConflictErrorEnvelope,
  VolumeSyncReseedRequiredErrorEnvelope,
} from '../models/index';
import {
    AppendReplicaChangesRequestFromJSON,
    AppendReplicaChangesRequestToJSON,
    CreateVolumeSyncBootstrapRequestFromJSON,
    CreateVolumeSyncBootstrapRequestToJSON,
    ErrorEnvelopeFromJSON,
    ErrorEnvelopeToJSON,
    ResolveVolumeSyncConflictRequestFromJSON,
    ResolveVolumeSyncConflictRequestToJSON,
    SuccessVolumeSyncAppendResponseFromJSON,
    SuccessVolumeSyncAppendResponseToJSON,
    SuccessVolumeSyncBootstrapResponseFromJSON,
    SuccessVolumeSyncBootstrapResponseToJSON,
    SuccessVolumeSyncChangeListResponseFromJSON,
    SuccessVolumeSyncChangeListResponseToJSON,
    SuccessVolumeSyncConflictListResponseFromJSON,
    SuccessVolumeSyncConflictListResponseToJSON,
    SuccessVolumeSyncConflictResponseFromJSON,
    SuccessVolumeSyncConflictResponseToJSON,
    SuccessVolumeSyncReplicaResponseFromJSON,
    SuccessVolumeSyncReplicaResponseToJSON,
    UpdateSyncReplicaCursorRequestFromJSON,
    UpdateSyncReplicaCursorRequestToJSON,
    UpsertSyncReplicaRequestFromJSON,
    UpsertSyncReplicaRequestToJSON,
    VolumeSyncBootstrapConflictErrorEnvelopeFromJSON,
    VolumeSyncBootstrapConflictErrorEnvelopeToJSON,
    VolumeSyncReseedRequiredErrorEnvelopeFromJSON,
    VolumeSyncReseedRequiredErrorEnvelopeToJSON,
} from '../models/index';

export interface ApiV1SandboxvolumesIdSyncBootstrapArchiveGetRequest {
    id: string;
    snapshotId: string;
}

export interface ApiV1SandboxvolumesIdSyncBootstrapPostRequest {
    id: string;
    createVolumeSyncBootstrapRequest?: CreateVolumeSyncBootstrapRequest;
}

export interface ApiV1SandboxvolumesIdSyncChangesGetRequest {
    id: string;
    after?: number;
    limit?: number;
}

export interface ApiV1SandboxvolumesIdSyncConflictsConflictIdPutRequest {
    id: string;
    conflictId: string;
    resolveVolumeSyncConflictRequest: ResolveVolumeSyncConflictRequest;
}

export interface ApiV1SandboxvolumesIdSyncConflictsGetRequest {
    id: string;
    status?: string;
    limit?: number;
}

export interface ApiV1SandboxvolumesIdSyncReplayPayloadGetRequest {
    id: string;
    contentRef: string;
}

export interface ApiV1SandboxvolumesIdSyncReplicasReplicaIdChangesPostRequest {
    id: string;
    replicaId: string;
    appendReplicaChangesRequest: AppendReplicaChangesRequest;
}

export interface ApiV1SandboxvolumesIdSyncReplicasReplicaIdCursorPutRequest {
    id: string;
    replicaId: string;
    updateSyncReplicaCursorRequest: UpdateSyncReplicaCursorRequest;
}

export interface ApiV1SandboxvolumesIdSyncReplicasReplicaIdGetRequest {
    id: string;
    replicaId: string;
}

export interface ApiV1SandboxvolumesIdSyncReplicasReplicaIdPutRequest {
    id: string;
    replicaId: string;
    upsertSyncReplicaRequest: UpsertSyncReplicaRequest;
}

/**
 * 
 */
export class VolumeSyncApi extends runtime.BaseAPI {

    /**
     * Download a bootstrap snapshot archive for local-first sync
     */
    async apiV1SandboxvolumesIdSyncBootstrapArchiveGetRaw(requestParameters: ApiV1SandboxvolumesIdSyncBootstrapArchiveGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1SandboxvolumesIdSyncBootstrapArchiveGet().'
            );
        }

        if (requestParameters['snapshotId'] == null) {
            throw new runtime.RequiredError(
                'snapshotId',
                'Required parameter "snapshotId" was null or undefined when calling apiV1SandboxvolumesIdSyncBootstrapArchiveGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['snapshotId'] != null) {
            queryParameters['snapshot_id'] = requestParameters['snapshotId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/sandboxvolumes/{id}/sync/bootstrap/archive`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Download a bootstrap snapshot archive for local-first sync
     */
    async apiV1SandboxvolumesIdSyncBootstrapArchiveGet(requestParameters: ApiV1SandboxvolumesIdSyncBootstrapArchiveGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.apiV1SandboxvolumesIdSyncBootstrapArchiveGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a bootstrap snapshot and journal anchor for local-first sync
     */
    async apiV1SandboxvolumesIdSyncBootstrapPostRaw(requestParameters: ApiV1SandboxvolumesIdSyncBootstrapPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessVolumeSyncBootstrapResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1SandboxvolumesIdSyncBootstrapPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/sandboxvolumes/{id}/sync/bootstrap`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateVolumeSyncBootstrapRequestToJSON(requestParameters['createVolumeSyncBootstrapRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessVolumeSyncBootstrapResponseFromJSON(jsonValue));
    }

    /**
     * Create a bootstrap snapshot and journal anchor for local-first sync
     */
    async apiV1SandboxvolumesIdSyncBootstrapPost(requestParameters: ApiV1SandboxvolumesIdSyncBootstrapPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessVolumeSyncBootstrapResponse> {
        const response = await this.apiV1SandboxvolumesIdSyncBootstrapPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List volume sync journal entries
     */
    async apiV1SandboxvolumesIdSyncChangesGetRaw(requestParameters: ApiV1SandboxvolumesIdSyncChangesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessVolumeSyncChangeListResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1SandboxvolumesIdSyncChangesGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['after'] != null) {
            queryParameters['after'] = requestParameters['after'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/sandboxvolumes/{id}/sync/changes`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessVolumeSyncChangeListResponseFromJSON(jsonValue));
    }

    /**
     * List volume sync journal entries
     */
    async apiV1SandboxvolumesIdSyncChangesGet(requestParameters: ApiV1SandboxvolumesIdSyncChangesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessVolumeSyncChangeListResponse> {
        const response = await this.apiV1SandboxvolumesIdSyncChangesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Resolve or ignore a volume sync conflict
     */
    async apiV1SandboxvolumesIdSyncConflictsConflictIdPutRaw(requestParameters: ApiV1SandboxvolumesIdSyncConflictsConflictIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessVolumeSyncConflictResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1SandboxvolumesIdSyncConflictsConflictIdPut().'
            );
        }

        if (requestParameters['conflictId'] == null) {
            throw new runtime.RequiredError(
                'conflictId',
                'Required parameter "conflictId" was null or undefined when calling apiV1SandboxvolumesIdSyncConflictsConflictIdPut().'
            );
        }

        if (requestParameters['resolveVolumeSyncConflictRequest'] == null) {
            throw new runtime.RequiredError(
                'resolveVolumeSyncConflictRequest',
                'Required parameter "resolveVolumeSyncConflictRequest" was null or undefined when calling apiV1SandboxvolumesIdSyncConflictsConflictIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/sandboxvolumes/{id}/sync/conflicts/{conflict_id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"conflict_id"}}`, encodeURIComponent(String(requestParameters['conflictId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ResolveVolumeSyncConflictRequestToJSON(requestParameters['resolveVolumeSyncConflictRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessVolumeSyncConflictResponseFromJSON(jsonValue));
    }

    /**
     * Resolve or ignore a volume sync conflict
     */
    async apiV1SandboxvolumesIdSyncConflictsConflictIdPut(requestParameters: ApiV1SandboxvolumesIdSyncConflictsConflictIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessVolumeSyncConflictResponse> {
        const response = await this.apiV1SandboxvolumesIdSyncConflictsConflictIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List volume sync conflicts
     */
    async apiV1SandboxvolumesIdSyncConflictsGetRaw(requestParameters: ApiV1SandboxvolumesIdSyncConflictsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessVolumeSyncConflictListResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1SandboxvolumesIdSyncConflictsGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/sandboxvolumes/{id}/sync/conflicts`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessVolumeSyncConflictListResponseFromJSON(jsonValue));
    }

    /**
     * List volume sync conflicts
     */
    async apiV1SandboxvolumesIdSyncConflictsGet(requestParameters: ApiV1SandboxvolumesIdSyncConflictsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessVolumeSyncConflictListResponse> {
        const response = await this.apiV1SandboxvolumesIdSyncConflictsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Download a replay payload for one sync journal entry
     */
    async apiV1SandboxvolumesIdSyncReplayPayloadGetRaw(requestParameters: ApiV1SandboxvolumesIdSyncReplayPayloadGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1SandboxvolumesIdSyncReplayPayloadGet().'
            );
        }

        if (requestParameters['contentRef'] == null) {
            throw new runtime.RequiredError(
                'contentRef',
                'Required parameter "contentRef" was null or undefined when calling apiV1SandboxvolumesIdSyncReplayPayloadGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['contentRef'] != null) {
            queryParameters['content_ref'] = requestParameters['contentRef'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/sandboxvolumes/{id}/sync/replay-payload`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Download a replay payload for one sync journal entry
     */
    async apiV1SandboxvolumesIdSyncReplayPayloadGet(requestParameters: ApiV1SandboxvolumesIdSyncReplayPayloadGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.apiV1SandboxvolumesIdSyncReplayPayloadGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Append replica-originated sync journal entries
     */
    async apiV1SandboxvolumesIdSyncReplicasReplicaIdChangesPostRaw(requestParameters: ApiV1SandboxvolumesIdSyncReplicasReplicaIdChangesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessVolumeSyncAppendResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1SandboxvolumesIdSyncReplicasReplicaIdChangesPost().'
            );
        }

        if (requestParameters['replicaId'] == null) {
            throw new runtime.RequiredError(
                'replicaId',
                'Required parameter "replicaId" was null or undefined when calling apiV1SandboxvolumesIdSyncReplicasReplicaIdChangesPost().'
            );
        }

        if (requestParameters['appendReplicaChangesRequest'] == null) {
            throw new runtime.RequiredError(
                'appendReplicaChangesRequest',
                'Required parameter "appendReplicaChangesRequest" was null or undefined when calling apiV1SandboxvolumesIdSyncReplicasReplicaIdChangesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/sandboxvolumes/{id}/sync/replicas/{replica_id}/changes`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"replica_id"}}`, encodeURIComponent(String(requestParameters['replicaId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AppendReplicaChangesRequestToJSON(requestParameters['appendReplicaChangesRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessVolumeSyncAppendResponseFromJSON(jsonValue));
    }

    /**
     * Append replica-originated sync journal entries
     */
    async apiV1SandboxvolumesIdSyncReplicasReplicaIdChangesPost(requestParameters: ApiV1SandboxvolumesIdSyncReplicasReplicaIdChangesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessVolumeSyncAppendResponse> {
        const response = await this.apiV1SandboxvolumesIdSyncReplicasReplicaIdChangesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Advance a volume sync replica cursor
     */
    async apiV1SandboxvolumesIdSyncReplicasReplicaIdCursorPutRaw(requestParameters: ApiV1SandboxvolumesIdSyncReplicasReplicaIdCursorPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessVolumeSyncReplicaResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1SandboxvolumesIdSyncReplicasReplicaIdCursorPut().'
            );
        }

        if (requestParameters['replicaId'] == null) {
            throw new runtime.RequiredError(
                'replicaId',
                'Required parameter "replicaId" was null or undefined when calling apiV1SandboxvolumesIdSyncReplicasReplicaIdCursorPut().'
            );
        }

        if (requestParameters['updateSyncReplicaCursorRequest'] == null) {
            throw new runtime.RequiredError(
                'updateSyncReplicaCursorRequest',
                'Required parameter "updateSyncReplicaCursorRequest" was null or undefined when calling apiV1SandboxvolumesIdSyncReplicasReplicaIdCursorPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/sandboxvolumes/{id}/sync/replicas/{replica_id}/cursor`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"replica_id"}}`, encodeURIComponent(String(requestParameters['replicaId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateSyncReplicaCursorRequestToJSON(requestParameters['updateSyncReplicaCursorRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessVolumeSyncReplicaResponseFromJSON(jsonValue));
    }

    /**
     * Advance a volume sync replica cursor
     */
    async apiV1SandboxvolumesIdSyncReplicasReplicaIdCursorPut(requestParameters: ApiV1SandboxvolumesIdSyncReplicasReplicaIdCursorPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessVolumeSyncReplicaResponse> {
        const response = await this.apiV1SandboxvolumesIdSyncReplicasReplicaIdCursorPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a volume sync replica
     */
    async apiV1SandboxvolumesIdSyncReplicasReplicaIdGetRaw(requestParameters: ApiV1SandboxvolumesIdSyncReplicasReplicaIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessVolumeSyncReplicaResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1SandboxvolumesIdSyncReplicasReplicaIdGet().'
            );
        }

        if (requestParameters['replicaId'] == null) {
            throw new runtime.RequiredError(
                'replicaId',
                'Required parameter "replicaId" was null or undefined when calling apiV1SandboxvolumesIdSyncReplicasReplicaIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/sandboxvolumes/{id}/sync/replicas/{replica_id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"replica_id"}}`, encodeURIComponent(String(requestParameters['replicaId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessVolumeSyncReplicaResponseFromJSON(jsonValue));
    }

    /**
     * Get a volume sync replica
     */
    async apiV1SandboxvolumesIdSyncReplicasReplicaIdGet(requestParameters: ApiV1SandboxvolumesIdSyncReplicasReplicaIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessVolumeSyncReplicaResponse> {
        const response = await this.apiV1SandboxvolumesIdSyncReplicasReplicaIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Register or update a volume sync replica
     */
    async apiV1SandboxvolumesIdSyncReplicasReplicaIdPutRaw(requestParameters: ApiV1SandboxvolumesIdSyncReplicasReplicaIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessVolumeSyncReplicaResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1SandboxvolumesIdSyncReplicasReplicaIdPut().'
            );
        }

        if (requestParameters['replicaId'] == null) {
            throw new runtime.RequiredError(
                'replicaId',
                'Required parameter "replicaId" was null or undefined when calling apiV1SandboxvolumesIdSyncReplicasReplicaIdPut().'
            );
        }

        if (requestParameters['upsertSyncReplicaRequest'] == null) {
            throw new runtime.RequiredError(
                'upsertSyncReplicaRequest',
                'Required parameter "upsertSyncReplicaRequest" was null or undefined when calling apiV1SandboxvolumesIdSyncReplicasReplicaIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/sandboxvolumes/{id}/sync/replicas/{replica_id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"replica_id"}}`, encodeURIComponent(String(requestParameters['replicaId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpsertSyncReplicaRequestToJSON(requestParameters['upsertSyncReplicaRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessVolumeSyncReplicaResponseFromJSON(jsonValue));
    }

    /**
     * Register or update a volume sync replica
     */
    async apiV1SandboxvolumesIdSyncReplicasReplicaIdPut(requestParameters: ApiV1SandboxvolumesIdSyncReplicasReplicaIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessVolumeSyncReplicaResponse> {
        const response = await this.apiV1SandboxvolumesIdSyncReplicasReplicaIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
